javascript/benchmark/draw.py, javascript/packages/fury/lib/classResolver.ts, javascript/packages/fury/lib/codeGen.ts, javascript/packages/fury/lib/fury.ts, javascript/packages/fury/lib/internalSerializer/array.ts, javascript/packages/fury/lib/internalSerializer/binary.ts, javascript/packages/fury/lib/internalSerializer/bool.ts, javascript/packages/fury/lib/internalSerializer/datetime.ts, javascript/packages/fury/lib/internalSerializer/map.ts, javascript/packages/fury/lib/internalSerializer/number.ts, javascript/packages/fury/lib/internalSerializer/set.ts, javascript/packages/fury/lib/internalSerializer/string.ts, javascript/packages/fury/lib/type.ts, javascript/test/array.test.ts
currently, we generate switch statements for each type,  which results in long generated code. Therefore we are replacing the switch statements  with closure. This will reduce generated code size without sacrificing performance.
Closes #632
=> [JavaScript] reduce generated code size

.github/workflows/ci.yml, ci/run_ci.sh, java/pom.xml, python/pyfury/_fury.py, python/pyfury/_serialization.pyx, python/pyfury/_serializer.py, python/pyfury/_struct.py, python/pyfury/serializer.py, python/pyfury/tests/test_cross_language.py, python/pyfury/tests/test_serializer.py, python/pyfury/tests/test_struct.py
- Reenable FURY CI
- Fix fury CI failure
- Rename fury_ to fury
Closes #637
=> [CI] Enable Fury CI

java/fury-core/src/main/java/io/fury/Config.java, java/fury-core/src/main/java/io/fury/Fury.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/CollectionSerializers.java, java/fury-core/src/main/java/io/fury/serializer/GuavaSerializers.java, java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java, java/fury-core/src/test/java/io/fury/serializer/CollectionSerializersTest.java, java/fury-core/src/test/java/io/fury/serializer/GuavaSerializersTest.java, java/fury-core/src/test/java/io/fury/serializer/MapSerializersTest.java
register guava serialziers in advance for:
- ImmutableList
- ImmutableMap
- ImmutableSet
Closes #653
=> [Java] register guava serialziers in advance

java/fury-core/src/main/java/io/fury/Fury.java, java/fury-core/src/test/java/io/fury/FuryTest.java
Fix  IndexOutOfBoundsException when new fury deserialize from InputStream
Closes #670
=> [Java] Fix  IndexOutOfBoundsException when new fury deserialize from InputStream

.github/workflows/sync.yml, docs/guide/java_object_graph_guide.md, docs/guide/row_format_guide.md, docs/guide/xlang_object_graph_guide.md
Currently we use "---" as front matter to describe the doc order and title. But in GitHub markdown preview, it does not work fine. So we use the comment "" as front matter which can be previewed rightly in GitHub. When syncing to Fury site, we replace the comment front matter back to "---".
=> [Doc] support front matter

java/fury-core/src/main/java/io/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/io/fury/serializer/JavaSerializer.java, java/fury-core/src/test/java/io/fury/memory/MemoryBufferTest.java, java/fury-core/src/test/java/io/fury/serializer/JavaSerializerTest.java
Add utils to check Jdk serialization binary by check whether frist 2 bytes are `java.io.ObjectStreamConstants#STREAM_MAGIC`.
Users can use following pattern to upgrade serialization to fury in an async rolling-up way:
```java
if (JavaSerializer.serializedByJDK(bytes)) {
ObjectInputStream objectInputStream = xxx;
return objectInputStream.readObject();
} else {
return fury.deserialize(bytes);
}
```
This method is used only for scenario which client and server can't upgrade at the same time.
Closes #713
=> [Java] Jdk serialization binary check

ci/format.sh, javascript/.eslintrc.cjs, javascript/packages/fury/lib/codeGen.ts, javascript/packages/fury/lib/internalSerializer/array.ts, javascript/packages/fury/lib/internalSerializer/map.ts, javascript/packages/fury/lib/internalSerializer/set.ts, javascript/packages/fury/lib/internalSerializer/string.ts, javascript/packages/fury/lib/io.ts, javascript/packages/fury/lib/type.ts, javascript/packages/fury/lib/util.ts, javascript/packages/fury/package.json, javascript/test/protocol.test.ts
Make the protocols of rust and js consistent.
- update the hashing algorithm, now it calculates correctly.
- add xlang test. rust should be able to decode binary from python.
- vec updated to use var_int32
#738
=> [JavaScript] Make the protocols of rust and js consistent

.github/workflows/ci.yml
I created this PR #786 to change README.md, it is not the code but github action CI still running. To avoid unnecessary CI runs, it's best to prevent them from triggering when only non-code files have been modified.
Closes #xxxx
=> Don't let CI run when the changed files are not the code

java/fury-core/src/main/java/io/fury/serializer/StringSerializer.java, java/fury-core/src/test/java/io/fury/serializer/StringSerializerTest.java
support decode utf8 for java string serialization
Closes #805
=> [Java] support decode utf8 for java string serialization

javascript/packages/fury/index.ts, javascript/packages/fury/lib/classResolver.ts, javascript/packages/fury/lib/codeGen.ts, javascript/packages/fury/lib/fury.ts, javascript/packages/fury/lib/internalSerializer/any.ts, javascript/packages/fury/lib/type.ts, javascript/test/protocol.test.ts
- Add a tool function called Type.Any which would use the anySerializer during compile time. 
- Fixed a bug where the dependencies serializer was null when build anySerializer, so we can't init the dependencies serializer when build it. We replaced it by getting the serializer by ID or tag every time we read or write. However, this modification could hurt the performance of Type.Any.
Closes #813
=> [JavaScript] support polymorphism

java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/test/java/io/fury/CrossLanguageTest.java
fix isSecure check for xlang in java: register class by type tag only register serializer, but didn't register classes, which make class secure check failed.
#703
=> [Java] fix isSecure check for xlang in java

docs/protocols/README.md, docs/protocols/java_object_graph.md, docs/protocols/row_format.md, docs/protocols/xlang_object_graph.md
add  protocol doc wip
The complete protocol will be added later.
#652
=> [Doc] add  protocol wire format wip

java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/Serializers.java, java/fury-core/src/main/java/io/fury/serializer/StructSerializer.java, java/fury-core/src/test/java/io/fury/serializer/SerializersTest.java
Fury disabled serialization for jdk internal types which doesn't implement java.io.Serializable for security, but empty object is safe and used sometimes, so fury should support its serialization without disable serializable or class registration checks.
#826
=> [Java] register empty object by default

java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
`Lookup` creation is not cheap.
ClassValue is thread safe, and weakref,  we can use ClassValue to cache it.
Closes #xxxx
https://bugs.openjdk.org/browse/JDK-8136353
=> [Java] use java.lang.ClassValue to cache Lookup

ci/deploy.sh, ci/format.sh, ci/run_ci.sh
suppress maven download logs by `--no-transfer-progress`
Closes #xxxx
=> [Java] suppress maven download logs by --no-transfer-progress

ci/run_ci.sh, integration_tests/latest_jdk_tests/pom.xml, java/fury-core/src/main/java/io/fury/util/RecordComponent.java, java/fury-core/src/main/java/io/fury/util/RecordUtils.java
This pr add missing headers and enable latest jdk ci
Closes #xxxx
=> [CI] Fix checkstyle

.bazelrc, .github/workflows/release.yaml, CONTRIBUTING.md, bazel/fury_deps_setup.bzl, bazel/grpc-cython-copts.patch, bazel/grpc-python.patch, ci/deploy.sh, ci/run_ci.sh, python/pyfury/_util.pyx, python/setup.py
Support pyarrow6  bazel build.
We choose pyarrow 6.0.1 since pyarrow 7+ drop support for python3.6
Closes #860
=> [Python] Support pyarrow6 bazel build

java/fury-core/src/main/java/io/fury/Fury.java
Create Fury and print exception when failed. Many application will create fury as a static variable, Fury creation exception will be swallowed by NoClassDefFoundError. We print exception explicitly for better debugging.
Closes #886
=> [Java] print exception for fury creation

README.md, docs/guide/java_object_graph_guide.md, java/fury-core/src/main/java/io/fury/Fury.java, java/fury-core/src/main/java/io/fury/resolver/AllowListChecker.java, java/fury-core/src/main/java/io/fury/resolver/ClassChecker.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/test/java/io/fury/resolver/AllowListCheckerTest.java
Add class checker API and white/black list based implementation.
Example:
```java
{
Fury fury = Fury.builder().requireClassRegistration(false).build();
AllowListChecker checker = new AllowListChecker(AllowListChecker.CheckLevel.STRICT);
fury.getClassResolver().setClassChecker(checker);
checker.addListener(fury.getClassResolver());
assertThrows(InsecureException.class, () -> fury.serialize(new AllowListCheckerTest()));
checker.allowClass("io.fury.*");
fury.serialize(new AllowListCheckerTest());
checker.disallowClass("io.fury.*");
assertThrows(InsecureException.class, () -> fury.serialize(new AllowListCheckerTest()));
}
{
Fury fury = Fury.builder().requireClassRegistration(false).build();
AllowListChecker checker = new AllowListChecker(AllowListChecker.CheckLevel.WARN); …
```
=> [Java] Add class checker API

java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/io/fury/serializer/ChildContainerSerializers.java, java/fury-core/src/main/java/io/fury/serializer/CollectionSerializers.java, java/fury-core/src/main/java/io/fury/serializer/Container.java, java/fury-core/src/main/java/io/fury/serializer/GuavaSerializers.java, java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java, java/fury-core/src/main/java/io/fury/util/unsafe/_Collections.java
support immutable collection/map jit and generics optimization
Closes #896
=> [Java] support immutable collection/map jit and generics optimization

integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/ImmutableCollectionSerializersTest.java, integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/TestUtils.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/Container.java, java/fury-core/src/main/java/io/fury/serializer/ImmutableCollectionSerializers.java
The jdk9+ immutable collection is not registered and optimized in fury.
Currently users need to register those class by fury.register(List.of(1,2).getClass()) for serialization, or disable class registration by `FuryBuilder.requireClassRegistration(false)`, which is tedious.
More importantly , the serialization call writeReplace/readResolve to ensure jdk compatibilyty, which is not efficient.
And generics are not used either.
This PR optimize above all issues ,and support jit&generics optimization for such class.
.
Closes #820
=> [Java] Optimize jdk9+ immutable collection serialization 

java/fury-core/src/main/java/io/fury/builder/AccessorHelper.java, java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/io/fury/resolver/FieldResolver.java, java/fury-core/src/main/java/io/fury/type/Descriptor.java
optimize duplicate fields utils by useing ClassValue cache to avoid recreate it every time in different threads
Closes #xxxx
=> [Java] optimize duplicate fields utils

python/pyfury/format/row.pxi
Getter cache should bind with type instead of getter instance
Closes #xxxx
=> [Python] fix row format getter

java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
Skip `toString` in annotation invocation handler `readObject` by fury serialization.
Disclaimer:
This `toString` can be invoked only when Fury class registration disabled. Please don't disable it if your environent is not safe.
Closes #xxxx
=> [Java] Skip `toString` in annotation invocation handler `readObject`

docs/protocols/java_object_graph.md
add basic type java format doc
#652
=> [Doc] add basic type java format doc

integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/RecordSerializersTest.java, java/fury-core/src/test/java/io/fury/FuryTest.java, java/fury-core/src/test/java/io/fury/TestUtils.java, java/fury-core/src/test/java/io/fury/ThreadSafeFuryTest.java, java/fury-core/src/test/java/io/fury/builder/ObjectCodecBuilderTest.java, java/fury-core/src/test/java/io/fury/codegen/JaninoUtilsTest.java, java/fury-core/src/test/java/io/fury/collection/MultiKeyWeakMapTest.java, java/fury-core/src/test/java/io/fury/serializer/ClassUtils.java, java/fury-core/src/test/java/io/fury/serializer/CodegenCompatibleSerializerTest.java, java/fury-core/src/test/java/io/fury/serializer/CompatibleSerializerTest.java, java/fury-core/src/test/java/io/fury/serializer/MetaSharedCompatibleTest.java, java/fury-test-core/src/main/java/io/fury/test/bean/Struct.java, java/fury-test-core/src/test/java/io/fury/test/bean/StructTest.java
speed up test codegen speed by avoid duplicate codegen
Closes #930
=> [Java] speed test codegen speed by avoid duplicate codegen

java/fury-core/src/main/java/io/fury/Fury.java, java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/io/fury/resolver/ClassInfoHolder.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/resolver/FieldResolver.java, java/fury-core/src/main/java/io/fury/serializer/ArraySerializers.java, java/fury-core/src/main/java/io/fury/serializer/CollectionSerializers.java, java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java, java/fury-core/src/main/java/io/fury/serializer/MetaSharedSerializer.java, java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java, java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java, java/fury-core/src/main/java/io/fury/serializer/UnexistedClassSerializers.java
Rename classinfocache to classinfoholder
Closes #932
=> [Java] Rename classinfocache to classinfoholder

java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
This pr uses raw type serializer for getSerialzier in jit. The cast of Serializer to subclass serializer with generic is easy to raise compiler error for javac, so just use raw type.
Closes #xxxx
=> [Java] use raw type serializer for getSerialzier in jit

java/fury-core/src/main/java/io/fury/Fury.java, java/fury-core/src/main/java/io/fury/resolver/ClassInfo.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/CollectionSerializers.java, java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java, java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java, java/fury-core/src/main/java/io/fury/serializer/UnexistedClassSerializers.java, java/fury-core/src/test/java/io/fury/resolver/ClassResolverTest.java
This PR use varint for class id encoding to reduce java class writing space cost.
Before this PR, class id will be written as 3 bytes:
```java
| flag byte | two bytes short class id|
```
With this PR, class id will be written as 1~3 bytes, and for most common used jdk types such as String, class id will be written using 1 bytes, which is much more efficient.
Closes #944
=> [Java] use varint for class id encoding to reduce space cost

java/fury-core/src/main/java/io/fury/serializer/CollectionSerializers.java, java/fury-core/src/main/java/io/fury/serializer/GuavaSerializers.java, java/fury-core/src/main/java/io/fury/serializer/ImmutableCollectionSerializers.java, java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java, java/fury-core/src/main/java/io/fury/serializer/SynchronizedSerializers.java, java/fury-core/src/main/java/io/fury/serializer/UnmodifiableSerializers.java, java/fury-core/src/test/java/io/fury/serializer/CollectionSerializersTest.java
This PR fixed Collection/Map jit/interpreter protocol inconsisitency for generics instantiated subclass by remove auto generics infer for  Collection/Map subclass.
Closes #946
=> [Java] Fix Collection/Map jit/interpreter protocol inconsisitency for generics instantiated subclass

go/fury/slice.go
This pr add slice serializer for fury go:
- sliceSerializer
- sliceConcreteValueSerializer
- byteSliceSerializer
- boolSliceSerializer
- int16SliceSerializer
- int32SliceSerializer
- int64SliceSerializer
- float32SliceSerializer
- float64SliceSerializer
- stringSliceSerializer
- zero-copy for byteSlice
Closes #960
=> [Go] add slice serializer for fury go

go/fury/set.go
add set serializer for fury go
Closes #962
=> [Go] add set serializer for fury go

.github/workflows/ci.yml, go/fury/fury_xlang_test.go
This PR add fury xlang tests by execute pyfury module as a subprocess in fury go tests to validate xlang consistency.
Closes #972
=> [Go] Add fury xlang tests

java/fury-core/src/main/java/io/fury/ThreadLocalFury.java, java/fury-core/src/main/java/io/fury/ThreadSafeFury.java, java/fury-core/src/main/java/io/fury/pool/ThreadPoolFury.java, java/fury-core/src/test/java/io/fury/ThreadSafeFuryTest.java
This PR added serializeJavaObject API to ThreadSafeFury to improve the usability of `ThreadSafeFury`.
Before this pr, users need to use :
```
io.fury.ThreadSafeFury#execute(f - > f.serializeJavaObject())
```
which is a little inconvenient. Now users can just use `ThreadSafeFury#serializeJavaObject` directly.
Closes #xxxx
=> [Java] add serializeJavaObject API to ThreadSafeFury

go/fury/type.go
`stringPtrType = reflect.TypeOf((**string)(nil)).Elem()` will cause tinygo compilation error, this pr change it to:
```stringPtrType = reflect.TypeOf((*string)(nil))```
=> [Go] Make compilation support tinygo

README.md
The import path in the Go example is incorrect, updated it to the correct one.
Updated example: https://go.dev/play/p/a1I6Z49hzHl
Old example: https://go.dev/play/p/6D9YmHFwdpV
Error with old example:
```
go: finding module for package github.com/alipay/fury/fury/go/fury
go: downloading github.com/alipay/fury v0.2.0
main.go:3:8: module github.com/alipay/fury@latest found (v0.2.0), but does not contain package github.com/alipay/fury/fury/go/fury
```
(didn't open an issue, since this is so minor)
=> [go] fixed typo in readme import path

docs/protocols/java_object_graph.md, java/fury-benchmark/src/main/java/io/fury/benchmark/CompressStringSuite.java, java/fury-core/src/main/java/io/fury/serializer/Serializers.java, java/fury-core/src/main/java/io/fury/serializer/StringSerializer.java, java/fury-core/src/test/java/io/fury/serializer/StringSerializerTest.java, java/fury-format/README.md, java/fury-format/src/main/java/io/fury/format/row/Row.java, java/fury-format/src/main/java/io/fury/format/row/binary/BinaryRow.java
Fury use latin/utf 16 for string encoding ,but we named it to ascii. We updated to latin in furyjs, but forget to update it for java. This pr fix it by replacing it from ascii to latin
s
https://github.com/eishay/jvm-serializers/pull/89#issuecomment-1768633760
=> [Java] rename wrong ascii naming to latin

javascript/packages/fury/lib/reader.ts, javascript/packages/fury/package.json, javascript/packages/hps/package.json
1. upgrade npm package version
2. move cursor when read binary field
#1025
=> bugfix: read buffer error when object contain binary field

java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java, java/fury-core/src/test/java/io/fury/serializer/ReplaceResolveSerializerTest.java
fix jdk compatible serialization for inheritance: when a class implements JDK `writeReplace/readResolve`, and it implements `writeObject/readObject` in parent class, current implementation will ignore such method contract, and the serialization may fail. For example, if a field is marked as `transient`, the deserialization will raise NullPointerException.
Closes #1029
=> [Java] fix jdk compatible serialization for inheritance

README.md, docs/README.md, docs/guide/scala_guide.md
add scala user doc
Closes #1024
=> [Doc] add scala user doc

java/fury-benchmark/src/main/java/io/fury/benchmark/NewJava11StringSuite.java, java/fury-benchmark/src/main/java/io/fury/benchmark/NewStringSuite.java, java/fury-core/src/main/java/io/fury/serializer/Serializers.java, java/fury-core/src/main/java/io/fury/serializer/StringSerializer.java, java/fury-core/src/test/java/io/fury/serializer/StringSerializerTest.java
This pr supported bytes string serialization for jdk8 by removing all jdk version check in `StringSerializer`
Closes #1038
=> [Java] support bytes string serialization for jdk8

java/fury-core/src/main/java/io/fury/Fury.java, java/fury-core/src/test/java/io/fury/FuryTest.java
The `InputStream#read()` API allows for an implementation to only partially read the requested number of bytes. Update the calls in `Fury#deserialize()` and `Fury#deserializeFromStream()` to account for this.
=> [Java] Allow for `InputStream` not reading entire length

java/fury-core/src/main/java/io/fury/serializer/ExternalizableSerializer.java, java/fury-core/src/test/java/io/fury/serializer/ExternalizableSerializerTest.java, java/fury-core/src/test/java/io/fury/serializer/test/A.java, java/fury-core/src/test/java/io/fury/serializer/test/Factory.java, java/fury-core/src/test/java/io/fury/serializer/test/Inaccessible.java
When deserializing an `Externalizable` object, it may end up throwing an exception, as the class may be declared as non-public in another package and thus isn't accessible from the serializer. Fix this by using the `ReflectionUtils.getCtrHandle()` utility.
=> [Java] Use `ReflectionUtils.getCtrHandle()` in `ExternalizableSerializer`

java/pom.xml
I find that many open source projects do this, like flink, streampark, etc. I think it is better to set maven-spotless-plugin-version as a parameter
=> [Improve] make maven-spotless-plugin version as a parameter

java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/JavaSerializer.java, java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java, java/fury-core/src/test/java/io/fury/FuryTestBase.java, java/fury-core/src/test/java/io/fury/TestUtils.java, java/fury-core/src/test/java/io/fury/serializer/ReplaceResolveSerializerTest.java
This PR supports Externalizable which has  a `writeReplace/readResolve` defined by spec: https://docs.oracle.com/javase/8/docs/platform/serialization/spec/output.html. The `writeReplace` can return same type object or different tyoe object, or just return itself.
Closes #1045
=> [Java] support writeReplace/readResolve for Externalizable

docs/guide/scala_guide.md, java/fury-core/src/main/java/io/fury/config/Config.java, java/fury-core/src/main/java/io/fury/config/FuryBuilder.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/scala/SingletonObjectSerializer.java, java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java, scala/README.md, scala/src/test/scala/io/fury/serializer/CollectionSerializerTest.scala, scala/src/test/scala/io/fury/serializer/SingleObjectSerializerTest.scala
This PR optimizes scala `object` serialization be special serializer. To avoid scala check overhead, this PPR introduce a `withScalaOptimization` option which is disabled by default. When this option is enabled, `io.fury.serializer.scala.SingletonObjectSerializer` will be used for `singleton object ` serialization.
The `SingletonObjectSerializer` is put into java source code since the implementation is simple.
Complex scala integration will be put into `fury/scala` directory instead.
Closes #764
=> [Scala] add scala singleton object serializer

java/fury-core/src/main/java/io/fury/codegen/Expression.java, java/fury-core/src/test/java/io/fury/codegen/ExpressionTest.java
Empty ListExpression invoke genCode will throw npe. this pull request fix this bug.
=> Empty ListExpression#genCode will throw npe

docs/guide/scala_guide.md, scala/src/main/java/io/fury/serializer/scala/ScalaDispatcher.java, scala/src/main/scala/io/fury/serializer/scala/CollectionSerializer.scala, scala/src/main/scala/io/fury/serializer/scala/MapSerializer.scala, scala/src/test/scala/io/fury/serializer/CollectionSerializerTest.scala
This PR integrates  scala collection serialization with fury java collection framework based on  `io.fury.serializer.collection.AbstractCollectionSerializer/AbstractMapSerializer` introduced in #1062.
The main idea behind this PR is that all scala collections serialization are handled by `scala.collection.generic.DefaultSerializable`. So we can intercept all such subclasses in a `io.fury.serializer.SerializerFactory` implementation to forward the serialization to fury implemented scala collection serializers.
The serialization for such collection will have following stages:
- `onCollectionWrite`: write collection size and scala collection factory, then return a `java.util.Collection` adapter for fury java collection framework to invoke.
- Fury java collection framework write all …
=> [Scala] integrate scala collection with fury java collection framework

.github/workflows/ci.yml, scala/build.sbt, scala/src/main/scala/io/fury/serializer/scala/CollectionSerializer.scala
* Code needs small hack for spliterator - won't compile in Scala 3 otherwise - possible Scala 3 compiler bug
* removes Scala 2.12 build option beause existing code uses Scala `Factory` class that was only added in Scala 2.13 - if you want to support Scala 2.12, new Scala 2.12 specific code is needed
* updates CI to use `+test` which tests with all the `crossScalaVersions` and gets rid of setup-scala action that is deprecated in favour of setup-java - sbt build tool installs the Scala version it needs anyway so no need to pre-install Scala
=> [Scala] get build to work with Scala 3

java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/io/fury/type/ScalaTypes.java, java/fury-core/src/main/java/io/fury/type/TypeUtils.java, scala/src/main/java/io/fury/serializer/scala/ScalaDispatcher.java
-  Support scala collection jit serialization
- Relax `ScalaDispatcher` to intercept all scala map/seq/set types.
Closes #1076 
#765
=> [Scala] support scala collection jit serialization

java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/collection/AbstractCollectionSerializer.java, java/fury-core/src/test/java/io/fury/serializer/collection/CollectionSerializersTest.java
When all elements are null, actual collection  element type will be null. If there is no collection generics, the declared collection element type will be null too, then serialization for such collection will throw NullPointerException:
Closes #1085
=> [Java] Fix collection serialization NPE when all elements are null

java/fury-core/src/main/java/io/fury/pool/FuryPooledObjectFactory.java
Before this refactor, when pooled fury cache not present:
1. double check cache present
2. put in cache
3. recursive call get function
In order to avoid recursive call, we could return cached obj or newly added cache object
thus rename addCache to getOrAddCache
=> [Java] FuryPooledObjectFactory getFury refactor, remove redundant recursive call

src/fury/util/util.h
- Simplify the implementation of `IsOneOf`
- Simplify the implementation of `To/FromBig/LittleEndian` via `if constexpr`
BTW I think maybe there's no difference between `ToXXXEndian` and `FromXXXEndian`.
=> Simplify endian utility functions and `IsOneOf`

rust/fury/src/deserializer.rs, rust/fury/src/error.rs, rust/fury/src/types.rs
Check xlang flag, currently Rust only supports xlang. If the flag is unsupported, we should generate a friendly error.
Closes #1111
=> chore: check xlang flag

rust/fury/src/serializer.rs
Rust does not yet support native data, so we should set the language flag as Xlang.
Closes #1119
=> [Rust] Correct language flag

.bazelrc, .github/workflows/ci.yml, .github/workflows/release-java.yaml, .github/workflows/release.yaml, bazel/arrow/pyarrow_configure.bzl, bazel/fury.bzl, bazel/fury_deps_setup.bzl, ci/deploy.sh, ci/run_ci.sh, docs/guide/DEVELOPMENT.md, java/pom.xml, python/pyfury/type.py, python/setup.py
- Support python3.11/12
- Drop python 3.6 support
- Use pyarrow==14.0.0
- Use pyarrow==12 for python3.7
Closes #1118
=> [Python] Support python3.11/12

docs/guide/DEVELOPMENT.md
=> rust/doc : add rust building

src/fury/row/writer.cc, src/fury/row/writer.h
- Make Writer::WriteString accept const reference
- Remove the rvalue reference one since it's same
=> [C++] Remove useless overload of Writer::WriteString

src/fury/util/status.h
- Make assignment operator return reference
- Add move ctor and move assignment operator for Status
=> [C++] Add move ctor/assign op to Status

java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/collection/CollectionSerializers.java, java/fury-core/src/main/java/io/fury/serializer/collection/MapSerializers.java, scala/src/test/scala/io/fury/serializer/CollectionSerializerTest.scala
When a class contains a field of scala list/map type, fury will returna ReplaceResolver serializer if `io.fury.serializer.scala.ScalaDispatcher` is not set, which will serializer CastException, since we assume all map/collection serializers all extends `AbstractMapSerializer/AbstractCollectionSerializer`
Fix scala collection serialization nested in pojo
Closes #1137
=> [Scala] Fix scala collection serialization nested in pojo

java/fury-core/src/main/java/io/fury/serializer/Serializers.java, java/fury-core/src/main/resources/META-INF/native-image/org.furyio/fury-core/native-image.properties
make sting builder serializer codegen eager to avoid graalvm create serializer exception at native image runtime:
```java
java.lang.InternalError: com.oracle.svm.core.jdk.UnsupportedFeatureError: Defining hidden classes at runtime is not supported.
at java.base@17.0.9/java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:500)
at java.base@17.0.9/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:402)
at java.base@17.0.9/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:315)
at java.base@17.0.9/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:341)
at io.fury.util.unsafe._JDKAccess.makeGetterFunction(_JDKAccess.java:283)
at …
```
=> [Java] make sting builder serializer codegen eager

ci/run_ci.sh
=> fix/rust: fix rust ci bug

src/fury/encoder/row_encoder.h, src/fury/meta/BUILD, src/fury/meta/field_info.h, src/fury/meta/type_traits.h, src/fury/meta/type_traits_test.cc
It will prevent such code to be successfully compiled:
(previously, such code can be compiled without error, which make code error-prone.)
```c++
struct A {
int x;
float y;
};
FURY_FIELD_INFO(A, x, y, x); // compile error: duplicated fields in FURY_FIELD_INFO arguments are detected
```
Besides, we move type traits to `meta/type_traits.h`.
=> [C++] Add duplicated fields detection in `FURY_FIELD_INFO` macro

src/fury/encoder/row_encoder.h, src/fury/encoder/row_encoder_test.cc, src/fury/meta/type_traits.h, src/fury/row/writer.cc, src/fury/row/writer.h, src/fury/util/BUILD, src/fury/util/buffer.h, src/fury/util/util.h
We support `std::string` and `std::string_view` in RowEncoder, e.g.
```c++
struct B {
int num;
std::string str;
};
FURY_FIELD_INFO(B, num, str);
RowWriter writer(encoder::RowEncodeTrait<B>::Schema());
writer.Reset();
B b{233, "hello"};
encoder::RowEncodeTrait<B>::Write(b, writer);
```
Besides, I move `IsOneOf` from `util` to `meta`.
And I think maybe we can rename `util.h` to something like `bit_util.h`, `time_util.h` and other `xxx_util.h`, so that it will not become a very messy source file that all developer want to put something into it since the name `util` is too general. cc @chaokunyang
=> [C++] Support string type in RowEncoder

integration_tests/graalvm_tests/src/main/java/io/fury/graalvm/Main.java, integration_tests/graalvm_tests/src/main/java/io/fury/graalvm/ThreadSafeExample.java, java/fury-core/src/main/java/io/fury/Fury.java, java/fury-core/src/main/java/io/fury/ThreadLocalFury.java, java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/io/fury/codegen/CodeGenerator.java, java/fury-core/src/main/java/io/fury/collection/MultiKeyWeakMap.java, java/fury-core/src/main/java/io/fury/config/Config.java, java/fury-core/src/main/java/io/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/io/fury/serializer/Serializers.java, java/fury-core/src/main/java/io/fury/serializer/scala/SingletonCollectionSerializer.java, java/fury-core/src/main/java/io/fury/serializer/scala/SingletonMapSerializer.java, java/fury-core/src/main/java/io/fury/serializer/scala/SingletonObjectSerializer.java, java/fury-core/src/main/java/io/fury/serializer/shim/ShimDispatcher.java, java/fury-core/src/main/java/io/fury/util/GraalvmSupport.java, java/fury-core/src/main/java/io/fury/util/Platform.java, java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java, java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java, java/fury-core/src/main/resources/META-INF/native-image/org.furyio/fury-core/native-image.properties, java/fury-format/src/main/java/io/fury/format/encoder/RowEncoderBuilder.java
Support thread safe fury for graalvm native image by cache generated serializer for query by other fury.
Usage example:
```java
import io.fury.Fury;
import io.fury.ThreadLocalFury;
import io.fury.ThreadSafeFury;
import io.fury.util.Preconditions;
import java.util.List;
import java.util.Map;
public class Example {
static ThreadSafeFury fury;
static {
fury = new ThreadLocalFury(classLoader -> {
Fury f = Fury.builder().requireClassRegistration(true).build();
// register and generate serializer code.
f.register(Foo.class, true);
return f;
});
}
public static void main(String[] args) {
Preconditions.checkArgument("abc".equals(fury.deserialize(fury.serialize("abc"))));
Preconditions.checkArgument(List.of(1,2,3).equals(fury.deserialize(fury.serialize(List.of(1,2,3)))));
Map<String, Integer> map …
```
=> [Java] Support thread safe fury for graalvm native image

python/pyfury/includes/libutil.pxd, src/fury/row/row.h, src/fury/row/writer.cc, src/fury/row/writer.h, src/fury/util/BUILD, src/fury/util/bit_util.h, src/fury/util/buffer.cc, src/fury/util/buffer.h, src/fury/util/logging.cc, src/fury/util/time_util.cc, src/fury/util/time_util.h, src/fury/util/time_util_test.cc
`util/util.h` is splitted to `util/bit_util.h` and `util/time_util.h`.
namespace `BitUtil` is renamed to `util`.
=> [C++] Split util.h to bit_util.h and time_util.h

src/fury/encoder/row_encoder.h, src/fury/encoder/row_encoder_test.cc
Now we can add cv qualifiers to field types ,e.g.
```c++
struct A {
const int x;
volatile float y;
}
FURY_FIELD_INFO(A, x, y);
...
```
=> [C++] Support cv-qualified types in row encoder

src/fury/encoder/row_encoder.h, src/fury/encoder/row_encoder_test.cc
Nested struct/class types is finally supported! e.g
```c++
struct A { ... };
FURY_FIELD_INFO(A, ...);
struct B { ... };
FURY_FIELD_INFO(B, ...);
struct D {
int x;
A y;
B z;
};
FURY_FIELD_INFO(D, x, y, z);
RowWriter writer(encoder::RowEncodeTrait<D>::Schema());
writer.Reset();
D d{233, {234, 3.14, true}, {235, "hi"}};
encoder::RowEncodeTrait<D>::Write(d, writer);
...
```
=> [C++] Add support for nested class types in row encoder

rust/fury-derive/src/fury_meta.rs, rust/fury-derive/src/fury_row.rs, rust/fury/src/deserializer.rs, rust/fury/src/error.rs, rust/fury/src/lib.rs, rust/fury/src/row/reader.rs, rust/fury/src/row/row.rs, rust/fury/src/row/writer.rs, rust/fury/src/serializer.rs, rust/tests/tests/test_row.rs
1. Ensure that the library only exports the necessary modules.
2. Rust row format support Map.
Add a new binary accessor named MapGetter, which wraps two ArrayGetter instances to access keys and values. Additionally, include a function to convert keys and values into a BTreeMap.
usage:
```rust
#[test]
fn rowmap() {
#[derive(FuryRow)]
struct Foo {
f5: BTreeMap<String, String>,
}
let mut f5: BTreeMap<String, String> = BTreeMap::new();
f5.insert(String::from("k1"), String::from("v1"));
f5.insert(String::from("k2"), String::from("v2"));
let row = to_row(&Foo {
f5,
},);
let obj = from_row::<Foo>(&row);
let binding = obj.f5();
assert_eq!(binding.keys().size(), 2);
assert_eq!(binding.keys().get(0), "k1");
assert_eq!(binding.values().size(), 2);
assert_eq!(binding.values().get(0), "v1");
let f5 = …
```
=> [Rust] Support row map

docs/guide/DEVELOPMENT.md
We update bazel version to 6.3.2 in #1064  but didn't update the doc. This PR update bazel version from 4.2 to 6.3.2
#1064
=> [C++] update bazel version from 4.2 to 6.3.2

javascript/packages/fury/lib/description.ts, javascript/packages/fury/lib/internalSerializer/bool.ts, javascript/packages/fury/lib/internalSerializer/datetime.ts, javascript/packages/fury/lib/internalSerializer/number.ts, javascript/packages/fury/lib/internalSerializer/string.ts, javascript/packages/fury/lib/referenceResolver.ts, javascript/packages/fury/lib/util.ts, javascript/packages/fury/package.json, javascript/test/object.test.ts
1. JavaScript is a dynamic language, so the object being serialized may lack certain properties. We should handle partial objects by adding default values for non-referencable types and making the description of object field types optional.
2. Sometimes, webpack may mock the process object, which can break environment detection. To mitigate this, we can detect the process.version.node property, as it is usually not mocked.
Closes #1207
=> [JavaScript] Support partial record

java/fury-core/src/main/java/io/fury/builder/AccessorHelper.java, java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/io/fury/codegen/CodeGenerator.java, java/fury-core/src/main/java/io/fury/codegen/CodegenContext.java, java/fury-core/src/test/java/io/fury/FuryTest.java, java/fury-core/src/test/java/io/fury/builder/AccessorHelperTest.java, java/fury-core/src/test/java/io/fury/builder/pkg/AccessLevelClass.java, scala/src/test/scala/io/fury/serializer/ScalaTest.scala
=> [Java] fix package access level class accessor jit

javascript/packages/fury/lib/codeGen.ts, javascript/packages/fury/package.json
I found an issue that if we register a description twice, in the second times, the result of `genSerializer` is undefined.
Closes #xxxx
=> [JavaScript] Fix register a description twice will get undefined serializer

src/fury/encoder/row_encode_trait.h, src/fury/encoder/row_encode_trait_test.cc, src/fury/encoder/row_encoder_test.cc, src/fury/meta/type_traits.h, src/fury/meta/type_traits_test.cc, src/fury/row/writer.h
In this PR we support any iterable types for `RowEncodeTrait` and its combination with struct types, e.g.
```c++
std::vector<int>
// nested array type
std::vector<std::vector<int>>
// class type in array type
struct A { ... }
std::vector<A>
// array in class type
struct B {
std::vector<...> field1;
...
}
```
=> [C++] Support iterable types in RowEncodeTrait

javascript/package.json, javascript/packages/fury/lib/codeGen.ts, javascript/packages/fury/lib/description.ts, javascript/packages/fury/lib/internalSerializer/tuple.ts, javascript/packages/fury/lib/type.ts, javascript/test/__snapshots__/codeGen.test.ts.snap, javascript/test/codeGen.test.ts, javascript/test/fixtures/tuple.ts, javascript/test/tuple.test.ts
Implements tuple serializer
In many language, there is a data structure called tuple, but the fury specification has not defined tuple behaviours.
so I am using Array as Tuple.
and also thanks to @wangweipeng2 for his teaching, he also has a lot contribution for this pr.
Closes #xxxx
=> [JavaScript] Implements tuple serializer

rust/fury-derive/src/fury_row.rs, rust/fury/src/lib.rs, rust/fury/src/row/mod.rs, rust/fury/src/row/reader.rs, rust/fury/src/row/row.rs, rust/fury/src/row/writer.rs
1. Removing unnecessary abstractions, as unreachable code can be confusing for developers.
2. Use a FieldWriteHepler to reuse code instead of implement trait to avoid unreachable code
Closes #1224
=> [Rust] Remove unnecessary abstraction

docs/guide/graalvm_guide.md, java/fury-core/src/main/java/io/fury/config/FuryBuilder.java
Graalvm doesn't support JIT, we should disable fury async compilation for graalvm, otherwise threads will be created at graalvm build time, which is disallowed, and Fury codegen may not be finished at graalvm build time too.
#678
=> [Java] disable async compilation for graalvm

javascript/packages/fury/lib/internalSerializer/string.ts, javascript/packages/fury/lib/reader.ts, javascript/test/io.test.ts, javascript/test/reader.test.ts
Add more methods for BinaryReader
In real world scene, we need do many opreation on binary, it is better to have an buffer ref method to get a buffer reference instead of get a copy of the original buffer.
=> [JavaScript] Add more methods for BinaryReader

src/fury/util/time_util.cc
In FormatTimePoint we don't need to use std::stringstream and even std::string.
=> [C++] Improve FormatTimePoint by removing sstream

docs/protocols/java_object_graph.md
=> [Doc][Spec] fury java spec

.github/sync.yml, docs/guide/DEVELOPMENT.md, docs/guide/graalvm_guide.md, docs/guide/java_object_graph_guide.md, docs/guide/row_format_guide.md, docs/guide/scala_guide.md, docs/guide/xlang_object_graph_guide.md
The structure and frontmatter of the site has some changes, so it is necessary to ensure that the results synced over remain consistent
=> [DOC] doc sync stay consistent with the site

javascript/packages/fury/lib/classResolver.ts, javascript/packages/fury/lib/codeGen.ts, javascript/packages/fury/lib/platformBuffer.ts, javascript/packages/fury/lib/util.ts, javascript/test/__snapshots__/codeGen.test.ts.snap
Previously, everytime we write tag, we create new BufferWriter, we alloc new Buffer pool, this is no need.
=> [JavaScript] Improve tag write performance

README.md
- use apache group id for snapshot version
- use furyio group id for release version until released first version under apache
=> update fury java install

java/fury-format/src/test/java/org/apache/fury/format/CrossLanguageTest.java
Once the test is completed, this change deletes the temporary file created in CrossLanguageTest.
https://github.com/apache/incubator-fury/issues/1276
=> [Java] Clean-up of tmp files created in CrossLanguageTest

java/fury-core/src/main/java/org/apache/fury/AbstractThreadSafeFury.java, java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/ThreadLocalFury.java, java/fury-core/src/main/java/org/apache/fury/ThreadSafeFury.java, java/fury-core/src/main/java/org/apache/fury/pool/ClassLoaderFuryPooled.java, java/fury-core/src/main/java/org/apache/fury/pool/FuryPooledObjectFactory.java, java/fury-core/src/main/java/org/apache/fury/pool/ThreadPoolFury.java, java/fury-core/src/main/java/org/apache/fury/util/LoaderBinding.java, java/fury-core/src/test/java/org/apache/fury/ThreadSafeFuryTest.java
=> [Java] Support registration in thread safe fury

java/fury-core/src/main/java/org/apache/fury/util/MurmurHash3.java, licenserc.toml
feels wrong to add an ASL when the code is borrowed and the source is not Apache licensed
=> [JAVA] remove license header from MurmurHash3

README.md
Many users have been asking if it's possible to use Fury without modifying any code. Our original doc was that no additional code changes would be required, but it is still necessary to replace the serialization calls with Fury. Therefore, our previous description was ambiguous. This PR removes such ambiguity from our document.
=> [Java] remove vague desc in drop-in replacement jdk serialization libs

.bazelrc, BUILD, bazel/fury.bzl, src/fury/BUILD, src/fury/columnar/BUILD, src/fury/encoder/BUILD, src/fury/meta/BUILD, src/fury/row/BUILD, src/fury/thirdparty/BUILD, src/fury/util/BUILD
When compiled using Windows bazel, the following error occurs:
```
cl: 命令行 warning D9002 :忽略未知选项“-pthread”
cl: 命令行 warning D9002 :忽略未知选项“-std=c++17”
time_util.cc
src/fury/util/time_util.cc(43): warning C4477: “snprintf”: 格式字符串“%03ld”需要类型“long”的参数，但可变参数 1 拥有了类型“_Rep”        with
[
_Rep=__int64
]
src/fury/util/time_util.cc(43): note: 请考虑在格式字符串中使用“%lld”
src/fury/util/time_util.cc(43): note: 请考虑在格式字符串中使用“%Id”
src/fury/util/time_util.cc(43): note: 请考虑在格式字符串中使用“%I64d”
INFO: From Compiling absl/debugging/failure_signal_handler.cc:
failure_signal_handler.cc
INFO: From Compiling absl/strings/str_replace.cc:
str_replace.cc
INFO: From Compiling absl/strings/match.cc:
match.cc
INFO: From Compiling absl/strings/internal/stringify_sink.cc:
stringify_sink.cc
ERROR: …
```
=> [C++] Windows build support

bazel/arrow/pyarrow_configure.bzl
Some linux distributions do not have `python` by default, and some make `python` point to python2 instead of python3.
=> [C++] Use python3 instead of python in bazel build

java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractCollectionSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/ChildContainerSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/FuryArrayAsListSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/GuavaCollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/ImmutableCollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializers.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/ChildContainerSerializersTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/CollectionSerializersTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java, scala/src/main/scala/org/apache/fury/serializer/scala/CollectionSerializer.scala, scala/src/main/scala/org/apache/fury/serializer/scala/MapSerializer.scala
Closes #1305 
Nested collection outer deserialization may read `num elements` for internal collection, which will make deserialization fail.
Currently only `StringKeyMapSerializer` has this bug, but future customized may have this issue. This PR make  `num elements` defensive from such cases by using a read and reset pattern.
=> [Java] fix nested collection num elements

.github/workflows/sync.yml, docs/guide/DEVELOPMENT.md, docs/guide/graalvm_guide.md, docs/guide/java_object_graph_guide.md, docs/guide/row_format_guide.md, docs/guide/scala_guide.md, docs/guide/xlang_object_graph_guide.md
We can just keep these head metadata as it is instead of replacing with html comments.
It will display in a normal manner on GitHub.
=> Keep head metadata as is in docs

docs/guide/DEVELOPMENT.md
=> [DOC] Refine build steps and wording in DEVELOPMENT

javascript/packages/fury/lib/description.ts, javascript/packages/fury/lib/gen/enum.ts, javascript/packages/fury/lib/gen/index.ts, javascript/packages/fury/lib/meta.ts, javascript/packages/fury/lib/type.ts, javascript/test/enum.test.ts
Implement the Enum type which declare in SPEC.
Usage: 
```TypeScript
enum Foo {
f1 = 1,
f2 = 2
}
const fury = new Fury({ refTracking: true });   
const {serialize, deserialize} = fury.registerSerializer(Type.enum(Foo)) 
const input = serialize(Foo.f1);
const result = deserialize(
input
);
expect(result).toEqual(Foo.f1)
```
=> feat(JavaScript): Implement Enum 

BUILD, src/fury/BUILD, src/fury/columnar/BUILD, src/fury/encoder/BUILD, src/fury/meta/BUILD, src/fury/row/BUILD, src/fury/thirdparty/BUILD, src/fury/util/BUILD
Remove unused bazel rulers, e.g. `cc_binary`.
=> chore(C++): Remove unused bazel rulers

.github/workflows/ci.yml, ci/run_ci.py
Implement C++ CI scripts using python.
=> ci(c++): Implement C++ CI scripts using python

java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/CompatibleCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecOptimizer.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/resolver/FieldResolver.java, java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/MetaSharedSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/ObjectSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractCollectionSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java, java/fury-core/src/main/java/org/apache/fury/type/ClassDef.java, java/fury-core/src/main/java/org/apache/fury/type/Descriptor.java, java/fury-core/src/main/java/org/apache/fury/type/DescriptorGrouper.java, java/fury-core/src/main/java/org/apache/fury/type/GenericType.java, java/fury-core/src/main/java/org/apache/fury/util/ReflectionUtils.java, java/fury-core/src/test/java/org/apache/fury/FuryTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/ArraySerializersTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedCompatibleTest.java
`Object[]` can be assigned from `String[]` and other arrays, we take it as a final type before, so we skip writing classinfo for such types and lost object type too.
This PR fix this polymorphic array serialization bug by checking array type polymorphism by component type.
Closes #1323
=> fix(java): fix polymorphic array serialization

javascript/packages/fury/lib/gen/index.ts, javascript/packages/fury/lib/writer.ts, javascript/packages/fury/package.json
some old compiler did not recognize the `?.` expression(sadly).
=> chore(JavaScript): Drop optional chaining expression

rust/fury/src/lib.rs, rust/fury/src/row/writer.rs, rust/fury/src/types.rs
1. Dismiss warnings
2. Fix incorrect type conversions which cause the failures in #1332
=> fix(Rust): incorrect cast

.github/workflows/ci.yml, ci/run_ci.py
Rust ci is ported from `run_ci.sh` to `run_ci.py`.
=> feat(ci): Rust ci is ported from run_ci.sh to run_ci.py

java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java
Both `false` and `null` will determine `ENABLE_CLASS_REGISTRATION_FORCIBLY` as `false`, so there is no need to take this extra step.
=> chore(java): Remove redundant code

go/fury/buffer.go
=> fix(go):  fix comment error, should be 1-5 byte

.github/workflows/ci.yml, javascript/jest.config.js, javascript/package.json, javascript/packages/fury/package.json, javascript/test/reader.test.ts, javascript/test/string.test.ts, javascript/test/writer.test.ts
1. JavaScript codebase contains a c++ module which requires the nodejs version greater than 20, we should ignore it when the version is not satisfied to prevent it from breaking test ci
2. Remove coverage threshold  temporarily before the xlang protocol release
3. Add 14.x and 16.x to the docker envs
#1350
=> chore(JavaScript): Fix JavaScript test CI

.github/workflows/ci.yml, ci/run_ci.sh, javascript/jest.config.js, javascript/packages/hps/package.json
1. Npm 6 doesn't support workspace, upgrade it before run test
2. There are Some node-gyp compile problems on windows, ignore it temporary
#1350
=> chore(JavaScript): fix test ci on early Node

javascript/packages/hps/package.json
When using `npm run build` or `npm run test`, the hps module will still be compiled, resulting in an error.
=> chore(JavaScript): Fix using npm run build error

.github/workflows/ci.yml, ci/run_ci.py
1. JavaScript CI implemented using python.
2. Enable windows CI and macos CI for JavaScript.
=> ci(JavaScript): JavaScript ci is ported from run_ci.sh to run_ci.py

javascript/package.json, javascript/packages/fury/lib/description.ts, javascript/packages/fury/lib/fury.ts, javascript/packages/fury/lib/gen/any.ts, javascript/packages/fury/lib/gen/builder.ts, javascript/packages/fury/lib/gen/index.ts, javascript/packages/fury/lib/gen/object.ts, javascript/packages/fury/lib/gen/oneof.ts, javascript/packages/fury/lib/gen/serializer.ts, javascript/packages/fury/lib/meta.ts, javascript/packages/fury/lib/platformBuffer.ts, javascript/packages/fury/lib/reader/index.ts, javascript/packages/fury/lib/referenceResolver.ts, javascript/packages/fury/lib/type.ts, javascript/packages/hps/index.ts, javascript/test/any.test.ts, javascript/test/oneof.test.ts
Before:
```JavaScript
// reader/index.ts
function writeVarInt32() {
buffer.byteLength
}
```
After:
```JavaScript
// reader/index.ts
const byteLength = buffer.byteLength;
function writeVarInt32() {
byteLength
}
```
The byteLength property in a Buffer is slow to access. It appears that when we access byteLength, the V8 engine processes it using a hash lookup. so we store it in closure.
Sometimes, the data we want to serialize does not have a confirmed type; instead, it could be one of several confirmed types. If we use an object to handle this situation, the size of the resulting binary will be too large, as it will contain much unused information.
usage:
```JavaScript
const oneOfThree = Type.oneof({
option1: Type.string(),
option2: Type.object("foo", {
a: Type.int32()
}),
option3: …
```
=> feat(JavaScript): Support oneof

java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java, java/fury-core/src/test/java/org/apache/fury/codegen/CodegenContextTest.java, java/fury-core/src/test/java/org/apache/fury/codegen/javalangnameconflict/Object.java
Hi. This is my initial approach to provide a PR for fixing #1363 
I'm not sure what you mean
> Maybe we should move it to CodeGenerator
as the CodeGenerator is not available in `CodegenContext`. So for the first approach I use the same way to determine the classloader as in the sample.
As we only have 'java.lang' classes here - wouldn't the classloader of java.lang.X  always be null?
=> fix(java): CodeGen: Name conflicts when omitting java.lang prefix #1363

rust/fury/src/buffer.rs, rust/fury/src/deserializer.rs
In the stable version of Rust, the `from_raw_parts_mut` API does not check for memory alignment, but in the 1.78.0-nightly version, alignment checking has been added to the preconditions.  To ensure memory safety, we have replaced direct memory writes with the `LittleEndian::write_xx` methods from the appropriate library. While this may introduce additional overhead for memory checks, robustness is the priority before releasing the software.
=> fix(Rust): Fix memory errors caused by casting

java/fury-core/src/main/java/org/apache/fury/serializer/JdkProxySerializer.java, java/fury-core/src/main/java/org/apache/fury/util/Platform.java, java/fury-core/src/main/java/org/apache/fury/util/ReflectionUtils.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/serializer/JdkProxySerializerTest.java
This is the fix for the issue #1364 including a test case ;)
=> fix(java): References within InvocationHandler, Issue #1364

java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java
As found with previous context class-loaders add Fury class-loader as a fallback instance.
=> fix(java): add potential missing bean class-loader

docs/guide/xlang_object_graph_guide.md, rust/fury/src/serializer.rs, rust/tests/tests/test_complex_struct.rs
Remove `fury-derive` as `fury::Fury` is enough to do the job.  Closes #1384
=> chore(Rust): remove fury-derive

java/fury-core/src/main/java/org/apache/fury/Fury.java
Deserialize from `InputStream` throws when the size cannot be read in one read. This fixes the issue by reading in a loop like it does for the serialized data.
Closes #1383
=> fix(java): Allow partial read of serialized size from `InputStream`

java/fury-core/src/main/java/org/apache/fury/Fury.java
There has been cases where Fury use too much memory:
This is caused by Fury held buffer. Fury holds a MemoryBuffer and write to it when users doesn't provide its own buffer. This held buffer can save memory copy since we don't have to grow buffer every time.  But Fury never clear this buffer. If a big object tree is passed, the held buffer will take much memory even later object tree is small. 
This PR fix it by reset buffer when it's lager than 128Kb.
=> feat(java): avoid big object graph cause buffer take up too much memory

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/test/java/org/apache/fury/FuryTest.java
fix big buffer trunc introduced in #1397, which reset buffer before copying data from it
=> fix(java): fix big buffer trunc

.github/workflows/ci.yml
- `macos-12`: x86
- `macos-14`: arm64
Refer to https://github.com/actions/runner-images for more details.
=> ci: Add arm64 macos to CI workflow

java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
1. `registeredClassIdCounter` is incremented every time `register(Class<?> cls, int classId)` is successfully called, so it can be used directly in `register(Class<?> cls)` without recalculation.
2. Delete `registeredId2Classes` and use `registeredId2ClassInfo` to achieve the corresponding function.
=> refactor(java): Optimize Class ID allocation.

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
use `Platform.BYTE_ARRAY_OFFSET` replace `MemoryBuffer.BYTE_ARRAY_BASE_OFFSET`.
=> chore(java): use `Platform.BYTE_ARRAY_OFFSET` replace `MemoryBuffer.BYTE_ARRAY_BASE_OFFSET`

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/collection/ObjectArray.java, java/fury-core/src/main/java/org/apache/fury/exception/DeserializationException.java, java/fury-core/src/main/java/org/apache/fury/resolver/MapRefResolver.java, java/fury-core/src/test/java/org/apache/fury/FuryTest.java
This PR carry read objects when deserialization fail for better trouble shooting.
Closes #1419
=> feat(java): carry read objects when deserialization fail for better trouble shooting

java/fury-core/pom.xml, java/fury-core/src/main/java/org/apache/fury/util/ClassLoaderUtils.java, java/fury-core/src/main/java/org/apache/fury/util/unsafe/DefineClass.java, java/fury-core/src/main/java/org/apache/fury/util/unsafe/_JDKAccess.java, java/fury-core/src/main/java/org/apache/fury/util/unsafe/_Lookup.java, java/fury-core/src/test/java/org/apache/fury/util/ClassLoaderUtilsTest.java, java/fury-core/src/test/java/org/apache/fury/util/unsafe/DefineClassTest.java, java/pom.xml
This PR implements `defineClass` insteadof using javaassist to reduce the dependency
=> feat(java): implement define_class insteadof using javaassist

java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
skip print exception when `deserializeUnexistedClass` option enabled and class not exist
=> feat(java): skip print exception when class not exist

java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/test/java/org/apache/fury/resolver/ClassResolverTest.java
Remove `registerWithCheck` function and register function enables duplicate registration check by default. When Class is repeatedly registered, an `IllegalArgumentException` is thrown.
=> refactor(java): remove registerWithCheck function

.github/workflows/ci.yml, .github/workflows/release-java-snapshot.yaml, .github/workflows/release.yaml
avoid actions that use node16
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
also - only publish if running on main fork - not on user forks
=> fix: update CI actions

.asf.yaml, README.md, go/README.md, java/fury-core/pom.xml, java/fury-format/pom.xml, java/pom.xml, javascript/packages/fury/package.json, python/setup.py, rust/README.md
As a native English speaker, the existing text doesn't read properly for me.
Blazing is being used as an adverb so should become Blazingly.
https://en.wiktionary.org/wiki/blazingly
For instance, if you wanted to use `incredible` - you would say `incredibly fast`, not `incredible fast`.
=> fix: use blazingly instead of blazing

ci/run_ci.sh, java/fury-core/src/main/java/org/apache/fury/util/LoggerFactory.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-test-core/pom.xml, java/pom.xml
This PR closes #1404 by:
- Upgrade slf4j to 2.0.12
- Using print instead of slf4j for graalvm
=> fix(java): fix slf4j on graalvm

docs/guide/xlang_type_mapping.md, docs/protocols/README.md, docs/protocols/java_object_graph_spec.md, docs/protocols/xlang_object_graph.md, docs/protocols/xlang_object_graph_spec.md
This PR standardizes fury cross-language serialization specification. It comes with following changes:
- Remove type tag from the protocol since it introduce space and performance overhead to the implementation. The `type tag` version can be seen in https://github.com/apache/incubator-fury/blob/6ea2e0b83d5449d63ca62296ff0dfd67b96c5bc5/docs/protocols/xlang_object_graph_spec.md .
- Fury preserves `0~63` for internal types, but let users register type by id from `0`(added by 64 automatically） to setup type mapping between languages. 
- Streamline the type systems, only `bool/byte/i16/i32/i64/half-float/float/double/string/enum/list/set/map/Duration/Timestamp/decimal/binary/array/tensor/sparse/tensor/arrow/record/batch/arrow/table` are allowed.
- Formulized the binary format for above types. …
=> feat(spec): standardizing fury cross-language serialization specification

scala/build.sbt
ideally all files should have license headers
relates to #1441
=> fix: add license header to build.sbt

java/fury-core/src/main/java/org/apache/fury/AbstractThreadSafeFury.java, java/fury-core/src/main/java/org/apache/fury/BaseFury.java, java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/ThreadLocalFury.java, java/fury-core/src/main/java/org/apache/fury/pool/ThreadPoolFury.java
Extract public Fury method to the `BaseFury` interface and implement them in `ThreadPoolFury` and `ThreadLocalFury`, so end users can avoid using `execute()` and other utility methods.
Off topic: further steps might be changing `BaseFury` interface name to `Fury` while existing class renaming to something like `FuryImpl`. `FuryBuilder` should return the new `Fury` interface, so we will hide system methods like `xwriteRef` and others. WDYT?
=> feat(java): extract public Fury methods to BaseFury

java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/CompatibleCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/serializer/PrimitiveSerializers.java
This PR reduced code size of read long for jvm jit inline:
- Reduced readVarLong code size by separating little/big endian
- Reduced readLong code size by separating little/big endian
- Reduced unsafeGetLong code size by separating little/big endian and generate online
=> feat(java): reduce code size of read long to optimize jvm jit inline

CONTRIBUTING.md
When PR has an impact on Fury performance, it is recommended to use perf type and provide benchmark data in the PR description.
=> docs: Use perf type when pr has performance impact.

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
Reduce bytecode size from 431 to 413.
Through the calculation in advance to reduce memory
#1465 
pre
after
=> perf(java): Reduce unsafeWritePositiveVarLong bytecode size.

java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
generate list fori loop instead of iterator loop for list serialization
Before this PR:
```java
private void sameElementClassWrite(MemoryBuffer memoryBuffer2, int value3, int value4, java.util.Collection collection, boolean value5) {
boolean isDeclType = (value4 & 4) != 4;
Serializer serializer1;
if (isDeclType) {
serializer1 = serializer0;
} else {
serializer1 = imageClassInfoHolder.getSerializer();
}
java.util.Iterator iter = collection.iterator();
int i = 0;
while (iter.hasNext()) {
org.apache.fury.benchmark.data.Image elemValue = (org.apache.fury.benchmark.data.Image)iter.next();
if (value5) {
if ((elemValue == null)) {
memoryBuffer2.writeByte(((byte)-3));
} else {
memoryBuffer2.writeByte(((byte)0));
serializer1.write(memoryBuffer2, elemValue);
}
} else { …
```
=> perf(java): generate list fori loop instead of iterator loop for list serialization

java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
This PR reduce endian check code size in MemoryBuffer and fixed some internal API name.
This PR introduce a 10% performance improvement
Serialization:
```
Before:
Benchmark                              (bufferType)   (objectType)  (references)   Mode  Cnt        Score       Error  Units
UserTypeSerializeSuite.fury_serialize         array  MEDIA_CONTENT         false  thrpt   10  3363940.073 ± 86298.538  ops/s
Now
Benchmark                              (bufferType)   (objectType)  (references)   Mode  Cnt        Score       Error  Units
UserTypeSerializeSuite.fury_serialize         array  MEDIA_CONTENT         false  thrpt   10  3645145.088 ± 56496.783  ops/s
```
Deserialization:
```
Before:
Benchmark                                  (bufferType)   (objectType)  (references)   Mode  Cnt …
```
=> perf(java): refine endian check code size in buffer

java/fury-core/src/main/java/org/apache/fury/logging/LoggerFactory.java, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/resolver/MapRefResolver.java, java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/PrimitiveSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractCollectionSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/ChildContainerSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/FuryArrayAsListSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/GuavaCollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/ImmutableCollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializers.java, java/fury-core/src/main/java/org/apache/fury/type/ClassDef.java, java/fury-core/src/test/java/org/apache/fury/memory/MemoryBufferTest.java, scala/src/main/scala/org/apache/fury/serializer/scala/CollectionSerializer.scala, scala/src/main/scala/org/apache/fury/serializer/scala/MapSerializer.scala
This PR add fastpath for read/write small varint in range `[0,127]`.
This PR also fix wrong log level setting in #1492
With this PR:
Before this PR:
=> perf(java): fastpath for read/write small varint in range [0,127]

java/fury-core/src/main/java/org/apache/fury/meta/MetaString.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringDecoder.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java, java/fury-core/src/main/java/org/apache/fury/util/StringUtils.java, java/fury-core/src/test/java/org/apache/fury/meta/MetaStringTest.java
This PR implements meta string encoding described in [fury java serialization spec](https://fury.apache.org/docs/specification/fury_java_serialization_spec#meta-string) and [xlang serialization spec](https://fury.apache.org/docs/specification/fury_xlang_serialization_spec#meta-string)
We have `3/8` space saveing for most string:
```java
// utf8 use 30 bytes, we use only 19 bytes
assertEquals(encoder.encode("org.apache.fury.benchmark.data").getBytes().length, 19);
// utf8 use 12 bytes, we use only 9 bytes.
assertEquals(encoder.encode("MediaContent").getBytes().length, 9);
```
The integration with ClassResolver is left in another PR.
#1240 
#1413
=> feat(java): meta string encoding algorithm in java

go/fury/type.go, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/resolver/MetaStringResolver.java, java/fury-core/src/test/java/org/apache/fury/FuryTestBase.java, java/fury-core/src/test/java/org/apache/fury/memory/MemoryBufferTest.java, java/fury-core/src/test/java/org/apache/fury/resolver/ClassResolverTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/UnexistedClassSerializersTest.java, python/pyfury/_fury.py, python/pyfury/_serialization.pyx, python/pyfury/_serializer.py, python/pyfury/serializer.py, python/pyfury/tests/test_serializer.py
This PR concats meta string len with flags and use varint encoding to encode such info, which can reduce 2 bytes for every meta string at most times.
This PPR reduced serialized size a little: 415 bytes -> 407 bytes when class is not registered in java
```
Before this PR:
Fury | MEDIA_CONTENT | false | array | 415 |
With this PR:
Fury | MEDIA_CONTENT | false | array | 407 |
```
Closes #1518 
Closes #1519 
Closes #1520
Closes #1521
=> feat(java/python/golang): concat meta string len with flags

java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/resolver/MetaStringResolver.java, java/fury-core/src/test/java/org/apache/fury/resolver/ClassResolverTest.java
This PR concats write classname flag with package name, which can save one byte for unregistred classname writing
=> feat(java): concat write classname flag with package name

java/fury-core/src/main/java/org/apache/fury/BaseFury.java
This PR deprecates serializeJavaObjectAndClass/deserializeJavaObjectAndClass API.
This APi is vargue and kind of duplicate with `Fury#serialize`. 
It doesn't provide `BufferCallback` support too.
We should make our API minimal and does not bloat it
=> chore(java): deprecate  serializeJavaObjectAndClass/deserializeJavaObjectAndClass API

go/fury/type.go, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaString.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringDecoder.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassInfo.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/resolver/MetaStringBytes.java, java/fury-core/src/main/java/org/apache/fury/resolver/MetaStringResolver.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/StreamTest.java, java/fury-core/src/test/java/org/apache/fury/resolver/MetaStringResolverTest.java, python/pyfury/_fury.py, python/pyfury/_serialization.pyx
This PR supports meta string encoding for classname and package name in fury java serialization.
Before this PR a unregistered class serialization:
```
Fury | MEDIA_CONTENT | false | array | 405 |
```
With this PR:
```
Fury | MEDIA_CONTENT | false | array | 390 |
```
This PR also fix buffer streaming readSliInt64 bugs introduced in #1451
=> feat(java): support meta string encoding for classname and package name

java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
THis pr inline  isDeclType in codegen
before this pr:
```java
boolean isDeclType0 = (value14 & 4) != 4;
Serializer serializer2;
if (isDeclType0) {
serializer2 = serializer0;
} else {
serializer2 = classResolver.readClassInfo(memoryBuffer6, imageClassInfoHolder).getSerializer();
}
```
with this pr:
```
Serializer serializer2;
if ( (value14 & 4) != 4) {
serializer2 = serializer0;
} else {
serializer2 = classResolver.readClassInfo(memoryBuffer6, imageClassInfoHolder).getSerializer();
}
```
=> chore(java): inline isDeclType in codegen

README.md, docs/README.md, docs/guide/java_serialization_guide.md, docs/guide/xlang_serialization_guide.md
THis PR renames guide document name by rename `object graph` to serialization. This help reduce confusion.
=> chore(doc): rename guide document name

go/fury/fury.go, go/fury/fury_test.go, java/fury-core/src/main/java/org/apache/fury/Fury.java, python/pyfury/_fury.py, python/pyfury/_serialization.pyx
This PR implements the MagicNumer feature in [xlang_serialization_spec.md](https://github.com/apache/incubator-fury/blob/main/docs/specification/xlang_serialization_spec.md#fury-header).
=> feat(java/python/golang): Implement the magicNumber feature

java/fury-core/src/main/java/org/apache/fury/io/FuryInputStream.java
This PR fix fury input stream read slow.
Closes #1548 
- Before this PR: cost 18031 mills
- With this PR: cost 1441mills
```java
public static void main(String[] args) throws IOException {
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
ZstdOutputStream zstdOutputStream = new ZstdOutputStream(outputStream);
FURY_RELEASE.serializeJavaObject(zstdOutputStream, BeanA.createBeanA(20));
byte[] bytes = outputStream.toByteArray();
long start = System.currentTimeMillis();
for (int i = 0; i < 10000; i++) {
zstdFuryDeserialize_Snapshot(new ByteArrayInputStream(bytes), BeanA.class);
}
System.out.println(System.currentTimeMillis() - start);
start = System.currentTimeMillis();
for (int i = 0; i < 10000; i++) {
zstdFuryDeserialize_Snapshot(new ByteArrayInputStream(bytes), BeanA.class); …
```
=> perf(java): fix fury input stream read slow

ci/release.py
This PR  makes `incubating` comes after `version` in release artifacts. 
For example: from `apache-fury-incubating-0.5.0-src.tar.gz` to `apache-fury-0.5.0-incubating-src.tar.gz`
#1389
=> fix(release): make incubating after version in release artifacts

java/fury-core/src/main/java/org/apache/fury/util/Platform.java
This change defensively switches the order of literals in comparison expressions to ensure that no null pointer exceptions are unexpectedly thrown. Runtime exceptions especially can cause exceptional and unexpected code paths to be taken, and this can result in unexpected behavior. 
Both simple vulnerabilities (like information disclosure) and complex vulnerabilities (like business logic flaws) can take advantage of these unexpected code paths.
Our changes look something like this:
```diff
String fieldName = header.getFieldName();
String fieldValue = header.getFieldValue();
- if(fieldName.equals("requestId")) {
+ if("requestId".equals(fieldName)) {
logRequest(fieldValue);
}
```
<details>
<summary>More reading</summary>
* [http://cwe.mitre.org/data/definitions/476.html](http://cwe.mitre.org …
=> fix(java): Switch order of literals to prevent NullPointerException

ci/release.py
Benchmark code are excluded from source release, we should remove license mention in the final LICENSE file.
The NOTICE fof those files are empty, so no need to change NOTICE file
#1389
=> fix(license): remove benchmark license when build

docs/specification/java_serialization_spec.md, docs/specification/xlang_serialization_spec.md, java/fury-core/src/main/java/org/apache/fury/meta/MetaString.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringDecoder.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java, java/fury-core/src/main/java/org/apache/fury/resolver/MetaStringBytes.java, java/fury-core/src/main/java/org/apache/fury/resolver/MetaStringResolver.java, java/fury-core/src/test/java/org/apache/fury/meta/MetaStringTest.java
add strip flag in meta string encoding spec
#1540
=> feat(spec/java): add strip flag in meta string encoding spec

java/fury-core/src/main/java/org/apache/fury/meta/MetaStringDecoder.java
When `MetaStringDecoder` is decoding, it will read two bytes at a time from the `data` and then perform the operation. This PR determines whether to skip the byte value. If it does not skip the byte decoding, it will only read one byte from the data.
=> perf(java): Optimize MetaStringDecoder

java/fury-core/src/main/java/org/apache/fury/collection/ObjectArray.java, java/fury-core/src/test/java/org/apache/fury/collection/ObjectArrayTest.java
Without this change, if `ObjectArray.clearObjectArray()` is called with start > 0 and size < 128 (which is `COPY_THRESHOLD`), then an IllegalArgumentException is thrown. This happens because `Arrays.fill()` takes a from index and a to index, in contrast with `clearObjectArray()`, which takes a start index and a size. The exception looks like this:
```
Exception in thread "main" java.lang.IllegalArgumentException: fromIndex(11) > toIndex(5)
at java.base/java.util.Arrays.rangeCheck(Arrays.java:718)
at java.base/java.util.Arrays.fill(Arrays.java:3453)
```
This wasn't thrown in Fury code, because Fury itself never calls clearObjectArray() with any start value other than 0. The method is part of a public API, though, so user code can call it.
I added an extra check to ObjectArrayTest that …
=> fix(java): Prevent exception in ObjectArray.clearObjectArray()

java/benchmark/src/main/java/org/apache/fury/benchmark/UserTypeDeserializeSuite.java, java/benchmark/src/main/java/org/apache/fury/benchmark/UserTypeSerializeSuite.java, java/benchmark/src/main/java/org/apache/fury/benchmark/ZeroCopySuite.java, java/benchmark/src/main/java/org/apache/fury/benchmark/state/FlatBuffersState.java, java/benchmark/src/main/java/org/apache/fury/benchmark/state/FstState.java, java/benchmark/src/main/java/org/apache/fury/benchmark/state/JsonbState.java, java/fury-core/src/main/java/org/apache/fury/io/FuryReadableChannel.java, java/fury-core/src/main/java/org/apache/fury/memory/ByteBufferUtil.java, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/memory/Platform.java, java/fury-core/src/test/java/org/apache/fury/StreamTest.java, java/fury-core/src/test/java/org/apache/fury/memory/MemoryBufferTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/BufferSerializersTest.java, java/fury-core/src/test/java/org/apache/fury/util/PlatformTest.java
This PR add a bytebuffer util and fix bytebuffer no such method error
Closes #1577 
#1579
=> fix(java): fix bytebuffer no such method error

java/fury-core/src/main/java/org/apache/fury/reflect/TypeParameter.java, java/fury-core/src/main/java/org/apache/fury/reflect/TypeRef.java, java/fury-core/src/main/java/org/apache/fury/reflect/Types.java
add guava derive comments
#1553
=> fix(java): add guava derive comments

java/fury-core/src/main/java/org/apache/fury/io/FuryInputStream.java, java/fury-core/src/main/java/org/apache/fury/io/FuryReadableChannel.java, java/fury-core/src/main/java/org/apache/fury/io/FuryStreamReader.java, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
grow buffer to interger.max
#1576
=> fix(java): grow buffer to interger.max

integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/CompatibleExample.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/CompatibleThreadSafeExample.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/Example.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/Main.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/ThreadSafeExample.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/record/CompatibleRecordExample.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/record/RecordExample2.java, integration_tests/graalvm_tests/src/main/resources/META-INF/native-image/org.apache.fury/graalvm_tests/native-image.properties, java/fury-core/src/main/java/org/apache/fury/builder/AccessorHelper.java, java/fury-core/src/main/java/org/apache/fury/reflect/FieldAccessor.java, java/fury-core/src/main/java/org/apache/fury/util/function/Functions.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/reflect/FieldAccessorTest.java
This PR supports compatible mode for graalvm by using `MethodHandle` to geenrate accessor at build time instead of using `Unsafe`
Closes #1555
=> feat(java): support compatible mode for graalvm

.gitignore, java/fury-core/src/main/java/org/apache/fury/meta/MetaString.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringDecoder.java, java/fury-core/src/test/java/org/apache/fury/meta/MetaStringTest.java
Fix two bugs:
+ fix method `MetaString.stripLastChar()` logical error
+ add empty encoded bytes check in `MetaStringDecoder.decode()`
- #1565 
- [No] Does this PR introduce any public API change?
- [No] Does this PR introduce any binary protocol compatibility change?
=> fix(java): meta string strip last char && check empty encoded string

docs/specification/java_serialization_spec.md, docs/specification/xlang_serialization_spec.md
This PR removes list/map header from type meta spec. 
Such header may be computed ahead sometimes. But it may need to compute based the data at runtime. If we write header into type meta, we may still need to compute and write header when serialization. This will introduce extra space cost.
Instead, we can write all such header at runtime, and when creating/generating serializer, we can compute part of such header ahead, and let remaing parts of header computed at serialization.
When deserialization, the deserializer can generate different deserializer based on read header, which will be more efficient.
#1413
=> feat(spec): remove list/map header from type meta spec

java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
skip register unexisted skip class if `deserializeUnexistedClass` not enabled
#1600
=> fix(java): skip register unexisted skip class

java/fury-core/src/main/java/org/apache/fury/resolver/FieldResolver.java, java/fury-core/src/main/java/org/apache/fury/serializer/CompatibleSerializer.java
Some collectionSerializer may overwrite write/read method, then clear element serializer may not got invoked.
This PR clears serializer for collection/map to avoid container use wrong serializer for nested elements.
#1558
https://github.com/apache/incubator-fury/issues/1455, https://github.com/apache/incubator-fury/issues/1325 and https://github.com/apache/incubator-fury/issues/1176.
=> fix(java): clear serializer for collection/map

docs/specification/xlang_serialization_spec.md
Update type meta field info spec:
```
- field info:
- header(8
bits): `3 bits size + 2 bits field name encoding + polymorphism flag + nullability flag + ref tracking flag`.
Users can use annotation to provide those info.
- 2 bits field name encoding:
- encoding: `UTF8/ALL_TO_LOWER_SPECIAL/LOWER_UPPER_DIGIT_SPECIAL/TAG_ID`
- If tag id is used, i.e. field name is written by an unsigned varint tag id. 2 bits encoding will be `11`.
- size of field name:
- The `3 bits size: 0~7`  will be used to indicate length `1~7`, the value `7` indicates to read more bytes,
the encoding will encode `size - 7` as a varint next.
- If encoding is `TAG_ID`, then num_bytes of field name will be used to store tag id.
- ref tracking: when set to 1, ref tracking will be enabled for this field.
- nullability: when …
```
=> feat(sepc): update type meta field info spec

java/benchmark/src/test/java/org/apache/fury/benchmark/state/JsonTest.java, java/fury-core/src/main/java/org/apache/fury/reflect/TypeRef.java, java/fury-core/src/test/java/org/apache/fury/reflect/TypeRefTest.java
fix TypeRef getSubType
Closes #1604
=> fix(java): fix TypeRef getSubType

java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/serializer/collection/CollectionSerializersTest.java
Support CopyOnWriteArrayListSerializer
=> feat(java): Support CopyOnWriteArrayListSerializer

docs/specification/xlang_serialization_spec.md, go/fury/fury.go, java/fury-core/src/main/java/org/apache/fury/config/Language.java, javascript/packages/fury/lib/fury.ts, javascript/packages/fury/lib/type.ts, python/pyfury/_fury.py, rust/fury/src/deserializer.rs, rust/fury/src/serializer.rs
Add serialization language field for Fury Header in xlang_spec.
https://github.com/apache/incubator-fury/issues/1607
=> chore: Fury header add language field

LICENSE, java/fury-core/src/main/java/org/apache/fury/builder/JITContext.java, java/fury-core/src/main/java/org/apache/fury/codegen/CodeGenerator.java, java/fury-core/src/main/java/org/apache/fury/util/concurrency/DirectExecutorService.java, java/fury-core/src/main/java/org/apache/fury/util/concurrency/FuryJitCompilerThreadFactory.java, java/fury-core/src/main/resources/META-INF/LICENSE, licenserc.toml
Removes Guava's Concurrency utils usages
#1113
=> refactor(java): Remove Guava's Concurrency utils usages

java/fury-core/src/main/java/org/apache/fury/resolver/FieldResolver.java, java/fury-core/src/main/java/org/apache/fury/serializer/CompatibleSerializer.java, java/fury-testsuite/pom.xml, java/fury-testsuite/src/test/java/org/apache/fury/TestBase.java, java/fury-testsuite/src/test/java/org/apache/fury/test/Object2ObjectOpenHashMapTest.java
fix fastutil Object2ObjectOpenHashMap serialization
Closes #1615
=> fix(java): fix fastutil Object2ObjectOpenHashMap serialization

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/io/BlockedStreamUtils.java, java/fury-core/src/main/java/org/apache/fury/util/ExceptionUtils.java, java/fury-core/src/test/java/org/apache/fury/CyclicTest.java, java/fury-core/src/test/java/org/apache/fury/io/BlockedStreamUtilsTest.java
Native stream is not feasible for every cases, this PR add blocked stream utils to adapt to streaming API.
This is s serialization helper as the fallback of streaming serialization/deserialization in FuryInputStream/FuryReadableChannel. 
FuryInputStream/FuryReadableChannel will buffer and read more data, which makes the original passed stream when constructing FuryInputStream not usable. If this is not possible, use this BlockedStreamUtils instead for streaming serialization and deserialization.
Note that this mode will disable streaming in essence. It's just a helper for make the usage in streaming interface more easily. The deserialization will read whole bytes before do the actual deserialization, which don't have any streaming behaviour under the hood.
#1451
=> feat(java): add blocked stream utils

go/fury/meta/meta_string_encoder.go, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java
This PR introduces a validation method to ensure that all input strings to the `MetaString` encoder are ASCII.
=> feat(go/java): Add ASCII check before meta string encoding

java/fury-core/src/main/java/org/apache/fury/serializer/collection/GuavaCollectionSerializers.java
before guava 19.0, of() return EmptyImmutableSet/EmptyImmutableBiMap/EmptyImmutableSortedMap/EmptyImmutableSortedSet. check class and register serializer for them.
=> feat(java): register old version guava collect

ci/format.sh, java/fury-core/src/main/java/org/apache/fury/config/Config.java, java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java, java/fury-core/src/main/java/org/apache/fury/serializer/EnumSerializer.java, java/fury-core/src/test/java/org/apache/fury/serializer/EnumSerializerTest.java
=> feat(java): support deserialization ignoreEnumDeserializeError

integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/Collection.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/CollectionExample.java, integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/Main.java, java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/serializer/collection/CollectionSerializersTest.java
we use `Sets.newConcurrentHashSet()`  to create set, with lastest guava version it use `ConcurrentHashMapKeySetView` and old version it use `Collections.newSetFromMap(map)`. 
remove `CopyOnWriteArrayListSerializer` from native-image.properties.  #1614 forget delete.
=> feat(java): add set serializer for concurrent set

java/fury-core/src/main/java/org/apache/fury/meta/ClassDefEncoder.java, java/fury-core/src/test/java/org/apache/fury/meta/ClassDefEncoderTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedCompatibleTest.java
when subclass without fields. `org.apache.fury.meta.ClassDefEncoder#getClassFields` will skip subclass so className will be superclass. however we should save class even fields is empty.
=> fix(java): subclass without fields will encode superclass

java/fury-core/src/main/java/org/apache/fury/util/StringUtils.java, java/fury-core/src/test/java/org/apache/fury/util/StringUtilsTest.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/RowEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/type/TypeInference.java
=> refactor(java): replace Guava's string utility methods with own implementation

java/fury-core/src/main/java/org/apache/fury/pool/FuryPooledObjectFactory.java, java/fury-core/src/main/java/org/apache/fury/pool/ThreadPoolFury.java, java/fury-core/src/test/java/org/apache/fury/ThreadSafeFuryTest.java
ThreadPoolFury#factoryCallback don't work when create new classLoaderFuryPooled.
=> fix(java): ThreadPoolFury#factoryCallback don't work when create new classLoaderFuryPooled

go/fury/meta/meta_string_encoder.go, go/fury/meta/meta_string_test.go, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java, java/fury-core/src/test/java/org/apache/fury/meta/MetaStringTest.java
This PR enhances the current ASCII check (before meta string encoding) I implemented in #1620 to return a UTF-8 encoded `MetaString` early if the input is non-ASCII. This improves efficiency and saves time on `computeEncoding` and `encode`. Unit tests are also added.
https://github.com/apache/incubator-fury/issues/1619
=> fix(go/java): Enhance ASCII check in meta string encoding

java/fury-core/src/main/java/org/apache/fury/config/Config.java, java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java, java/fury-core/src/main/java/org/apache/fury/serializer/EnumSerializer.java, java/fury-core/src/test/java/org/apache/fury/serializer/EnumSerializerTest.java
rename deserializeUnexistentEnumValueAsNull to deserializeNonexistentAsNull
=> chore(java): rename deserializeUnexistentEnumValueAsNull to deserializeNonexistentAsNull

java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/codegen/Expression.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/CollectionSerializersTest.java
This PR fix inlineable expression codegen and reduce class load cost in generated code.
With those changes, it fixed abstract collection elems same type serialization in #1640 
Closes #1640
=> fix(java): fix abstract collection elems same type serialization

java/fury-core/src/main/java/org/apache/fury/ThreadLocalFury.java, java/fury-core/src/main/java/org/apache/fury/pool/FuryPooledObjectFactory.java, java/fury-core/src/main/java/org/apache/fury/util/LoaderBinding.java, java/fury-core/src/test/java/org/apache/fury/ThreadSafeFuryTest.java
remove soft/weak ref values from thread safe fury
Closes #1632
=> feat(java): remove soft/weak ref values from thread safe fury

README.md, ci/release.py, docs/guide/scala_guide.md
This PR bumps release version to 0.5.1 since fury 0.5.1 has been released
=> chore: bump release version to 0.5.1

java/fury-core/src/main/java/org/apache/fury/resolver/MetaStringBytes.java
MetaStringBytes `hashcode & 0xff`, that is, header, represents the encoding
=> fix(java): Fix header offset issue in MetaStringBytes hashcode

ci/run_ci.py, ci/run_ci.sh
The current CI keeps failing.
[Error](https://github.com/apache/fury/actions/runs/9560557264/job/26352935638):
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
```
`numpy` was updated to 2.0.0 on Jun 16, 2024, which caused compatibility issues with CI, so `numpy<2.0.0` was set.
=> ci: fix ci error

java/fury-core/src/main/java/org/apache/fury/pool/ClassLoaderFuryPooled.java, java/fury-core/src/main/java/org/apache/fury/pool/FuryPooledObjectFactory.java, java/fury-core/src/main/java/org/apache/fury/pool/ThreadPoolFury.java
incase of pooledCache expired from cache, and fury will return to another pooledCache.
so we save pooledCache instead of get from cache.
=> fix(java): return fury to pooled which get from

java/benchmark/src/main/java/org/apache/fury/benchmark/CompressStringSuite.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java, java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java, java/fury-core/src/main/java/org/apache/fury/util/StringUtils.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/serializer/StringSerializerTest.java, java/fury-core/src/test/java/org/apache/fury/util/StringUtilsTest.java
This PR decouples and moves the `isLatin([])` method from `StringSerializer` class to `StringUtils`.
#1703
=> refactor(java): move latin language checker method from string serializer to string util

scala/build.sbt, scala/project/plugins.sbt
This PR uses https://github.com/mdedetrich/sbt-apache-sonatype to support publishing fury-scala jars to Apache's Nexus repository.
`sbt +publishSigned`
requires that you set NEXUS_USER and NEXUS_PW environment variables to provide your Apache username and password.
I have used my PR code to publish some snapshots to https://repository.apache.org/content/groups/snapshots/org/apache/fury/
=> build: publish jars for fury-scala

cpp/fury/util/string_util.cc, cpp/fury/util/string_util.h, cpp/fury/util/string_util_test.cc
Use SIMD acceleration to implement and optimize utf16 to utf8.
Adapter x86, arm and  risc-v
Add 8 tests verify the function
And efficiency has improved
done.
Closes #1546
=> feat(C++): The use of SIMD accelerated to implement and optimize utf16 utf8

java/fury-core/src/main/java/org/apache/fury/collection/ObjectArray.java, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/meta/ClassDef.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassInfo.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/resolver/MetaContext.java, java/fury-core/src/main/java/org/apache/fury/resolver/SerializationContext.java, java/fury-core/src/test/java/org/apache/fury/resolver/MetaContextTest.java
This PR optimizes scoped meta share mode writing perf by about 30%:
- Replace ArrayList by ObjectArray, which can save `clear` cost
- Speed up copy performance when writing classdefs 
#1733
=> perf(java): optimize scoped meta share mode perf

java/benchmark/analyze.py, java/benchmark/src/main/java/org/apache/fury/benchmark/StructBenchmark.java, java/benchmark/src/main/proto/bench.proto, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
add struct benchmark with pb:
Perf:
```
Benchmark                       Mode  Cnt      Score      Error  Units
fury_deserialize                thrpt   30  49667.900 ± 3004.061  ops/s
fury_kv_compatible_deserialize  thrpt   30  33014.595 ± 3716.199  ops/s
fury_kv_compatible_serialize    thrpt   30  23915.260 ± 3968.119  ops/s
fury_serialize                  thrpt   30  63146.826 ± 2930.505  ops/s
protobuf_deserialize            thrpt   30  14156.610 ±  685.272  ops/s
protobuf_serialize              thrpt   30  10060.293 ±  706.064  ops/s
```
Lib | Size
-- | --
fury | 8077
furystrict | 8009
furykv | 48028
protobuf | 18000
<br class="Apple-interchange-newline">
=> perf(java): add struct benchmark with pb

java/benchmark/src/main/java/org/apache/fury/benchmark/CopyBenchmark.java, java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/serializer/AbstractObjectSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/MetaSharedSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/NonexistentClassSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/ObjectSerializer.java
optimize pojo copy performance by 1~4X and add copy benchmark
Before:
```java
Benchmark                (bufferType)   (objectType)  (references)   Mode  Cnt        Score         Error  Units
CopyBenchmark.fury_copy         array  MEDIA_CONTENT         false  thrpt    3  1294614.644 ± 2103796.392  ops/s
CopyBenchmark.fury_copy         array         SAMPLE         false  thrpt    3  1909071.799 ± 2343118.356  ops/s
CopyBenchmark.fury_copy         array         STRUCT         false  thrpt    3  1220680.635 ± 1019806.837  ops/s
CopyBenchmark.fury_copy         array        STRUCT2         false  thrpt    3   584429.541 ±  111229.502  ops/s
CopyBenchmark.kryo_copy         array  MEDIA_CONTENT         false  thrpt    3  1008490.635 ±  309047.316  ops/s
CopyBenchmark.kryo_copy         array …
```
=> perf(java): optimize pojo copy performance

rust/fury/Cargo.toml, rust/fury/benches/simd_bench.rs, rust/fury/src/meta/meta_string.rs, rust/fury/src/meta/mod.rs, rust/fury/src/meta/string_util.rs
Using SIMD technology to speed up string detection
In fury/rust, run
```bash
cargo bench
```
result：
```bash
SIMD sse short          time:   [992.07 ps 993.91 ps 995.81 ps]                            
change: [-1.1907% -0.7021% -0.2276%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
2 (2.00%) high mild
3 (3.00%) high severe
SIMD sse long           time:   [368.88 ns 369.70 ns 370.59 ns]                          
change: [-1.1407% -0.4415% +0.1537%] (p = 0.20 > 0.05)
No change in performance detected.
Found 11 outliers among 100 measurements (11.00%)
9 (9.00%) high mild
2 (2.00%) high severe
SIMD avx short          time:   [4.4313 ns 4.4425 ns 4.4566 ns]                            
change: [-0.4239% -0.0440% +0.3277%] (p = 0.82 > 0.05)
No …
```
=> feat(RUST): String detection is performed using SIMD techniques

java/fury-core/src/main/java/org/apache/fury/annotation/Expose.java, java/fury-core/src/main/java/org/apache/fury/annotation/Exposed.java, java/fury-core/src/main/java/org/apache/fury/type/Descriptor.java, java/fury-core/src/test/java/org/apache/fury/FuryTest.java
Add `Expose` annotation to support "only de/serialize annotated fields"
#1735 
N/A
=> feat(java): Add 'Expose' annotation to support "only de/serialize annotated fields"

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/test/java/org/apache/fury/StreamTest.java
fix streaming classdef read
Closes #1757
=> fix(java): fix streaming classdef read

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/test/java/org/apache/fury/StreamTest.java
fix big buffer streaming MetaShared read by using relative offset
Closes #1759
=> fix(java): fix big buffer streaming MetaShared read offset

java/fury-core/src/main/java/org/apache/fury/logging/FuryLogger.java, java/fury-core/src/test/java/org/apache/fury/logging/Slf4jLoggerTest.java
=> fix(java): fix fury logger npe

java/benchmark/src/main/java/org/apache/fury/benchmark/CopyBenchmark.java, java/benchmark/src/main/java/org/apache/fury/benchmark/data/Data.java, java/benchmark/src/main/java/org/apache/fury/benchmark/state/KryoState.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java
optimize map copy perf and add benchmark
Closes #1744 
```
Benchmark                           (bufferType)  (references)   Mode  Cnt        Score         Error  Units
CopyBenchmark.fury_copy_int_map            array         false  thrpt    3  1779502.276 ± 2305262.034  ops/s
CopyBenchmark.fury_copy_string_map         array         false  thrpt    3  1845474.980 ± 2072340.777  ops/s
CopyBenchmark.kryo_copy_int_map            array         false  thrpt    3   625471.456 ±  289827.215  ops/s
CopyBenchmark.kryo_copy_string_map         array         false  thrpt    3   649970.300 ±  404700.716  ops/s
Benchmark                           (bufferType)  (references)   Mode  Cnt        Score         Error  Units
CopyBenchmark.fury_copy_int_map            array         false  thrpt    3 …
```
=> perf(java): optimize map copy perf

java/fury-core/src/main/java/org/apache/fury/serializer/StructSerializer.java
Fix memory leak in `StructSerializer.xread()` caused by re-pushing instead of popping `GenericType`.
None, probably.
N/A
=> fix(java): Fix memory leak in `StructSerializer.xread()` caused by re-pushing instead of popping `GenericType`.

java/benchmark/src/main/java/org/apache/fury/benchmark/CopyBenchmark.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializer.java
optimize list copy perf
Closes #1743
```
Benchmark                     (bufferType)  (references)   Mode  Cnt        Score         Error  Units
CopyBenchmark.fury_copy_list         array         false  thrpt    3  3942934.726 ± 2361062.022  ops/s
CopyBenchmark.kryo_copy_list         array         false  thrpt    3   910135.076 ±  914811.092  ops/s
Benchmark                     (bufferType)  (references)   Mode  Cnt        Score         Error  Units
CopyBenchmark.fury_copy_list         array         false  thrpt    3  5797916.088 ± 3054882.337  ops/s
CopyBenchmark.kryo_copy_list         array         false  thrpt    3   942358.419 ±  942454.986  ops/s
```
=> perf(java): optimize list copy perf

docs/guide/java_serialization_guide.md
add fury deep copy documentation
Closes #1772
=> chore(java): add fury deep copy documentation

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/collection/ObjectArray.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/test/java/org/apache/fury/FuryTest.java
When obj is null, if shareMeta is enabled, no need to write meta classdef
=> chore(java): Disallow writing meta classdef when obj is null

rust/fury-core/src/buffer.rs, rust/fury-core/src/error.rs, rust/fury-core/src/fury.rs, rust/fury-core/src/meta/type_meta.rs, rust/fury-core/src/resolver/class_resolver.rs, rust/fury-core/src/resolver/context.rs, rust/fury-core/src/resolver/meta_resolver.rs, rust/fury-core/src/resolver/mod.rs, rust/fury-core/src/serializer/any.rs, rust/fury-core/src/serializer/bool.rs, rust/fury-core/src/serializer/datetime.rs, rust/fury-core/src/serializer/list.rs, rust/fury-core/src/serializer/map.rs, rust/fury-core/src/serializer/mod.rs, rust/fury-core/src/serializer/number.rs, rust/fury-core/src/serializer/option.rs, rust/fury-core/src/serializer/primitive_list.rs, rust/fury-core/src/serializer/set.rs, rust/fury-core/src/serializer/string.rs, rust/fury-core/src/types.rs, rust/fury-derive/src/lib.rs, rust/fury-derive/src/object/misc.rs, rust/fury-derive/src/object/read.rs, rust/fury-derive/src/object/serializer.rs, rust/fury-derive/src/object/write.rs, rust/tests/tests/test_complex_struct.rs
1. Support polymorphism
Add a class resolver which is used for managing the relationship between type_id and serializer. The serializer is generated by a generic function which will be called by dynamic dispatch. When a struct uses `Box<dyn Any>` as a field type and does not specify the specific type, we will use the class resolver to load the handler by type_id. In this situation, there is some performance overhead due to hash lookup, but it greatly improves convenience.
Use as follow:
```Rust
#[test]
fn any() {
#[derive(Fury, Debug)]
struct Animal {
f3: String,
}
#[derive(Fury, Debug)]
struct Person {
f1: Box<dyn Any>,
}
let person = Person {
f1: Box::new(Animal {
f3: String::from("hello"),
}),
};
let mut fury = Fury::default();
fury.register::<Animal>(999); …
```
=> feat(Rust): Support polymorphism

java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/ImmutableCollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializers.java
support jdk9+ java.util.ImmutableCollections copy
https://github.com/apache/fury/issues/1679
=> feat(java): support jdk9+ java.util.ImmutableCollections copy

rust/fury-core/src/resolver/meta_resolver.rs, rust/fury-core/src/serializer/list.rs, rust/fury-core/src/serializer/map.rs, rust/fury-core/src/serializer/mod.rs, rust/fury-core/src/serializer/set.rs
Use iterator + collect to avoid re-allocate vec/set/map.
=> fix(rust): use iter to avoid reallocate

rust/fury-core/Cargo.toml, rust/fury-core/src/error.rs, rust/fury-core/src/meta/meta_string.rs, rust/fury-core/src/meta/type_meta.rs, rust/fury-core/src/resolver/context.rs, rust/fury-core/src/row/row.rs, rust/fury-core/src/serializer/any.rs, rust/fury-core/src/serializer/datetime.rs, rust/fury-core/src/serializer/mod.rs, rust/fury-core/src/serializer/option.rs, rust/fury-core/src/types.rs, rust/fury-derive/src/object/read.rs, rust/tests/Cargo.toml
Make error easy to use.
In most case, users don't care about error details, so too many fields in enum is hard to write, and hard to use. 
So I refactor it to include an `Other` field to be used as a general Error, most error can be mapped to it directly.
`Ref` is a special case, so I leave it as it's now.
=> refactor(rust): simplify error handle

java/fury-core/src/main/java/org/apache/fury/exception/DeserializationException.java
Fix failure on `DeserializationException#getMessage`
```
java.lang.StringIndexOutOfBoundsException: Range [311, 2) out of bounds for length 313
at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
at java.base/java.lang.AbstractStringBuilder.delete(Unknown Source)
at java.base/java.lang.StringBuilder.delete(Unknown Source)
at …
```
=> fix(java): DeserializationException#getMessage call

java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractCollectionSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java, java/fury-core/src/test/java/org/apache/fury/FuryTestBase.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/CollectionSerializersTest.java
fix collection view serialization
Closes #1831 
Closes #1832
=> fix(java): fix collection view serialization

docs/specification/java_serialization_spec.md, java/fury-core/src/main/java/org/apache/fury/meta/ClassDefDecoder.java, java/fury-core/src/main/java/org/apache/fury/meta/ClassDefEncoder.java, java/fury-core/src/test/java/org/apache/fury/meta/ClassDefEncoderTest.java, java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedCompatibleTest.java
fix long type name meta string encoding
Closes #1835
=> fix(java): fix long type name meta string encoding

rust/fury-core/src/util.rs
=> fix(rust): replace `(value << 8) | (value >> 8)` with `value.rotate_right(8)`

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
Fixes the maximum size of Java arrays using Integer.MAX_VALUE when it should be Integer.MAX_VALUE - 8.
See this https://github.com/openjdk/jdk14u/blob/84917a040a81af2863fddc6eace3dda3e31bf4b5/src/java.base/share/classes/jdk/internal/util/ArraysSupport.java#L577 or https://www.baeldung.com/java-arrays-max-size
- #1842
No
=> fix(java): Fix for maximum size of java arrays

java/fury-core/src/main/java/org/apache/fury/io/FuryInputStream.java
Fixes the maximum size of Java arrays using Integer.MAX_VALUE when it should be Integer.MAX_VALUE - 8.
See this https://github.com/openjdk/jdk14u/blob/84917a040a81af2863fddc6eace3dda3e31bf4b5/src/java.base/share/classes/jdk/internal/util/ArraysSupport.java#L577 or https://www.baeldung.com/java-arrays-max-size
Same as https://github.com/apache/fury/pull/1843 but for the reader.
- #1842
No
Not needed
=> fix(java): Fix max Java array size for reader

java/fury-core/src/main/java/org/apache/fury/builder/AccessorHelper.java, java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/MetaSharedCodecBuilder.java
simplify generated codec name
before:
after:
=> chore(java): simplify generated codec name

java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, scala/src/main/java/org/apache/fury/serializer/scala/ScalaDispatcher.java, scala/src/main/java/org/apache/fury/serializer/scala/ScalaSerializers.java, scala/src/main/java/org/apache/fury/serializer/scala/ToFactorySerializers.java, scala/src/test/scala/org/apache/fury/serializer/scala/CollectionSerializerTest.scala, scala/src/test/scala/org/apache/fury/serializer/scala/CompatibleSingleObjectSerializerTest.scala, scala/src/test/scala/org/apache/fury/serializer/scala/MutableCollectionSerializerTest.scala, scala/src/test/scala/org/apache/fury/serializer/scala/ScalaTest.scala
- Optimize scala Iterable type serialization
- Reduce type name writing for msot scala collection and factory types
- Add serializers for ToFactory type
=> feat(scala): optimize scala class serialization

java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/SubListSerializers.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/serializer/collection/SubListSerializersTest.java
Since so many users serialize sublist, but we don't allow this type for serialization, this introduce some confustion. So I added  sublist serializers in this PR.
Closes https://github.com/apache/fury/issues/281
=> feat(java): implement sublist serializers

java/fury-core/src/main/java/org/apache/fury/serializer/collection/SubListSerializers.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/SubListSerializersTest.java
use SubListViewSerializer only when tracking ref
Closes #1198
#1856
=> feat(java): use SubListViewSerializer only when tracking ref

.github/workflows/sync.yml
The sync job is set up so it also runs on forks of the apache/fury repo. It can't pass on the forks because they don't have the secrets set up.
=> ci: only run sync job if the repo is apache/fury

.bazelrc, .github/workflows/ci.yml, bazel/arrow/BUILD.windows.bzl, bazel/arrow/pyarrow_configure.bzl, ci/run_ci.py, cpp/fury/row/row.cc
Make bazel happy on `Windows OS`.
1. Rewrite a little codes in `row.cc`, then it could be compiled by MSVC ([VLA is not supported](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/))
2. Add MSVC flag [`/Zc:preprocessor`](https://learn.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-170)  to enable C99/C11
3. Add MSVC flag [`/utf-8`](https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170) to set source and execution character sets to UTF-8.
4. Load arrow(arrow_python) interface libraries `*.lib` to the linker
5. Add a new CI env `windows-2022` to build fury cpp libraries
#798
=> feat(bazel): support building C++ libs on windows platform

kotlin/README.md, kotlin/src/main/java/org/apache/fury/serializer/kotlin/KotlinSerializers.java, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/KotlinToJavaClass.kt, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedSerializer.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/NullablePrimitiveSerializerTests.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/PrimitiveSerializerTest.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/UnsignedBoundarySerializerTests.kt
This PR adds unsigned primitive support to Kotlin Fury.
It also adds tests for the standard kotlin primitives(supported by fury Java), nullable primitive tests, boundary tests for unsigned serializers.
#683
Yes it adds Unsigned support for Kotlin. There's documentation new issue (should add something to document Kotlin!)
N/A
=> feat(kotlin): Add Unsigned Primitive Support

python/pyfury/util.py
This PR removes [pkgutil.find_loader()][] and replaces it with [importlib.util.find_spec()][]. `find_loader` was deprecated in Python 3.12 and will be removed in 3.14. `find_spec` has been present since Python 3.4.
Both functions return `None` if the module loader cannot be found. For its use in this project, this is sufficient and no translation of the return value is needed.
[pkgutil.find_loader()]: https://docs.python.org/3/library/pkgutil.html#pkgutil.get_loader
[importlib.util.find_spec()]: https://docs.python.org/3/library/importlib.html#importlib.util.find_spec
=> chore(py314): Replace deprecated pkgutil.find_loader

kotlin/README.md, kotlin/src/main/java/org/apache/fury/serializer/kotlin/KotlinSerializers.java, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedArraySerializers.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/ArraySerializerTest.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/StringsSerializerTest.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/UnsignedBoundarySerializerTests.kt
This PR adds tests for serializing/deserializing:
- Strings (same as Java)
- Primitive arrays in Kotlin (same as Java)
- Array<T> in kotlin (same as Java)
- Unsigned arrays in kotlin - `UByteArray`, `UIntArray`, `UShortArray`, `ULongArray`
Unsigned arrays in kotlin are currently marked experimental, and are subject to API changes (hence the annotations needed to suppress those warnings).
These types are implemented as a view over the signed arrays e.g. UByteArray is a view over ByteArray with contents reinterpreted as UByte, so serializers. The current implementation delegate to existing serializers for corresponding signed types.
The xlang type id is set to LIST for unsigned types.
#683
Yes. Unsigned primitives no longer need to be registered for `fury-kotlin`.
N/A
=> feat(kotlin): Add unsigned array support and tests for arrays and strings

java/fury-core/src/main/java/org/apache/fury/serializer/NonexistentClassSerializers.java, java/fury-core/src/test/java/org/apache/fury/serializer/NonexistentClassSerializersTest.java
Handle NonExistentEnum on mode serializeEnumByName by returning UNKNOWN. since there are no relevancy anymore by using enum ordinal.
=> fix(java): NonExistentEnum on mode serializeEnumByName

docs/guide/java_serialization_guide.md, docs/guide/xlang_serialization_guide.md
Fixes two small typos in the guide
=> docs(guide): Fix package typo

java/fury-core/src/main/java/org/apache/fury/ThreadLocalFury.java, java/fury-core/src/main/java/org/apache/fury/pool/FuryPooledObjectFactory.java, java/fury-core/src/test/java/org/apache/fury/classloader/ThreadSafeFuryClassLoaderTest.java
ThreadLocalFury and ThreadPoolFury prioritize using the user-specified ClassLoader
[1884](https://github.com/apache/fury/issues/1884)  [1878](https://github.com/apache/fury/issues/1878)
=> fix(java): ThreadLocalFury and ThreadPoolFury prioritize using the user classloader

kotlin/README.md, kotlin/pom.xml, kotlin/src/main/java/org/apache/fury/serializer/kotlin/KotlinSerializers.java, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/CollectionBuilder.kt, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/CollectionSerializer.kt, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/DurationSerializer.kt, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/KotlinToJavaClass.kt, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedArraySerializers.kt, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedSerializer.kt, kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UuidSerializer.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/ArraySerializerTest.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/BuiltinClassSerializerTests.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/CollectionSerializerTest.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/NullablePrimitiveSerializerTests.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/PrimitiveSerializerTest.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/StringsSerializerTest.kt, kotlin/src/test/kotlin/org/apache/fury/serializer/kotlin/UnsignedBoundarySerializerTests.kt
This PR modifies the build to:
1) add ktfmt - Since the fury java uses GOOGLE style, the fury kotlin will also use GOOGLE style. The version of ktfmt used is the highest compatible with the spotless maven plugin.
2) explicit api mode
3) parameterized kotlin version in pom.xml so it is easy to change in future
4) Update README.md with build, format and testing instructions.
#1896 
None.
N/A
=> build(kotlin): Add spotless ktfmt and enable explicit api mode for library code.

java/fury-core/src/main/java/org/apache/fury/reflect/ReflectionUtils.java, java/fury-core/src/main/java/org/apache/fury/serializer/AbstractObjectSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/ChildContainerSerializers.java
fix child container bug
https://github.com/apache/fury/issues/1855
=> fix(java): child container deep copy

java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java, java/fury-core/src/main/java/org/apache/fury/util/StringEncodingUtils.java, java/fury-core/src/main/java/org/apache/fury/util/StringUtils.java, java/fury-core/src/test/java/org/apache/fury/util/StringEncodingUtilsTest.java
Fix incorrect results of utf16 to utf8 conversion for latin1 but not ascii characters
=> fix(java): Fix incorrect results of utf16 to utf8 conversion for latin1 but not ascii characters

java/fury-core/src/main/java/org/apache/fury/Fury.java
previously there was this kind of error stacktrace:
```
Caused by: java.lang.IllegalArgumentException: false
at org.apache.fury.util.Preconditions.checkArgument(Preconditions.java:52)
at org.apache.fury.Fury.deserialize(Fury.java:765)
at org.apache.fury.Fury.deserialize(Fury.java:815)
at org.apache.fury.Fury.deserialize(Fury.java:808)
at org.apache.camel.component.fury.FuryDataFormat.unmarshal(FuryDataFormat.java:79)
```
=> feat(java): Improve error message on architecture not using little-endian format

python/pyfury/tests/test_serializer.py
Pytest treats classes starting with "Test" as test classes, avoid using such names for test data.
#518
=> fix(python): Eliminate PytestCollectionWarning when running pytest

java/fury-core/src/main/java/org/apache/fury/type/ScalaTypes.java, scala/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties
This PR supports scala native image build and fix quarkus graalvm build for java in https://github.com/quarkiverse/quarkus-fury/issues/7:
```
Error: Class initialization of org.apache.fury.type.ScalaTypes failed. Use the option 
'--initialize-at-run-time=org.apache.fury.type.ScalaTypes'
to explicitly request initialization of this class at run time.
com.oracle.svm.core.util.UserError$UserException: Class initialization of org.apache.fury.type.ScalaTypes failed. Use the option 
'--initialize-at-run-time=org.apache.fury.type.ScalaTypes'
to explicitly request initialization of this class at run time.
at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupp …
```
=> feat(scala): support scala native image build

java/fury-core/src/main/java/org/apache/fury/serializer/ReplaceResolveSerializer.java, java/fury-core/src/test/java/org/apache/fury/serializer/ReplaceResolveSerializerTest.java
Adjusting the deep copy of ReplaceResolveSerializer.
obj -> writeReplace -> copy -> readResolve -> newObj
https://github.com/apache/fury/issues/1849
=> feat(java): ReplaceResolveSerializer deep copy

.github/workflows/ci.yml
macos-12 is being deprecated https://github.com/actions/runner-images/issues/10721
Replacing it with macos-13 which also runs on x86-64
=> chore(ci): Migrate the ci from macOS 12 to macOS 13

integration_tests/cpython_benchmark/fury_benchmark.py, python/pyfury/_serialization.pyx
Pre-allocate memory for sequence containers based on the data size to avoid resizing and improve deserialization performance.
python format
```
python -m pyperf compare_to base.json opt.json
fury_large_tuple: Mean +- std dev: [base] 104 ms +- 2 ms -> [opt] 92.7 ms +- 5.5 ms: 1.13x faster
fury_large_list: Mean +- std dev: [base] 98.5 ms +- 3.7 ms -> [opt] 92.8 ms +- 5.3 ms: 1.06x faster
Benchmark hidden because not significant (2): fury_tuple, fury_list
```
xlang format
```
python -m pyperf compare_to base_xlang.json opt_xlang.json
fury_tuple: Mean +- std dev: [base_xlang] 262 us +- 6 us -> [opt_xlang] 259 us +- 5 us: 1.01x faster
fury_large_tuple: Mean +- std dev: [base_xlang] 104 ms +- 4 ms -> [opt_xlang] 90.0 ms +- 4.6 ms: 1.16x faster
fury_large_list: Mean +- std dev: [base_xlang] 97.6 …
```
=> perf(python): Improve tuple and list serializer performance

README.md, docs/guide/scala_guide.md, integration_tests/graalvm_tests/pom.xml, integration_tests/jdk_compatibility_tests/pom.xml, integration_tests/jpms_tests/pom.xml, integration_tests/latest_jdk_tests/pom.xml, java/benchmark/pom.xml, java/fury-core/pom.xml, java/fury-format/pom.xml, java/fury-test-core/pom.xml, java/fury-testsuite/pom.xml, java/pom.xml, javascript/packages/fury/package.json, javascript/packages/hps/package.json, kotlin/README.md, kotlin/pom.xml, python/pyfury/__init__.py, rust/Cargo.toml, scala/build.sbt
=> chore: bump release version to 0.9.0

python/pyfury/_serialization.pyx
Implement a new format for collection serialization in pyfury.
```
fury_tuple: Mean +- std dev: [base] 259 us +- 6 us -> [collection] 256 us +- 5 us: 1.01x faster
fury_large_tuple: Mean +- std dev: [base] 92.7 ms +- 5.5 ms -> [collection] 63.7 ms +- 4.8 ms: 1.46x faster
fury_list: Mean +- std dev: [base] 277 us +- 6 us -> [collection] 267 us +- 3 us: 1.04x faster
fury_large_list: Mean +- std dev: [base] 92.8 ms +- 5.3 ms -> [collection] 66.5 ms +- 3.0 ms: 1.40x faster
Geometric mean: 1.21x faster
```
=> feat(python): Implement collection serialization protocol

java/fury-format/pom.xml, java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryArray.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryRow.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/UnsafeTrait.java, java/fury-format/src/main/java/org/apache/fury/format/type/DataTypes.java
This PR removes the java specific `ExtField` class from the schema and moves the extData mechanism to the internal UnsafeTrait class. This is necessary because `ExtField` is only created internally from `inferSchema` method used by java, and we would potentially import or derive schemas from other sources (e.g XLANG, handwritten schema, arrow-native source) -- those schemas will be incompatible when we attempt to retrieve the cached schema. Removing schema-caching will fix the issue, but create allocations, so after some discussion, we decided to move the mechanism to the internal UnsafeTrait class.
This implementation makes changes internal API:
- Derived classes from `UnsafeTrait` need to initialize the `extData` cache and define the number of extData slots needed.
- The internal …
=> fix(java): Move schema caching to unsafe trait to avoid issues when using non-inferred schema.

java/fury-core/src/main/java/org/apache/fury/builder/CodecUtils.java, java/fury-core/src/main/java/org/apache/fury/util/ClassLoaderUtils.java, java/fury-core/src/test/java/org/apache/fury/codegen/CodeGeneratorTest.java
fix duplicate classloading in parent classloader.
Some classloader such as flink classloader can load class from children classloader. If fury is located in children classloader, but we are serializing a class in such parent class, the  parent class will load Fury class again, which caused two Fury clases loaded.
Closes #1947
=> fix(java): fix find constructor error in generated serializer class caused by duplicated class classloading for Fury

java/fury-core/src/main/java/org/apache/fury/io/MemoryBufferObjectInput.java, java/fury-core/src/main/java/org/apache/fury/io/MemoryBufferObjectOutput.java, java/fury-core/src/main/java/org/apache/fury/serializer/ObjectStreamSerializer.java, java/fury-core/src/test/java/org/apache/fury/io/MemoryBufferObjectInputTest.java
use varint for jdk compatible serializers to reduce serialized size
=> feat(java): use varint for jdk compatible serializers

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/config/Config.java, java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java, java/fury-core/src/test/java/org/apache/fury/FuryTest.java
This PR introduces a new configuration option `bufferSizeLimitBytes` that replaces the hard-coded default of 128kb.
#1950
The PR introduces a new configuration option `bufferSizeLimitBytes`.
This PR solves my problem, but I'm not sure if it is the right way to move forward. This is quite a low-level configuration option, but a potentially very important one. Every user whose average payload size is >=128kb, will need to increase this value for maximum performance. Maybe the default limit should be increased to something less conservative like 1MB, so fewer users will need to adjust this setting?
=> feat(java): configurable buffer size limit

docs/guide/java_serialization_guide.md, java/fury-core/src/test/java/org/apache/fury/FuryTest.java
add object mapping example and tests
#1973
=> docs(java): add object mapping example and tests

java/fury-core/src/test/java/org/apache/fury/codegen/ExpressionVisitorTest.java
`ExpressionVisitorTest#testTraverseExpression` relies on ordered traversal. However, the traversal depends on the order of `getDeclaredFields()` to be deterministic (see below). The Java specification explicitly marks `getDeclaredFields` as a function that can return field names in any order. In the wild, this is most likely to manifest on different architectures with different JVM versions.
https://github.com/apache/fury/blob/54b62fb6ab5d7e557131efe07c7402c885f6e7c4/java/fury-core/src/main/java/org/apache/fury/reflect/ReflectionUtils.java#L368-L381
Using [NonDex](https://github.com/TestingResearchIllinois/NonDex), we can replicate the flaky behavior with the following command:
```
mvn edu.illinois:nondex-maven-plugin:2.1.7:nondex -pl fury-core/ -Dcheckstyle.skip -Dmaven.javadoc.skip …
```
=> fix(java): Fix flakiness in ExpressionVisitorTest#testTraverseExpression

python/pyfury/meta/metastring.py, python/pyfury/tests/test_metastring.py
In the original MetaString, MetaStringEncoder used hard coding directly to solve the special char1/2 situation, but this was not the best choice. So it's passable, allowing MetaString to select the special char it passes.
Close #1983
=> feat(python): Hardcoding metastring into passable parameters

java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java, java/fury-core/src/test/java/org/apache/fury/serializer/StringSerializerTest.java
Fix the issue caused by not using readCompressedBytesString during deserialization when string compression is enabled.
fix issue [#1984 ](https://github.com/apache/fury/issues/1984)
=> fix(java): Fix the issue caused by not using readCompressedBytesString during deserialization when string compression is enabled.

cpp/fury/util/string_util.cc, cpp/fury/util/string_util.h, cpp/fury/util/string_util_test.cc
To support the utf8 utf16 and using simd to accelerate the optimization
``` c++
std::string utf16ToUtf8(const std::u16string &utf16, bool is_little_endian)
```
The logic of converting UTF-8 to UTF-16 isn't that complicated. but there are still lots of optimizations that I haven't come up with yet.
So, I'll first design a version that's a bit faster than the original one, and then think about how to make further optimizations.
Judging from the tests, the logic is correct:
``` text 
[----------] 9 tests from UTF8ToUTF16Test
[ RUN      ] UTF8ToUTF16Test.BasicConversion
[       OK ] UTF8ToUTF16Test.BasicConversion (0 ms)
[ RUN      ] UTF8ToUTF16Test.EmptyString
[       OK ] UTF8ToUTF16Test.EmptyString (0 ms)
[ RUN      ] UTF8ToUTF16Test.SurrogatePairs
[       OK ] …
```
=> feat(c++): Support the UTF-8 to UTF-16 with SIMD

cpp/fury/util/string_util.cc, cpp/fury/util/string_util.h, cpp/fury/util/string_util_test.cc, java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java, java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java, python/README.md, python/pyfury/_fury.py, python/pyfury/_serialization.pyx, python/pyfury/_util.pyx, python/pyfury/includes/libutil.pxd, python/pyfury/tests/test_serializer.py
Support support latin1/utf16 string encoding in python. For utf16, since python doesn't use surrogate pairs, this pr also added a vectorized  surrogate pairs check function.
Note:
- Python UCS-2 doesn't contains surrogate pairs, we must check utf16 first before contruct string from the binary. This is different from java/nodejs
Closes #1967
=> feat(python): support latin1/utf16 string encoding in python

cpp/fury/util/string_util.cc, cpp/fury/util/string_util.h, cpp/fury/util/string_util_test.cc
add simd accelerated c++ ascii/latin1 check funcion
=> feat(c++): add simd accelerated c++ ascii/latin1 check funcion

python/pyfury/serializer.py
This PR extract `__dict__` in object when serialize a dataclass without slots for faster attribute set/set by 16%
For following object:
```python
COMPLEX_OBJECT = ComplexObject1(
f1=ComplexObject2(f1=True, f2={-1: 2}),
f2="abc",
f3=["abc", "abc"],
f4={1: 2},
f5=2**7 - 1,
f6=2**15 - 1,
f7=2**31 - 1,
f8=2**63 - 1,
f9=1.0 / 2,
f10=1 / 3.0,
f12=[-1, 4],
)
```
This PR gives a 16% speed up
=> perf(python): get object __dict__ for faster field read/write

java/fury-core/src/main/java/org/apache/fury/config/Config.java, java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java, java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java, java/fury-core/src/test/java/org/apache/fury/FuryTestBase.java, java/fury-core/src/test/java/org/apache/fury/serializer/StringSerializerTest.java
Currently fury serialize utf8 string in java will write num bytes of utf16 first, so that the deserializaiton can save one copy. 
But C++ and golang does not need this information. This PR makes the 4 bytes utf16 size header optional for utf8 encoding, so theat the xlang serialiation can use the standard fury string serialization spec, and align to other languages.
For performance consideration, this PR introduce `writeNumUtf16BytesForUtf8Encoding` which can perserve current behaviour.
#1890
This PR will introduce an extra copy for deserialization since we can't know the size of utf16 in advance before decoding utf8 string.
=> feat(java): make 4 bytes utf16 size header optional for utf8 encoding

cpp/fury/util/logging.cc, cpp/fury/util/logging.h, cpp/fury/util/logging_test.cc, cpp/fury/util/string_util_test.cc
Thus the duplicated macro problem could be solved.
=> style(cpp): rename logging level with "FURY_" prefix

java/fury-format/src/main/java/org/apache/fury/format/encoder/ArrayEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/BaseBinaryEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/Encoder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/Encoders.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/MapEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryMap.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/writer/BinaryArrayWriter.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/writer/BinaryRowWriter.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/writer/BinaryWriter.java, java/fury-format/src/main/java/org/apache/fury/format/type/TypeInference.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/ArrayEncoderTest.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/CodecBuilderTest.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/MapEncoderTest.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/RowEncoderTest.java, java/fury-test-core/src/main/java/org/apache/fury/test/bean/SimpleFoo.java
support streaming encode/decode to/from buffer for row format
Closes #2019
=> feat(java): support streaming encode/decode to/from buffer for row format

docs/specification/java_serialization_spec.md, docs/specification/xlang_serialization_spec.md, java/benchmark/src/main/java/org/apache/fury/benchmark/MapSerializationSuite.java, java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapFlags.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java
This pr provides a new implementation for chunk based map serialization.
#1571
#1549
#1722 
Closes #925 
Deserialization are much faster than no-chunk version, serialization are faster if map size are bigger
Using the benchmark code in https://github.com/apache/fury/pull/1722#issuecomment-2342512316:
This PR has run faster, it gets up to **3x faster** :
```java
Benchmark                                  (size)  (tracking)  Mode  Cnt     Score       Error  Units
HnBenchmark.testGeneralChunkWriteWithNull      64        true  avgt    3   965.521 ±  1830.936  ns/op
HnBenchmark.testGeneralChunkWriteWithNull      64       false  avgt    3  1060.411 ±  3424.719  ns/op
HnBenchmark.testGeneralChunkWriteWithNull     128        true  avgt    3  2404.445 ±  8687.122  ns/op …
```
=> feat(java): new implementation and protocol refine for chunk based map serialization

java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java
fix some error
new implement of map chunk can not pass all of the unit test in the org.apache.fury.serializer.collection.MapSerializersTest
I found an error in line 298 of the AbstractMapSequencer file
none
none
=> fix(java): chunk map serialize an error

python/pyfury/_fury.py, python/pyfury/_registry.py, python/pyfury/_serialization.pyx, python/pyfury/_serializer.py, python/pyfury/resolver.py, python/pyfury/serializer.py, python/pyfury/tests/test_serializer.py
This pr unifies type system between python and xlang serialization in pyfury, so that we can remove duplicate code in pyfury, and lay the foundation for following features:
#1690
=> feat(python): unify type system between python and xlang serialization in pyfury

python/pyfury/_serialization.pyx, python/pyfury/_util.pxd, python/pyfury/_util.pyx, python/pyfury/tests/test_serializer.py
Implement chunk based map serialization for python using cython.
Note:
- non-cython debug mode version is not implemented in this PR. It's implemented in #2037 
- xlang serialization is not covered in this PR too. It will be supported easily after we unified type system in java for xlang and native java serialization
Closes #1935 
Here is the benchamrk script:
```python
def test_map_benchmark(data=None, dictsize=50, repeat=100000):
import timeit, pickle, pyfury
fury = pyfury.Fury(language=pyfury.Language.PYTHON, ref_tracking=False)
dict0 = data or {i: i * 2 for i in range(dictsize)}
bytes0 = fury.serialize(dict0)
bytes1 = pickle.dumps(dict0)
print(f"fury serialize map of size {len(dict0)}, payload size {len(bytes0)}")
print(f"pickle serialize map of size {len(dict0)}, payload size …
```
=> feat(python): chunk based map serialization for python

python/pyfury/_fury.py, python/pyfury/_serializer.py
Fix missing parameters and old API names
``` python
self.class_resolver.write_classinfo(buffer, classinfo)
self.class_resolver.write_typeinfo(buffer, classinfo)
```
```python
if cls is str:
buffer.write_int16()
buffer.write_int16(NOT_NULL_STRING_FLAG)
```
=> fix(python): Fix missing parameters and old API names

.github/workflows/ci.yml, .github/workflows/release.yaml, bazel/arrow/pyarrow_configure.bzl, bazel/fury_deps_setup.bzl, ci/deploy.sh, ci/run_ci.sh, python/setup.py
Adding support for Python 3.13 in CI. This can help us experiment with new features like no-GIL and JIT in the future.
=> feat(python): support 3.13

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
Fix the issue with `MemoryBuffer::readBytesAsInt64` when the system is not in LITTLE_ENDIAN mode.
- Fix #2068
=> fix(java): Fix error with `MemoryBuffer::readBytesAsInt64` when not in LITTLE_ENDIAN mode #2068

integration_tests/jdk_compatibility_tests/src/test/java/org/apache/fury/integration_tests/JDKCompatibilityTest.java, java/fury-core/src/main/java/org/apache/fury/serializer/collection/SubListSerializers.java
fix ImmutableCollections$SubList duplicate registration
java.util.ImmutableCollections$SubList has been registered twice, resulting in different numbers of classIdGenerator across different JDK versions, which ultimately leads to serialization failures when crossing JDK versions.
Closes #2070
=> fix(java): fix ImmutableCollections$SubList duplicate registration

java/benchmark/src/main/java/org/apache/fury/benchmark/ThreadPoolFurySuite.java, java/fury-core/src/main/java/org/apache/fury/pool/ClassLoaderFuryPooled.java
After testing, it was observed that ​ThreadPoolFury​ experiences prolonged blocking during cold starts under high-concurrency scenarios. Analysis revealed that improper usage of locks in ​ClassLoaderFuryPooled​ was the root cause. This PR refactors the implementation of ​ClassLoaderFuryPooled​ by significantly reducing the granularity of locks, thereby drastically minimizing blocking time during cold starts.
[](url)https://github.com/apache/fury/issues/2087
CPU:9950X 
Class:org.apache.fury.benchmark.ThreadPoolFurySuite.java
old:
Percentiles, ms/op:
p(0.0000) =      0.001 ms/op
p(50.0000) =      0.001 ms/op
p(90.0000) =   1587.388 ms/op
p(95.0000) =   1587.388 ms/op
p(99.0000) =   1587.388 ms/op
p(99.9000) =   1587.388 ms/op
p(99.9900) =   1587.388 ms/op
p(99.9990) =   1587.388 ms/op …
=> perf(java): Refactor ThreadPoolFury to improve performance

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
Try to use `System.arraycopy` when copying between byte arrays. This significantly increases performance, in our use case serialization is twice as fast (serializing/deserializing 1M complex strucutures using (de)serializeJavaObject in parallel). When using Platform.copyMemory, the JDK is doing a lot of type checking to see if it's a byte array, causing a visible slowdown. `Unsafe.memoryCopy` implementation was changed in Java 9 from a native method to a method calling the internal unsafe method containing the reflection checks.
There are a few places where System.arraycopy is already used, referring to it being faster on certain JDK implementations. Tested our use case on a macbook with arm64 cpu against zulu 21 and open-jdk 23. 
I tried to reproduce the performance impact through one on …
=> perf(java): Improve performance by using System.arraycopy to copy between byte arrays

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java, java/fury-core/src/main/java/org/apache/fury/serializer/StructSerializer.java
This PR refactors the field sorting in `StructSerializer.java` by caching transformed field names to avoid redundant computations during sorting. The `lowerCamelToLowerUnderscore` transformation is now applied once per field instead of multiple times.
=> perf(java): Refactor field sorting in StructSerializer to cache transformed field names and avoid redundant computation

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java, java/fury-core/src/main/java/org/apache/fury/serializer/StructSerializer.java, python/pyfury/_struct.py
The struct hash calculation implementations in Java and Python are inconsistent. When `classinfo` is `None` in the Python implementation, the method returns early without updating the hash value, whereas the Java implementation continues with a default hash value of 0.
Modified the `visit_customized` method in the Python implementation to initialize `hash_value` to 0 before checking if `classinfo` is `None`, ensuring the hash computation continues regardless of the `classinfo` status. This approach aligns with the Java implementation behavior.
Changes:
- Initialize `hash_value` to 0 at the beginning of the method
- Replace the early return with a conditional assignment to `hash_value`
- Always call `_compute_field_hash` at the end of the method
Verified the fix by running the …
=> fix(python): inconsistent struct hash calculation between Java and Python

java/fury-core/src/main/java/org/apache/fury/Fury.java, java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/meta/ClassDef.java, java/fury-core/src/main/java/org/apache/fury/meta/ClassDefDecoder.java, java/fury-core/src/main/java/org/apache/fury/meta/ClassDefEncoder.java, java/fury-core/src/main/java/org/apache/fury/meta/TypeExtMeta.java, java/fury-core/src/main/java/org/apache/fury/reflect/TypeRef.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/serializer/AbstractObjectSerializer.java, java/fury-core/src/main/java/org/apache/fury/serializer/ObjectSerializer.java, java/fury-core/src/main/java/org/apache/fury/type/GenericType.java, java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java, java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties, java/fury-core/src/test/java/org/apache/fury/meta/ClassDefTest.java, java/fury-core/src/test/java/org/apache/fury/resolver/ClassResolverTest.java
This pr supports passed tracking ref meta when building serializers. The meta can be pssed by Type Annotation in #2036 or by classdef encoded into binary.
=> feat(java): support passed tracking ref meta when building serializers

.github/workflows/ci.yml, ci/run_ci.sh, java/fury-core/src/main/java/org/apache/fury/resolver/DisallowedList.java, java/fury-core/src/test/java/org/apache/fury/resolver/DisallowedListTest.java
- add windows ci for java21
- Fix sha256 check error on windows:
Closes #2100
=> fix(java): fix disallowed.txt check in windows

java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java, java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java
fix nested chunk map serialization error when generics exists
Closes #2135
=> fix(java): fix nested chunk map serialization error when generics exists

java/fury-core/src/main/java/org/apache/fury/reflect/ReflectionUtils.java, java/fury-core/src/test/java/org/apache/fury/resolver/DisallowedListTest.java
1. Directly use the `DisallowedList#DISALLOWED_LIST_TXT_PATH` value in `DisallowedListTest#testCalculateSHA256`.
2. Directly use the `DisallowedList#SHA256_HASH` value in `DisallowedListTest#testCalculateSHA256`.
Reduce manual maintenance costs :smile:
=> chore(java): use the SHA256_HASH field value directly.

dart/packages/fury-test/test/datatype_test/fixed_num_test.dart, dart/packages/fury/lib/src/datatype/fury_fixed_num.dart
This PR improves the `FixedNum.from()` factory method by replacing the string-based type selection with a proper enum (`NumType`). The change eliminates the risk of runtime errors due to typos in string literals and enables better IDE support with autocomplete suggestions.
**Before:**
```dart
// String-based type selection
FixedNum.from(42, type: 'int32')  // Works
FixedNum.from(42, type: 'INT32')  // Works (case insensitive)
FixedNum.from(42, type: 'int-32') // Runtime error
```
**After:**
```dart
// Enum-based type selection
FixedNum.from(42, NumType.int32)  // Works, with IDE autocomplete
```
- The `FixedNum.from()` method now takes a `NumType` enum instead of a string for the type parameter
- The parameter is now positional optional rather than named optional
=> fix(dart): replace string-based type selection with enum in FixedNum factory method

java/fury-core/src/main/java/org/apache/fury/serializer/ObjectStreamSerializer.java
Ensure FuryObjectInputStream.read never returns 0 when length>0, so that when outer logic attempts to read in a while loop, it won't get stuck or throw exception.
#2204 
No.
No measurable performance impact is expected.
=> fix(java): ensure FuryObjectInputStream.read never returns 0 when length>0 #2204

.github/workflows/ci.yml, .github/workflows/release.yaml
Fix warnings in GitHub YAML configuration that were reported on #2224
=> chore(github): fix YAML warnings about spaces before comments

.github/workflows/ci.yml, ci/run_ci.sh, java/pom.xml
Explicitly enable annotation processing for Lombok jdk 24 support
No
Recent JDK versions require opting in to annotation processing.
=> chore(java): jdk 24 build support

java/fury-core/src/main/java/org/apache/fury/type/Descriptor.java, java/fury-core/src/main/java/org/apache/fury/type/DescriptorBuilder.java, java/fury-core/src/test/java/org/apache/fury/type/DescriptorTest.java
=> feat(java): add DescriptorBuilder for easy build and copying Descriptor

.gitignore
TestNG creates output files which are not ignored by `.gitignore`
=> chore(java): gitignore testng output

java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java, java/fury-core/src/test/java/org/apache/fury/memory/MemoryBufferTest.java
The implementation of MemoryBuffer.getRemainingBytes, if I am understanding correctly, should return only the remaining bytes. On a sliced buffer, it returns the shared bytes, which is different than the remaining bytes in the slice.
=> fix(java): MemoryBuffer getRemainingBytes can return unexpected results on a slice

java/fury-core/src/main/java/org/apache/fury/type/CustomTypeRegistry.java, java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java, java/fury-format/README.md, java/fury-format/src/main/java/org/apache/fury/format/encoder/ArrayDataForEach.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/ArrayEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/BaseBinaryEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/CustomCodec.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/CustomCollectionFactory.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/Encoders.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/MapEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/RowEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryUtils.java, java/fury-format/src/main/java/org/apache/fury/format/type/CustomTypeEncoderRegistry.java, java/fury-format/src/main/java/org/apache/fury/format/type/CustomTypeHandler.java, java/fury-format/src/main/java/org/apache/fury/format/type/CustomTypeRegistration.java, java/fury-format/src/main/java/org/apache/fury/format/type/TypeInference.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/CustomCodecTest.java
Extend Java Row Format to allow registering custom datatypes (e.g. UUID as Int128) and collection factories (e.g. `SortedSet<UUID>` as `new TreeSet<UUID>(customComparator)` )
Additionally supports arrays of custom types e.g. `UUID[]`
Since the type inference is in `fury-core` but I wanted to keep new features scoped to `fury-format`, I had to add a small plugin interface to core so that format can add types dynamically without affecting existing core behavior.
https://github.com/apache/fury/issues/2208
The `Encoders` class has new `registerCustomCodec` and `registerCustomCollectionFactory` methods.
All custom types are written with the existing protocol as embedded memory buffers just like any other field, but with a custom byte representation, so there should be no wire compatibility …
=> feat(java): row encoder supports custom types and collections

go/fury/buffer.go, go/fury/fury.go, go/fury/fury_xlang_test.go, go/fury/map.go, go/fury/serializer.go, go/fury/set.go, go/fury/slice.go, go/fury/str.go, go/fury/string.go, go/fury/struct.go, go/fury/type.go
1、Cross-language interoperability of furygo has been achieved (except for dynamic Pointers).
2、The new collection serialization has been implemented, and dynamic writing will be performed based on the object header
3、The chunk based map serialization has been implemented
4、The int type is written to a dynamic varint
5、The string becomes a dynamic string and will be written according to the encoding
It is hoped that the dynamic pointer problem can be solved in the next pr.
Close #2200
Close #2201
Close #2202
Close #2014
Relate #2198
=> feat(go): fury-go implements adaptation and optimization for new xlang

cpp/fury/benchmark/benchmark_string_util.cc
This PR fixes several minor issues and improves the implementation of string utility benchmarks:
- Corrected reversed function parameters.
- Fixed an incorrect function call.
- Replaced some usages of auto with explicit types for better readability and maintainability.
- Refactored random number generation by encapsulating std::mt19937 in a thread-local helper function.
One part of the original code used default random generation methods, which could result in uneven value distributions and non-deterministic behavior across platforms. To improve randomness quality and thread-safety, I replaced it with a `thread_local` encapsulated `std::mt19937` generator. This ensures better reproducibility and consistency during benchmarking.
After these changes, the code compiles and runs correctly. …
=> fix(C++): Fix reversed parameters and incorrect calls in string_util benchmark

java/fury-core/src/main/java/org/apache/fury/annotation/FuryField.java, java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java, java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java, java/fury-core/src/main/java/org/apache/fury/meta/ClassDef.java, java/fury-core/src/main/java/org/apache/fury/meta/ClassDefEncoder.java, java/fury-core/src/main/java/org/apache/fury/meta/TypeDefEncoder.java, java/fury-core/src/main/java/org/apache/fury/reflect/TypeRef.java, java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java, java/fury-core/src/main/java/org/apache/fury/resolver/FieldResolver.java, java/fury-core/src/main/java/org/apache/fury/serializer/ObjectSerializer.java, java/fury-core/src/main/java/org/apache/fury/type/Descriptor.java, java/fury-core/src/main/java/org/apache/fury/type/TypeResolutionContext.java, java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java, java/fury-core/src/test/java/org/apache/fury/CrossLanguageTest.java, java/fury-format/README.md, java/fury-format/src/main/java/org/apache/fury/format/encoder/ArrayDataForEach.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/ArrayEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/BaseBinaryEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/MapEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/RowEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryUtils.java, java/fury-format/src/main/java/org/apache/fury/format/type/TypeInference.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/ImplementInterfaceTest.java
You can now call `Encoders.registerLazyBeanInterface` and Fury will generate a bean implementation type for you.
This should allow easy integration with Immutables library for example - I will be testing that over the coming days.
Fixes #2223
New api to register interface types. Since this was not implemented before, there should be no breaking change.
=> feat(java): fury row encoder now supports implementing interfaces with simple value type

java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java, java/fury-format/README.md, java/fury-format/src/main/java/org/apache/fury/format/encoder/BaseBinaryEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/Encoders.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/RowEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/type/TypeInference.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/OptionalTest.java
Support `Optional<T>` in java row format
Stored as an inline nullable field - so this implementation chooses not to differentiate between `(Optional) null` and `Optional.empty()` and always deserialize as `empty`.
New type supported - docs updated
=> feat(java): row format supports Optional<T>

java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/Encoders.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryUtils.java, java/fury-format/src/test/java/org/apache/fury/format/encoder/EnumTest.java
support Enum values in row format nested bean / record types
=> fix(java): fix row type enum properties

.github/workflows/ci.yml, ci/run_ci.sh, integration_tests/latest_jdk_tests/pom.xml, integration_tests/latest_jdk_tests/src/test/java/org/apache/fury/integration_tests/RecordRowTest.java, java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/Encoders.java, java/fury-format/src/main/java/org/apache/fury/format/encoder/RowEncoderBuilder.java, java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryUtils.java, java/fury-format/src/main/java/org/apache/fury/format/type/TypeInference.java
Support Record types in row format
Treated as Bean types, except we have to use canonical constructor instead of unsafe field setting
Test only runs on Java 17+
New type support in java row format
=> feat(java): row format supports Record types

java/fory-core/src/main/java/org/apache/fory/type/TypeUtils.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/Encoders.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/GenericTypeTest.java
Given a typed-identifier type `class Id<T> { int id; }` and a `class T { Id<T> id; }`, Fury incorrectly reports a type cycle of T, but the Id type does not actually have any property of type T.
This is due to over-eager expansion of bean types in the type utils - all generic types are assumed to be used as property types, which is not always correct.
=> fix(java): row encoder incorrectly interprets type parameters as cycles

java/fory-core/src/main/java/org/apache/fory/serializer/scala/SingletonObjectSerializer.java
This PR fixes an issue in Scala. 
Since Scala object's are lazy, the singleton instance doesn't exist or it does exist, but its value is `null` so when `SingletonObjectSerializer.read` is called we get null. This PR resolves the issue by ensuring that the object is initialized before deserialization. 
https://github.com/apache/fury/issues/2249
I verified that this change resolves the issue for the repro code in the "Anything else?" section of https://github.com/apache/fury/issues/2249
```
[info] running Main 
2025-05-29 10:45:26 WARN  FuryBuilder:427 [sbt-bg-threads-5] - Class registration isn't forced, unknown classes can be deserialized. If the environment isn't secure, please enable class registration by `FuryBuilder#requireClassRegistration(true)` or configure ClassChecker by …
```
=> fix(scala): Ensure singleton classes are initialized before reading

ci/run_ci.sh, java/fory-core/src/test/java/org/apache/fory/CrossLanguageTest.java, java/fory-format/src/test/java/org/apache/fory/format/CrossLanguageTest.java, java/fory-test-core/src/main/java/org/apache/fory/test/TestUtils.java
right now a Java dev has to contend with failing tests that require Python
by skipping the xlang tests when pyfory is not available, a Java developer can build without needing to set up pyfory
=> chore(java): skip xlang tests when pyfory is not available

java/fory-core/src/main/java/org/apache/fory/Fory.java, java/fory-core/src/main/java/org/apache/fory/resolver/ClassInfo.java, java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java, java/fory-core/src/main/java/org/apache/fory/serializer/Serializer.java, java/fory-core/src/main/java/org/apache/fory/serializer/collection/CollectionSerializers.java, java/fory-core/src/main/java/org/apache/fory/serializer/collection/MapSerializers.java, java/fory-core/src/main/java/org/apache/fory/serializer/collection/SubListSerializers.java, java/fory-core/src/test/java/org/apache/fory/ForyTest.java, java/fory-core/src/test/java/org/apache/fory/serializer/EnumSerializerTest.java, java/fory-format/src/main/java/org/apache/fory/format/vectorized/ArrowSerializers.java
The Fory class fields `language` and `crossLanguage` are redundant and can be quickly determined using `crossLanguage` without the need for `language`.
=> chore(java): Use `crossLanguage` instead of `language` in Fory

.gitignore
right now, running integration tests makes your checkout not clean
=> chore(java): gitignore test-output from integration_tests as well as java

java/fory-core/src/main/java/org/apache/fory/type/Descriptor.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java
Bean interface method descriptor discovery incorrectly includes static methods like `static Builder builder()`
=> fix(java): descriptors for beans should not include static methods

java/fory-core/src/main/java/org/apache/fory/config/Config.java
#2272: adding a clear message when failing `deserializeNonexistentClass` precondition check in `Config`.
=> feat(java): Adding explanatory message to `deserializeNonexistentClass` misconfiguration in `Config`

integration_tests/latest_jdk_tests/src/test/java/org/apache/fory/integration_tests/RecordRowTest.java, java/fory-core/src/main/java/org/apache/fory/type/TypeResolutionContext.java, java/fory-core/src/main/java/org/apache/fory/type/TypeUtils.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/ArrayDataForEach.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/BaseBinaryEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/Encoders.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/type/TypeInference.java
Row encoder synthesized interfaces now work inside enclosing record classes.
The previous logic was over-complicated to work around the overly aggressive expanding of types. With the fix in #2265 this is no longer necessary and we can simplify the logic around detecting interfaces to synthesize, in a way that better supports nesting too.
=> feat(java): row encoder supports synthesizing interfaces nested inside of records

java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/OptionalTest.java
fix incorrect handling of lazy-read `(Optional) null` values
=> fix(java): row encoder interface synthesis handle `(Optional) null` correctly

.github/workflows/release.yaml, LICENSE, integration_tests/latest_jdk_tests/src/test/java/org/apache/fory/integration_tests/RecordRowTest.java, java/fory-core/src/main/java/org/apache/fory/collection/LongLongByteMap.java, java/fory-core/src/main/java/org/apache/fory/resolver/MetaStringResolver.java, java/fory-core/src/main/java/org/apache/fory/type/TypeResolutionContext.java, java/fory-core/src/main/java/org/apache/fory/type/TypeUtils.java, java/fory-core/src/main/resources/META-INF/LICENSE, java/fory-core/src/main/resources/META-INF/native-image/org.apache.fory/fory-core/native-image.properties, java/fory-core/src/test/java/org/apache/fory/collection/LongLongByteMapTest.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/ArrayDataForEach.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/BaseBinaryEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/Encoders.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/type/TypeInference.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/OptionalTest.java, licenserc.toml
=> chore: cherry pick commits for 0.11.0

java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java, java/fory-core/src/test/java/org/apache/fory/resolver/ClassResolverTest.java
Support customized serializer for abstract or interface. 
First, cache `absClassInfo` in `extRegistry` when `setClassInfo` if class is abstract or interface.
And then, find that in `createSerializer` for new type of Class. If match, return the customized (abs)serializer .
- https://github.com/apache/fory/issues/1806
=> feat(java): Support customized serializer for abstract or interface.

java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
Reduce reflection calls by skip find customized serializer when absClassInfo is empty.
=> chore(java): skip find customized serializer when absClassInfo is empty

bazel/fory_deps_setup.bzl
fory_large_tuple: Mean +- std dev: [base] 116 ms +- 5 ms -> [new] 115 ms +- 1 ms: 1.01x faster
fory_large_float_tuple: Mean +- std dev: [base] 142 ms +- 3 ms -> [new] 137 ms +- 9 ms: 1.04x faster
fory_large_boolean_tuple: Mean +- std dev: [base] 43.6 ms +- 0.6 ms -> [new] 37.8 ms +- 0.4 ms: 1.15x faster
fory_large_list: Mean +- std dev: [base] 119 ms +- 4 ms -> [new] 117 ms +- 1 ms: 1.02x faster
Benchmark hidden because not significant (5): fory_dict, fory_large_dict, fory_dict_group, fory_tuple, fory_list
Geometric mean: 1.02x faster
=> feat(python): bump cython to 3.1.1

java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java
fix incorrect handling of Optional types nested inside of synthesized bean interfaces
If we build another 0.11.0 rc, it would be nice to include this fix if possible.
=> fix(java): fix row encoder synthesized interface lazy-decoding of Optional

ci/generate_release_note.py
A tool to generate release note from github generated release note
=> chore: add release note generate tool

java/fory-format/src/main/java/org/apache/fory/format/encoder/BaseBinaryEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java
Fix the logic for type with custom codec wrapped in Optional, currently causes compile error
Please review #2320 first; this PR depends on that fix
And please consider for a 0.11.0-rc2 if that happens, otherwise 0.11.1
=> fix(java): fix row format handling Optional of type with custom codec

java/fory-core/src/main/java/org/apache/fory/type/TypeUtils.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/ArrayEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/Encoders.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java
improve array row encoder to support custom collections that are not List, for example TreeSet
also supports interface types as value
=> feat(java): array row encoder supports set of interface type

python/pyfory/_registry.py, python/pyfory/_serialization.pyx, python/pyfory/_struct.py, python/pyfory/tests/test_cross_language.py
Fixed the incorrect arguments passed to compute_string_hash in StructHashVisitor.visit_customized when calculating the hash value.
- Aligned this change with the Java implementation after consulting the project founder.
- Exposed Cython’s TypeResolver in Python so its internal _resolver could provide the namespace and typename decoders.
- Marked the _resolver field as readonly to allow external read access without permitting modification.
- Added the issue author’s example to the test suite for validation.
- Noted in the test file comments that objects with self-references cannot be compared using ==; instead, comparison of serialized data is recommended.
close #2332
=> fix(python): correct compute_string_hash usage in StructHashVisitor.visit_customized

java/fory-core/src/main/java/org/apache/fory/serializer/TimeSerializers.java, java/fory-core/src/test/java/org/apache/fory/serializer/TimeSerializersTest.java
The JDK `ZoneOffset.ofTotalSeconds(...)` method uses a concurrent hash map for caching zone offsets with values for each 15 minutes (UTC, +01:00, +01:15, etc.), this causes a noticeable overhead when deserializing a lot of zone offsets. This PR overrides that caching for the single byte representation using an array, which is in line with the 15 minute JDK caching.
=> perf(java): Improve zone offset deserialization performance by overriding JDK caching

docs/guide/row_format_guide.md
This PR adds documentation to `row_format_guide.md` for recent enhancements that support Java `interface` types and class inheritance (`extends`) in row format mapping.
The update includes code examples demonstrating how to register interface mappings and superclass support using Fury's Java API.
- #2310
- [#2243](https://github.com/apache/fory/pull/2243)
- [#2250](https://github.com/apache/fory/pull/2250)
- [#2256](https://github.com/apache/fory/pull/2256)
Yes. It introduces user-facing documentation explaining how to use interface and extension types with row encoding in Java.
=> docs: add row format guide for ext and interface types

java/fory-core/src/main/java/org/apache/fory/builder/BaseObjectCodecBuilder.java, java/fory-core/src/main/java/org/apache/fory/builder/CodecBuilder.java, java/fory-core/src/main/java/org/apache/fory/codegen/Expression.java, java/fory-core/src/main/java/org/apache/fory/type/TypeUtils.java, java/fory-core/src/test/java/org/apache/fory/codegen/ExpressionVisitorTest.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/BaseBinaryEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/row/binary/BinaryUtils.java, java/fory-format/src/main/java/org/apache/fory/format/type/TypeInference.java
currently, optional wrappers are stored as a bean with two fields - present and value, taking 32 bytes
with this change, stored as nullable primitive, taking 8 bytes plus 1 bit for null
this is a breaking change to the row format, but since support is relatively recent, hopefully that is ok?
=> feat(java): store OptionalInt, OptionalLong, OptionalDouble same as nullable values

docs/guide/java_serialization_guide.md
Add a few clarifications to java serialization docs regarding multi-threading: `ThreadLocalFury` not appropriate for virtual threads, and `MetaContext` cannot be reused across threads.
=> docs: adding multi-threading clarifications for java serialization

.bazelrc, .github/workflows/ci.yml, .github/workflows/release.yaml, BUILD, ci/deploy.sh, ci/run_ci.py, ci/run_ci.sh, cpp/fory/type/BUILD, python/setup.py
- Enable Ubuntu 24.04 ARM builds in CI matrix
- Update `ci/run_ci.sh` to detect architecture and install Bazel accordingly
- Use `.bazelversion` for centralized Bazel version management
- Refactor Bazel download logic for Linux and macOS architectures
- Adjust build configurations for CPU-specific compiler flags
- Update `.bazelrc` with platform-specific C++ compilation and optimization flags
Fixes #1915 and #2330 
Sort of: Mac users can now run pyfury in Ubuntu containers (for testing etc.)
I used the following scripts to locally create the python wheel:
```bash
#!/bin/bash
set -e
IMAGE_NAME="fory-ubuntu24-arm64-build:latest"
export DOCKER_BUILDKIT=1
echo "Building Docker image..."
docker buildx build --load -t "$IMAGE_NAME" -f ubuntu-arm64-build.Dockerfile .
echo "Running build in …
```
=> feat(python): Add Python Linux ARM64 support and optimize Bazel installation

java/fory-format/src/main/java/org/apache/fory/format/encoder/BaseBinaryEncoderBuilder.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/LazyArray.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/LazyArrayData.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java
this way if you use only some indexes, you don't pay deserialization costs for any unread indexes
When List subtype is not specified, now we use our own lazy list. Since the user did not specify type, it should be ok, and you can always specify `ArrayList` to materialize the list eagerly
=> feat(java): row encoder array deserialization into List supports lazy access

python/pyfory/_struct.py, python/pyfory/serializer.py, python/pyfory/tests/test_struct.py
- Extended DataClassSerializer to support both Python native and xlang serialization modes.
- ComplexObjectSerializer is now a deprecated alias for DataClassSerializer (in xlang mode).
- Added tests for DataClassSerializer in xlang mode.
Completes #2157 
Not yet: we deprecate `ComplexObjectSerializer` in order give users time to migrate.
=> refactor(python): Unify DataClassSerializer and ComplexObjectSerializer

scala/src/test/scala/org/apache/fory/serializer/scala/ScalaTest.scala
I presume the test used to fail with an exception but now it passes, it is better not to have printlns and to actually compare the result of the deserialization to the original.
=> chore(Scala): refactor scala test so it asserts something

scala/src/test/scala/org/apache/fory/serializer/scala/DurationTest.scala
* the way that Scala Durations have been represented internally has changed between recent Scala versions
* it is useful to test that serialization/deserialization works
* it would be a breaking change but it might be useful for fory-scala to have a dedicated serializer for Scala Durations that converted the duration to ISO-8601 duration string (eg `PT1H` for 1 hour).
* this would mean that we wouldn't be relying on the internal state of class instances but have a format that is independent of the Duration class internal state but that still is easy for us to deserialize and match to meaningful new Scala Duration instance when we deserialize
=> chore(Scala): Create DurationTest.scala

python/pyfory/tests/core.py
I was encountering this warning in tests:
```
pyfory/tests/core.py:27
/workspace/python/pyfory/tests/core.py:27: PytestUnknownMarkWarning: Unknown pytest.mark.fory_format - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
func = pytest.mark.fory_format(func)
```
`fory_format` is [not currently defined](https://github.com/search?q=repo%3Aapache%2Ffory%20fory_format&type=code) so I decided to remove it.
* Rewrote the skip condition logic for pyarrow tests.
* The previous logic was a bit verbose and could be simplified.
* The new implementation directly checks if pyarrow is not installed or lacks the necessary attribute.
No
N/A
=> refactor(python): Simplify require_pyarrow, remove undefined pytest.mark

python/pyfory/__init__.py, python/pyfory/_registry.py, python/pyfory/_struct.py, python/pyfory/serializer.py
I realized I did not remove usages of `ComplexObjectSerializer` when I submitted #2389 
* Remove ComplexObjectSerializer from pyfory/__init__.py.
* Update _registry.py to use DataClassSerializer directly instead of ComplexObjectSerializer.
* Remove ComplexObjectSerializer definition from _struct.py.
No
N/A
=> feat(python): Replace usage of ComplexObjectSerializer with DataClassSerializer

java/fory-core/src/main/java/org/apache/fory/util/ExceptionUtils.java, java/fory-core/src/test/java/org/apache/fory/ForyTest.java
This test fails. I had expected it to fail with null when wrong type was used (because of #2392 but this fails differently from that - the use case where I saw a null returned was a Scala use case)
Fails with IndexOutOfBoundsException while I would expect a nicer exception. Maybe should be a Fory DeserializationException.
```
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(2) exceeds size(7): org.apache.fory.memory.MemoryBuffer$BoundChecker@4e268090
at org.apache.fory.memory.MemoryBuffer$BoundChecker.fillBuffer(MemoryBuffer.java:186)
at org.apache.fory.memory.MemoryBuffer.checkReadableBytes(MemoryBuffer.java:2440)
at org.apache.fory.ForyTest_Struct2ForyCodec_0.read(ForyTest_Struct2ForyCodec_0.java:59)
at org.apache.fory.Fory.readDataInternal(Fory.java:1055)
at …
```
=> chore(Java): handle deserialization scenario that currently throws an IndexOutOfBoundsException

python/pyfory/_registry.py, python/pyfory/serializer.py, python/pyfory/tests/test_reduce_serializer.py
* Add ReduceSerializer class to handle objects with __reduce__ or __reduce_ex__ methods.
* This serializer has higher precedence than StatefulSerializer.
* Implement serialization and deserialization logic for various __reduce__ return formats.
* Add comprehensive tests for ReduceSerializer, covering different scenarios and precedence.
* Update _registry.py to register ReduceSerializer and handle its precedence.
* Ensure cross-language compatibility by using Fory's native serialization format.
Closes #2294
=> feat(python): Implement ReduceSerializer for __reduce__ support

python/pyfory/_registry.py, python/pyfory/codegen.py, python/pyfory/serializer.py, python/pyfory/tests/test_function.py
* Implement `FunctionSerializer` to handle serialization and deserialization of function objects.
* Utilize `cloudpickle` for robust function serialization, including closures and lambdas.
* Introduce new test cases in `test_function.py` to cover various function types:
* Lambda functions (simple and with closures).
* Regular functions.
* Nested functions.
* Register `FunctionSerializer` in `_registry.py` for automatic detection and handling of function types during serialization.
* Ensure compatibility with both cross-language and Python-only modes.
Closes #2301 and #2402 
Not done
=> feat(python): Add FunctionSerializer for function serialization

python/README.md, python/pyfory/tests/core.py
I made a mistake in #2396 when I changed
```python
func = pytest.mark.fory_format(func)
arrow_installed = False
if pa is not None and hasattr(pa, "get_library_dirs"):
arrow_installed = True
func = pytest.mark.skipif(not arrow_installed, reason="pyarrow not installed")(func)
return func
```
to
```python
arrow_not_installed = pa is None or hasattr(pa, "get_library_dirs")
mark_decorator = pytest.mark.skipif(arrow_not_installed, reason="pyarrow not installed")(func)
return mark_decorator
```
The second condition, `hasattr(pa, "get_library_dirs")`, should have been negated. I noticed this when [arrow tests were incorrectly being skipped](https://github.com/apache/fory/actions/runs/16297878100/job/46024343029) :|
* Fix incorrect pyarrow installation check in core.py
* Add troubleshooting steps …
=> fix: Correct pyarrow installation check and add bazel troubleshooting

.github/workflows/ci.yml, ci/run_ci.py, ci/run_ci.sh, ci/tasks/__init__.py, ci/tasks/common.py, ci/tasks/cpp.py, ci/tasks/format.py, ci/tasks/go.py, ci/tasks/java.py, ci/tasks/javascript.py, ci/tasks/kotlin.py, ci/tasks/python.py, ci/tasks/rust.py, javascript/packages/fory/index.ts, javascript/test/hps.test.ts
At the suggestion of @LiangliangSui and @PragmaTwice, we propose a staged migration from shell scripts to Python per language. Please review the PR carefully; it was computer assisted.
* Refactor CI runner from shell scripts to a Python-based system.
* Introduces `ci/run_ci.py` as the main entry point for CI tasks.
* Organizes CI logic into modular Python files within `ci/tasks/`.
* Replaces shell script calls with Python function calls for each language.
* Updates GitHub Actions workflows (`.github/workflows/ci.yml`) to use the new Python runner.
* Enhances argument parsing for better control over CI tasks (e.g., specifying Java versions).
* Adds support for various Java versions, including specific scenarios like Windows Java 21 and GraalVM.
* Includes new CI tasks for Go and code …
=> refactor(ci): Migrate CI runner to Python scripts

python/pyfory/tests/test_cross_language.py
add execute doc for cross langauge tests in python
#2409
=> chore(python): add execute doc for cross langauge tests in python

java/fory-format/pom.xml, java/fory-format/src/main/java/org/apache/fory/format/type/DefaultTypeVisitor.java
Attempt 2 for #2421, now that we have java 11 baseline, thanks @chaokunyang 
arrow 15.0.0 is marked as vulnerable to CVE-2024-52338 Despite this CVE only affecting the R implementation, the CPE is not scoped to R so Java checkers will report as vulnerable:
```
13:25:42  [ERROR] One or more dependencies were identified with vulnerabilities:
13:25:42  [ERROR] arrow-memory-core-15.0.0.jar (pkg:maven/org.apache.arrow/arrow-memory-core@15.0.0, cpe:2.3:a:apache:arrow:15.0.0:*:*:*:*:*:*:*): CVE-2024-52338(9.8)
```
while this is really a problem with the CPE, not fory, the easiest fix by far is to simply update arrow
=> chore(java): arrow 18.3.0

docs/guide/java_serialization_guide.md, java/fory-core/src/main/java/org/apache/fory/memory/MemoryAllocator.java, java/fory-core/src/main/java/org/apache/fory/memory/MemoryBuffer.java, java/fory-core/src/test/java/org/apache/fory/memory/MemoryAllocatorTest.java
This PR introduces a new `MemoryAllocator` interface that allows customisation of memory allocation strategies in `MemoryBuffer`. This enables users to implement custom allocation policies.
- Closes https://github.com/apache/fory/issues/2459
- https://github.com/apache/fory/pull/2457 
- Closes https://github.com/apache/fory/issues/2350.
=> feat(memory): add customizable MemoryAllocator interface 

java/fory-format/src/main/java/org/apache/fory/format/encoder/Encoders.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/MapEncoderTest.java
We dynamically select the key and value type, and tried using this overload of Encoders.mapEncoder
With the single-arg mapEncoder invocation, bean codec classes are loaded with `token4BeanLoad`
But this overload never loads the bean classes leading to unexpected exceptions during Map codec compile since bean codecs are not loaded
=> fix(java): Encoders.mapEncoder(TypeRef, TypeRef, TypeRef, Fory) should load bean classes

.github/workflows/release-python.yaml
`actions/download-artifact` is [failing to find artifacts](https://github.com/apache/fory/actions/runs/17198889531/job/48785824375) despite [artifacts being created](https://github.com/apache/fory/actions/runs/17198794761).
Pass the github token so the action can find artifacts from other workflow runs (ours are separate).
=> ci: Pass the GH token to actions/download-artifact

java/fory-core/src/main/java/org/apache/fory/memory/MemoryBuffer.java, java/fory-core/src/test/java/org/apache/fory/memory/MemoryBufferTest.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java
Current implementation throws IAE for size zero buffers
=> fix(java): MemoryBuffer tests that equalTo works with size zero buffers

java/fory-core/src/main/java/org/apache/fory/builder/ObjectCodecBuilder.java
Calculating the `classVersionHash` can be quite expensive and can currently have side-effects. This PR implements a simple optimization that skips the calculation entirely if `fory.checkClassVersion() == false`.
See https://github.com/apache/fory/issues/2559
=> fix(java): Skip calculation of classVersionHash if checkClassVersion is false

java/fory-core/src/main/java/org/apache/fory/annotation/Ignore.java, java/fory-core/src/main/java/org/apache/fory/type/Descriptor.java, java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/ImplementInterfaceTest.java
this allows you to mark methods as not properties, for example if you have a computed value with a `default` method
=> feat(java): bean encoder implemented interfaces honor `@Ignore`

java/fory-format/src/main/java/org/apache/fory/format/row/binary/writer/BinaryRowWriter.java, java/fory-format/src/main/java/org/apache/fory/format/row/binary/writer/BinaryWriter.java, java/fory-format/src/test/java/org/apache/fory/format/encoder/RowEncoderTest.java
when reusing buffers during encoding, if a field changes from not-null to null, the offset and size from previous encode operations will remain in the output buffer
this causes hash mismatch for the same input object depending on previous serialized objects
=> fix(java): row format buffer recycling leaves offset and size for null values

ci/format.sh, python/pyfory/_fory.py, python/pyfory/_registry.py, python/pyfory/_serialization.pyx, python/pyfory/_serializer.py, python/pyfory/_struct.py, python/pyfory/format/__init__.py, python/pyfory/format/tests/test_encoder.py, python/pyfory/meta/typedef.py, python/pyfory/meta/typedef_decoder.py, python/pyfory/meta/typedef_encoder.py, python/pyfory/serializer.py, python/pyfory/tests/benchmark.py, python/pyfory/tests/record.py, python/pyfory/tests/test_buffer.py, python/pyfory/tests/test_codegen.py, python/pyfory/tests/test_meta_share.py, python/pyfory/tests/test_metastring.py, python/pyfory/tests/test_typedef_encoding.py, python/pyfory/type.py
implement meta share mode for pyfory, so the struct can add/delete fields and have inconsistent schema bettween serialization and deserialization
#2509
https://github.com/apache/fory/issues/1938
https://github.com/apache/fory/issues/2160
https://github.com/apache/fory/pull/2278
=> feat(python): meta share mode for pyfory compatible serialization

java/fory-core/src/test/java/org/apache/fory/CrossLanguageTest.java, python/pyfory/_registry.py, python/pyfory/meta/typedef_encoder.py, python/pyfory/tests/test_cross_language.py
Fix & optimize cross-language meta-share mode
=> perf(python/java): Fix & optimize cross-language meta-share mode

go/fory/slice.go, go/fory/type.go
In the Fory Go implementation, slices of basic types (such as `[]int32`, `[]bool`, etc.) were not correctly mapped to the corresponding array types during cross-language serialization. Instead, they were treated as generic LIST types, leading to inconsistencies with other languages (Python, Java, etc.).
Specialized array serializers were added in `slice.go`:
- `boolArraySerializer` (TypeId: 30) - Handles `[]bool`
- `int8ArraySerializer` (TypeId: 31) - Handles `[]int8` 
- `int16ArraySerializer` (TypeId: 32) - Handles `[]int16`
- `int32ArraySerializer` (TypeId: 33) - Handles `[]int32`
- `int64ArraySerializer` (TypeId: 34) - Handles `[]int64`
- `float32ArraySerializer` (TypeId: 36) - Handles `[]float32`
- `float64ArraySerializer` (TypeId: 37) - Handles `[]float64`
the correct TypeId mapping …
=> feat(go): align cross-language type serialization for primitive arrays

ci/run_ci.sh, go/fory/type.go
My previous PR #2615 had an incomplete implementation that was exposed by the recent metashare changes.
The factory-based registration only registered serializers to `typeToSerializers` map but didn't create complete `TypeInfo` objects with metadata (`PkgPathBytes`, `NameBytes`, etc.). This latent bug was exposed when metashare code path changes made `WriteMetaStringBytes()` calls mandatory, resulting in nil pointer dereference.
And CI **didn't run** `go test -v` in the `tests/` directory, so the codegen tests that would have caught this issue were not executed
**1. Complete the factory-based registration**
**Before (Incomplete):**
```go
// Only registered serializers, missing TypeInfo creation
for type_, factory := range factories {
serializer := factory()
r.typeToSerializers[type_] = …
```
=> fix(go): Complete type registration in factory-based serializer system

java/fory-core/src/main/java/org/apache/fory/builder/MetaSharedCodecBuilder.java, java/fory-core/src/main/java/org/apache/fory/meta/ClassDef.java, java/fory-core/src/main/java/org/apache/fory/reflect/FieldAccessor.java, java/fory-core/src/main/java/org/apache/fory/reflect/ReflectionUtils.java, java/fory-core/src/main/java/org/apache/fory/serializer/AbstractObjectSerializer.java, java/fory-core/src/main/java/org/apache/fory/serializer/MetaSharedSerializer.java, java/fory-core/src/main/java/org/apache/fory/serializer/converter/FieldConverter.java, java/fory-core/src/main/java/org/apache/fory/serializer/converter/FieldConverters.java, java/fory-core/src/main/java/org/apache/fory/type/Descriptor.java, java/fory-core/src/main/java/org/apache/fory/type/DescriptorBuilder.java, java/fory-core/src/main/resources/META-INF/native-image/org.apache.fory/fory-core/native-image.properties, java/fory-core/src/test/java/org/apache/fory/serializer/MetaSharedCompatibleTest.java
Support type converters for comaptible mode, so the deserialization peer can have different type for fields, and fory can convert to target type instead of ignoring it.
Closes #2636
#1870
=> feat(java): support type converters for comaptible mode

go/README.md, go/fory/cmd/fory/main.go, go/fory/codegen/generator.go, go/fory/codegen/parser.go, go/fory/tests/structs.go
Updates the annotation marker used to identify structs for code generation, making it more explicit and consistent with Go's generate conventions.
- Changes the code generation annotation from `//fory:gen` to `//fory:generate` 
- Updates all related documentation and help text
- #2227
=> refactor(go): Change codegen annotation from //fory:gen to //fory:generate

java/fory-core/src/test/java/org/apache/fory/RustXlangTest.java, rust/fory-core/src/meta/type_meta.rs, rust/fory-core/src/resolver/type_resolver.rs, rust/fory-core/src/serializer/enum_.rs, rust/fory-core/src/serializer/mod.rs, rust/fory-core/src/serializer/skip.rs, rust/fory-core/src/serializer/struct_.rs, rust/fory-derive/src/object/derive_enum.rs, rust/fory-derive/src/object/misc.rs, rust/fory-derive/src/object/read.rs, rust/fory-derive/src/object/serializer.rs, rust/fory-derive/src/object/write.rs, rust/tests/tests/test_compatible.rs, rust/tests/tests/test_cross_language.rs
1. Extract part of the compile-time code out and mark them with `#[inline(always)]` for inlining, which makes IDE hints and debugging quite convenient and avoid performance loss.
2. Fix logic of named_enum && skip enum.
3. Enable some java <-> rust unit tests. Thanks to #2654 && #2655
Fixes #2653
=> refactor(Rust): Refactor compile-time code & fix named_enum & fix skip enum

ci/run_ci.py, ci/run_ci.sh, go/fory/fory.go, go/fory/fory_test.go, go/fory/reference.go, go/fory/reference_test.go, go/fory/serializer.go, go/fory/set.go, go/fory/slice.go, go/fory/struct.go, go/fory/type.go, go/fory/type_def.go
Refine collection header bitmap to make it more understandable.
* Change the CollectionNotDeclElementType bit to CollectionIsDeclElementType, so now 0b100 represents declared type.
* Fix several bugs inside writeSameType of collection serializer
* Remove references tracking on string
#2642
=> refactor(go): refine collection header bitmap

integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/EnsureSerializerExample.java, integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/Main.java, integration_tests/graalvm_tests/src/main/resources/META-INF/native-image/org.apache.fory/graalvm_tests/native-image.properties, java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java, java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java, java/fory-core/src/main/resources/META-INF/native-image/org.apache.fory/fory-core/native-image.properties
Custom serializers are not retained during GraalVM native image builds.
The original code checks against `initialClassInfos` and removes serializers outside the set during native image builds. This PR removes that as well as `initialClassInfos`.
I don't know what `initialClassInfos` is for, because it is only involved in clearing serializers, which this PR is to remove.
Also, since the tests before weren't retaining some serializers, it turns out the original `native-image.properties` might be incomplete. And I added more classes to `--initialize-at-build-time` as is hinted by the `native-image` command.
- Fixes #2669
=> fix(java): retain serializers in graalvm native images

java/fory-core/src/main/java/org/apache/fory/Fory.java
修改无法从LZ4BlockInputStream流中无法反序列化大对象的问题。
#2686
=> fix(java): fix InputStream read big buffer error

java/fory-core/src/test/java/org/apache/fory/serializer/collection/CollectionSerializersTest.java
`CollectionSerializersTest#tesPriorityQueueSerializer` tries to compare the content of a PriorityQueue to an expected ImmutableList using `ImmutableList.copyOf()`, but the PriorityQueue is based on a heap and does not guarrentee any ordering in its underlying data structures. Therefore the `toArray()` method which `copyOf()` invokes will return non-deterministic results. 
We can reproduce this non-deterministic failure with [NonDex](https://github.com/TestingResearchIllinois/NonDex):
```
mvn -pl fory-core edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.fory.serializer.collection.CollectionSerializersTest#tesPriorityQueueSerializer
```
This PR uses `sortedCopyOf()` instead to enforce the ordering of elememts in the new ImmutableList, which removes the flakiness. 
This …
=> fix(java): Fix flakiness in CollectionSerializersTest#tesPriorityQueueSerializer

rust/fory-core/src/serializer/trait_object.rs, rust/tests/tests/test_rc_arc_trait_object.rs
This PR supports shared ref for arc/rc<dny T> by forward serialization/deserialization to `arc/rc<dny T>` using `upcast/downcast`
Closes #2705 
#2691 
#2704
=> feat(rust): support shared reference tracking for arc/rc<dny T>

rust/fory-core/src/serializer/trait_object.rs, rust/tests/tests/test_rc_arc_trait_object.rs
Deref/DerefMut can make a new type behave like a pointer
add deref to arc/rc wrapper to let wrapper behave like a pointer
=> feat(rust): add deref to arc/rc wrapper

rust/fory-core/benches/simd_bench.rs, rust/fory-core/src/buffer.rs, rust/fory-core/src/meta/mod.rs, rust/fory-core/src/meta/string_util.rs, rust/fory-core/src/serializer/string.rs
Use SIMD to se/de string
close #2713 
close #2658
hardware：
```
Chip: Apple M1 Pro
Total Number of Cores: 10 (8 performance and 2 efficiency)
Memory: 16 GB
```
output:
```
Write Latin-1 SIMD size 100
time:   [119.07 ns 119.88 ns 120.74 ns]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
Write Latin-1 Standard size 100
time:   [327.71 ns 329.71 ns 332.30 ns]
Found 9 outliers among 100 measurements (9.00%)
8 (8.00%) high mild
1 (1.00%) high severe
Write Latin-1 SIMD size 1000
time:   [826.19 ns 827.90 ns 829.97 ns]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
Write Latin-1 Standard size 1000
time:   [2.3436 µs 2.3459 µs 2.3488 µs]
Found 8 outliers among 100 measurements (8.00%)
1 (1.00%) low mild
4 (4.00%) high mild
3 (3.00%) high severe
Write …
```
=> perf(Rust): Use SIMD to se/de string
