- README.md
update java snapshot url
Closes #634
> [Java] update java snapshot url

- README.md
- docs/benchmarks/README.md
Add java benchmark data
Closes #638
> [Docs] add benchmark data

- README.md
- docs/benchmarks/README.md
use camel naming for benchmark class doc
Closes #xxxx
> [Doc] use camel naming for benchmark class doc

- README.md
- docs/user_guide.md
Update security doc
Closes #641
> [Docs] Update security doc

- LICENSE
- java/fury-core/src/main/java/io/fury/type/Generics.java
- java/fury-core/src/test/java/io/fury/type/GenericsTest.java
- java/pom.xml
update license for Generics
Closes #643
> [Java] update license for Generics

- README.md
update java security doc: add missing class registration check docs
Closes #xxxx
> [Java] update java security doc

- go/README.md
update golang readme
Closes #647
> [Go] update golang readme

- README.md
- docs/user_guide.md
Replace Fury.Language by Language in java doc
Closes #649
> [Doc] replace Fury.Language by Language

- java/fury-format/README.md
update java row readme
Closes #xxxx
> [Java] update java row readme

- README.md
- docs/guide/java_object_graph_guide.md
rename inner fury to f when creating ThreadSafeFury
Closes #675
> [Doc] rename inner fury to f when creating ThreadSafeFury

- java/fury-core/src/main/java/io/fury/serializer/StringSerializer.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_Lookup.java
Support string zerocopy for jdk14/17
Closes #91
> [Java] Support string zerocopy for jdk14+

- ci/deploy.sh
Add deploy script:
- Deploy java/python
- Bump version for java/python/javascript
- Setup python environment
Closes #687
> [CI] Add deploy script

- ci/deploy.sh
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/pom.xml
Support maven release
Closes #690
> [Java] Support maven release

- README.md
add java release jar doc
Closes #692
> [Doc] add java release jar for v0.1.0-alpha.1

- README.md
Fix release jar doc: remove extra ```
Closes #xxxx
> [Doc] Fix release jar doc

- README.md
Refine readme for more readability 
Closes #696
> [Doc] Refine readme for more readability 

- java/fury-core/src/main/java/io/fury/serializer/LambdaSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/Serializers.java
- java/fury-core/src/test/java/io/fury/serializer/LambdaSerializerTest.java
- Add detailed lambda error message
- Refine serializer creation exception
Closes #697
> [Java] Add detailed lambda error

- README.md
Fix threadsafe example
Closes #xxxx
> [Doc] Fix threadsafe example

- docs/guide/java_object_graph_guide.md
fix threadsafe fury in java guide
Closes #xxxx
> [Docs] fix threadsafe fury in java guide

- README.md
- docs/guide/java_object_graph_guide.md
remove bracket from classLoader
Closes #xxxx
> [Docs] remove bracket from classLoader

- java/pom.xml
add maven source plugin, which is removed in #691
#691
> [Java] add maven source plugin

- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/serializer/CodegenSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/GuavaSerializers.java
- java/fury-core/src/test/java/io/fury/FuryTest.java
Support jit for non public classes
Closes #720
> [Java] Support jit for non public classes

- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
add type tag registration check
Closes #xxxx
> [Java] add type tag registration check

- README.md
- docs/benchmarks/README.md
Highlight warmup to avoid incorrrect benchmark results from users
Closes #xxxx
> [Doc] highlight warmup

- README.md
- docs/guide/java_object_graph_guide.md
- docs/guide/xlang_object_graph_guide.md
- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/test/java/io/fury/CyclicTest.java
- java/fury-core/src/test/java/io/fury/serializer/TimeSerializersTest.java
- python/pyfury/_fury.py
- python/pyfury/_serialization.pyx
disable reference tracking by default
Closes #726
> [Java/Python] disable reference tracking by default

- java/fury-core/src/main/java/io/fury/codegen/CodeGenerator.java
debug log code stats to reduce fury log
Closes #729
> [Java] debug log code stats

- README.md
upgrade java install to 0.1.0-alpha.2
#730
> [Java] upgrade java install to 0.1.0-alpha.2

- README.md
> [Doc] use fury png logo

- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectStreamSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java
Rename writeNonRefT to writeNonRef
Closes #xxxx
> [Java] rename writeNonRefT to writeNonRef

- java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
avoid reflection in resolve/replace
Closes #745
> [Java] avoid reflection in resolve/replace

- java/fury-core/src/main/java/io/fury/serializer/ObjectStreamSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
avoid reflection in writeObject/readOject/readObjectNoData
Closes #746
> [Java] avoid reflection in writeObject/readOject/readObjectNoData

- java/fury-core/src/main/java/io/fury/serializer/GuavaSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/ReplaceResolveSerializer.java
- java/fury-core/src/test/java/io/fury/serializer/GuavaSerializersTest.java
optimize guava list serialization
Closes #749
> [Java] optimize guava list serialization

- java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
- java/fury-core/src/test/java/io/fury/util/unsafe/JDKAccessTest.java
add MakeJDKFunction lambda factory
Closes #753
> [Java] add MakeJDKFunction lambda factory

- CODE_OF_CONDUCT.md
Create CODE_OF_CONDUCT.md
Closes #760
> [Doc] Create CODE_OF_CONDUCT.md

- README.md
> [Doc] Fix broken link in README

- java/fury-core/src/main/java/io/fury/resolver/ClassInfo.java
- java/fury-core/src/test/java/io/fury/serializer/SerializersTest.java
fix write replace class failure
Closes #766
> [Java] fix write replace class failure

- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleMode.java
add javadoc for FuryBuilder
Closes #774
> [Doc] add javadoc for FuryBuilder

- docs/guide/java_object_graph_guide.md
add doc for fury creation reuse
Closes #776
> [Doc] add doc for fury creation reuse

- .github/workflows/release-java.yaml
- .github/workflows/release.yaml
- ci/deploy.sh
- ci/run_ci.sh
auto deploy java/python packages
Closes #780 
Closes #779
> [Java][Python] auto deploy java/python packages

- .github/workflows/release-java.yaml
skip release tests
Closes #xxxx
> [CI] skip release tests

- README.md
Corrected grammar and paraphrasing to make the README easier to read
Closes #736
> Corrected grammar and paraphrasing to make the README easier to read

- LICENSE
- java/fury-core/src/main/java/io/fury/serializer/SynchronizedSerializers.java
- java/fury-core/src/test/java/io/fury/serializer/SynchronizedSerializersTest.java
- java/pom.xml
- python/setup.py
use lambda for SynchronizedSerializers factory
Closes #xxxx
> [Java] use lambda for SynchronizedSerializers factory

- LICENSE
- java/fury-core/src/main/java/io/fury/serializer/SynchronizedSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/UnmodifiableSerializers.java
- java/fury-core/src/test/java/io/fury/serializer/UnmodifiableSerializersTest.java
- java/pom.xml
use lambda for unmodifiable serializers factory
Closes #xxxx
> [Java] use lambda for unmodifiable serializers factory

- ci/deploy.sh
replace alpha/beta to a/b for python
Closes #791
> [Python] replace alpha/beta to a/b for python

- ci/deploy.sh
fix python bump version:
- fix missing `-`
- avoid override javascript version
#792
> [Python] fix python bump version

- .github/workflows/release.yaml
- ci/deploy.sh
> [CI] Fix bump version

- .github/workflows/release.yaml
- ci/deploy.sh
Fix python  release failure:
- rename linux wheel  to manylinux
- configure pypa/gh-action-pypi-publish@release/v1
Closes #xxxx
> [CI] Fix py release

- README.md
update python and java install
Closes #xxxx
> [Doc] update python and java install

- README.md
Update java install version to 0.1.0-alpah.5
Closes #730
> [Doc] Update java install version to 0.1.0-alpah.5

- ci/deploy.sh
`pypiantfin` was used in antgroup internally, we should replace pypiantfin by pypi
Closes #xxxx
> [CI] Fix pypi upload

- java/pom.xml
Add core java developer to maven pom
Closes #xxxx
> [Java] Add core java developer to maven pom

- java/fury-core/pom.xml
- java/fury-format/pom.xml
add core java developer to maven modules pom
Closes #xxxx
> [Java] add core java developer to maven modules pom

- java/fury-core/src/main/java/io/fury/codegen/CodeGenerator.java
- java/fury-core/src/test/java/io/fury/codegen/CodeGeneratorTest.java
use soft reference to avoid duplicate codegen
Closes #808
> [Java] use soft reference to avoid duplicate codegen

- README.md
- integration_tests/pom.xml
- java/fury-benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- python/pyfury/__init__.py
Bump version to 0.2.0-SNATSHOT
Closes #xxxx
> Bump version to 0.2.0-SNATSHOT

- java/pom.xml
upgrade guava for CVE-2023-2976
Closes #833
> [Java] upgrade guava for CVE-2023-2976

- .github/workflows/ci.yml
- ci/run_ci.sh
- integration_tests/src/main/java/io/fury/integration_tests/UserTypeDeserializeSuite.java
- integration_tests/src/main/java/io/fury/integration_tests/UserTypeSerializeSuite.java
- integration_tests/src/main/java/io/fury/integration_tests/state/FlatBuffersState.java
- integration_tests/src/test/java/io/fury/integration_tests/state/JDKCompatibilityTest.java
- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
- java/fury-test-core/src/main/java/io/fury/test/bean/BeanA.java
- java/fury-test-core/src/main/java/io/fury/test/bean/TestUtils.java
Add jdk compatible ci to ensure compatibility across jdk
Closes #680
> [Java] Add compatible ci for JDK8/11/13/15/17

- java/fury-core/src/main/java/io/fury/util/function/Functions.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
This pr support generate lambda functions for getter method to reduce reflection cost
Closes #xxxx
> [Java] make getter lambda functions

- java/fury-core/src/main/java/io/fury/util/RecordComponent.java
- java/fury-core/src/main/java/io/fury/util/RecordUtils.java
This pr add jdk record utils for record serialization
#837
> [Java] add record utils

- java/fury-core/src/main/java/io/fury/util/FieldAccessor.java
Support access jdk record field value by generated lambda .
#837
> [Java] Support access record field value

- integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/RecordSerializersTest.java
- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/CompatibleCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/resolver/FieldResolver.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/MetaSharedSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/Serializers.java
- java/fury-core/src/main/java/io/fury/type/Descriptor.java
- java/fury-core/src/main/java/io/fury/type/DescriptorGrouper.java
- java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_Collections.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
This PR support record serialization interpreter mode for:
- schema consist mode
- schema forward/backward mode
- meta share mode
Closes #838 
Closes #839 
Closes #840
> [Java] interpreter mode support for record serialization

- integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/RecordSerializersTest.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/Serializers.java
- java/fury-test-core/src/main/java/io/fury/test/bean/Struct.java
This PR complete record forward/backward serialization in #837 
#839
#837
> [Java] [2/3] Support jdk record forward/backward serialization

- integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/RecordSerializersTest.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/MetaSharedSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/Serializers.java
- java/fury-core/src/main/java/io/fury/util/RecordInfo.java
- java/fury-core/src/main/java/io/fury/util/RecordUtils.java
- Support jdk record metashare mode
- refactor record utils
- support record default value
#842 
#838
> [Java] Support jdk record metashare mode

- java/fury-core/src/main/java/io/fury/builder/CompatibleCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/ObjectCodecOptimizer.java
- java/fury-core/src/main/java/io/fury/codegen/Expression.java
- java/fury-core/src/main/java/io/fury/codegen/ExpressionOptimizer.java
- java/fury-core/src/main/java/io/fury/util/function/Functions.java
- java/fury-core/src/main/java/io/fury/util/function/SerializableBiFunction.java
- java/fury-core/src/main/java/io/fury/util/function/SerializableFunction.java
- java/fury-core/src/main/java/io/fury/util/function/SerializableSupplier.java
- java/fury-core/src/main/java/io/fury/util/function/SerializableTriFunction.java
- java/fury-core/src/main/java/io/fury/util/function/TriFunction.java
- java/fury-core/src/test/java/io/fury/util/FunctionsTest.java
- java/fury-format/src/main/java/io/fury/format/encoder/ArrayDataForEach.java
move inner functions in  `io.fury.util.function.Functions` outside as upper level classes.
Closes #xxxx
> [Java] move inner functions outside

- python/setup.py
add missing shared lib for python
Closes #858
> [Python] add missing shared lib for python

- .github/workflows/release.yaml
- ci/deploy.sh
fix python deploy
Closes #xxxx
> [Python] fix python deploy

- integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/RecordSerializersTest.java
- java/fury-core/src/main/java/io/fury/builder/AccessorHelper.java
- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/CompatibleCodecBuilder.java
- java/fury-core/src/main/java/io/fury/codegen/Expression.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleSerializerBase.java
- java/fury-core/src/main/java/io/fury/type/TypeUtils.java
- java/fury-core/src/main/java/io/fury/util/Platform.java
- java/fury-core/src/main/java/io/fury/util/function/Functions.java
- java/fury-core/src/main/java/io/fury/util/record/RecordUtils.java
Jdk record compatible jit
Closes #841
> [Java] Jdk record compatible jit

- integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/RecordSerializersTest.java
- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/CompatibleCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/MetaSharedCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/codegen/Code.java
- java/fury-core/src/main/java/io/fury/serializer/MetaSharedSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/io/fury/type/DescriptorGrouper.java
- java/fury-core/src/main/java/io/fury/util/record/RecordUtils.java
JIT serialization for JDK record:
- Schema consistent mode
- Meta share mode
Closes #840 
Closes #843
> [Java] JIT serialization for JDK record 

- integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/RecordSerializersTest.java
- integration_tests/latest_jdk_tests/src/test/java/io/fury/integration_tests/Records.java
- java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/codegen/Expression.java
- java/fury-core/src/main/java/io/fury/codegen/ExpressionUtils.java
- java/fury-core/src/main/java/io/fury/type/DescriptorGrouper.java
- java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java
- java/fury-core/src/main/java/io/fury/util/function/Functions.java
- java/fury-core/src/main/java/io/fury/util/unsafe/_JDKAccess.java
- java/fury-core/src/test/java/io/fury/builder/ObjectCodecBuilderTest.java
- java/fury-core/src/test/java/io/fury/codegen/ExpressionVisitorTest.java
- java/fury-format/src/main/java/io/fury/format/encoder/ArrayDataForEach.java
- java/fury-format/src/main/java/io/fury/format/encoder/RowEncoderBuilder.java
- java/fury-test-core/src/main/java/io/fury/test/bean/AccessBeans.java
This pr support private record jit and add tests for private bean and nested private bean.
When supporting private record jit , we found that private final class jit write unnecessary classinfo, we also optimized it in this pr.
Closes #837
> [Java] support private record jit

- README.md
- docs/guide/row_format_guide.md
Fix typo in row foramt doc
Closes #xxxx
> [Doc] Fix row format doc

- docs/guide/java_object_graph_guide.md
- java/fury-core/src/main/java/io/fury/Config.java
- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/MetaSharedCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/MetaSharedSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/Serializers.java
- java/fury-core/src/main/java/io/fury/serializer/UnexistedClassSerializers.java
- java/fury-core/src/main/java/io/fury/type/ClassDef.java
- java/fury-core/src/main/java/io/fury/type/DescriptorGrouper.java
- java/fury-core/src/test/java/io/fury/serializer/CodegenSerializerTest.java
- java/fury-core/src/test/java/io/fury/serializer/CompatibleSerializerTest.java
- java/fury-core/src/test/java/io/fury/type/DescriptorGrouperTest.java
Support compress int long independently
Closes #876
> [Java] Support compress int long independently

- java/fury-test-core/pom.xml
add jdk tools.jar for tests
Closes #880
> [Java] add jdk tools.jar for tests

- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
- java/fury-core/src/test/java/io/fury/FuryTest.java
register common java exception class
Closes #878
> [Java] register common exception

- java/fury-core/src/main/java/io/fury/serializer/CodegenSerializer.java
- java/fury-core/src/test/java/io/fury/serializer/CodegenSerializerTest.java
- Fix async compilation for lazy bean serializer
- Add circualr tests
Closes #xxxx
> [Java] Fix lazy bean serializer

- java/fury-core/src/main/java/io/fury/ThreadLocalFury.java
- java/fury-core/src/main/java/io/fury/ThreadSafeFury.java
- java/fury-core/src/main/java/io/fury/pool/ThreadPoolFury.java
- java/fury-core/src/test/java/io/fury/ThreadSafeFuryTest.java
> [Java] remove getCurrentFury API

- java/fury-core/src/main/java/io/fury/builder/JITContext.java
- java/fury-core/src/main/java/io/fury/collection/FuryObjectMap.java
- java/fury-core/src/test/java/io/fury/collection/FuryObjectMapTest.java
Add fury map iterator api
Closes #xxxx
> [Java] Add fury map iterator api

- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/main/java/io/fury/resolver/AllowListChecker.java
refine AllowListChecker to adapt to dubbo serialization.
#890
> [Java] refine AllowListChecker

- java/fury-core/src/main/java/io/fury/serializer/GuavaSerializers.java
cache generated guava constructor
Closes #898
> [Java] cache generated guava constructor

- ci/run_ci.sh
> [Java] add jdk20 tests

- java/fury-core/src/main/java/io/fury/builder/AccessorHelper.java
- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/codegen/Expression.java
- java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java
- java/fury-core/src/test/java/io/fury/serializer/CodegenSerializerTest.java
fix jit error for package-level field with private type
Closes #906 
Closes #904
> [Java] fix jit error for package-level field with private type

- java/fury-core/src/main/resources/fury/blacklist.txt
> [Java] update blacklist

- python/pyfury/_fury.py
- python/pyfury/_serialization.pyx
- python/pyfury/_serializer.py
- python/pyfury/tests/test_serializer.py
- python/setup.py
Use cloudpickle for local function serialization
Closes #909
> [Python] Use cloudpickle for local function serialization

- docs/guide/java_object_graph_guide.md
- java/fury-core/src/main/java/io/fury/Fury.java
Disable class check by default to save space
Closes #916 
#912
> [Java] disable class check by default

- docs/guide/java_object_graph_guide.md
- add troubleshoting doc
- add customize serializer doc
Closes #xxxx
> [Java] refine java docs

- README.md
> Bump release versin to 0.1.2

- .github/workflows/ci.yml
- ci/run_ci.sh
- go/fury/go.mod
- go/fury/go.sum
- go/fury/util.go
- go/fury/util_test.go
- licenserc.toml
add fury go util and ci tests
Closes #948 
Closes #949
> [Go] add fury go util and ci tests

- go/fury/buffer.go
- go/fury/fury.go
- go/fury/reference.go
- go/fury/serializer.go
- go/fury/type.go
This pr add fury go serialization framework
Closes #953
> [Go] add fury go serialization framework

- java/fury-core/src/main/java/io/fury/builder/ObjectCodecBuilder.java
This pr increase writer index for varint writting in advance to avoid write 5 bytes int using long out-of-bound.
#938
> [Java] fix varint writeindex grow for jit

- go/fury/map.go
This PR add map serializer for fury go.
Closes #958
> [Go] add fury go map serializer

- go/fury/fury.go
- go/fury/struct.go
- go/fury/type.go
This PR includes following changes:
- Add struct serializer for fury go 
- Register type dispatch logic for serializers
Closes #964
> [Go] Add struct serializer for fury go 

- go/fury/reference_test.go
Add ref tracking tests
Closes #966
> [Go] add ref tracking tests

- go/fury/type_test.go
Add  type dispatch tests for fury go
Closes #968
> [Go] add fury type dispatch tests

- go/fury/fury.go
- go/fury/reference.go
- go/fury/reference_test.go
- go/fury/slice.go
rename Reference to Ref
Closes #629
> [Go] rename Reference to Ref

- ci/run_ci.sh
> [Java] add jdk 21 tests

- .github/workflows/ci.yml
- ci/run_ci.sh
- java/pom.xml
- add jdk 21 tests ci.
- Upgreade lombok for jdk21:
Closes #979
> [Java] add jdk 21 tests ci

- java/fury-core/src/main/java/io/fury/memory/MemoryBuffer.java
Optimize sli long read/write
Closes #980
> [Java] Optimize sli long read/write

- README.md
- docs/guide/java_object_graph_guide.md
- go/README.md
upgrade docs:
- Security doc
- Golang readme
- Fury upgrade doc
Closes #xxxx
> [Doc] upgrade docs

- ci/run_ci.sh
fix jdk17_plus_tests fury install:
Closes #xxxx
> [Java] fix jdk17/21 ci latest_jdk_tests skip

- README.md
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- integration_tests/perftests/pom.xml
- java/fury-benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- python/pyfury/__init__.py
bump version to 0.3.0-SNAPSHOT
Closes #xxxx
> bump version to 0.3.0-SNAPSHOT

- README.md
> [Doc] Update JDK support doc 

- README.md
- docs/guide/java_object_graph_guide.md
- docs/guide/xlang_object_graph_guide.md
This pr fix config class imports
Closes #xxxx
> [Doc] fix config class imports

- java/fury-core/src/main/java/io/fury/serializer/ChildContainerSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/CollectionSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/MetaSharedSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectStreamSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/Serializers.java
- java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java
Refine reflection contructor by MethodHandle
Closes #xxxx
> [Java] Refine reflection contructor by MethodHandle

- .github/workflows/ci.yml
> [CI] Revert Maven Dependency Tree Dependency Submission

- java/fury-benchmark/pom.xml
fix janino deps for fury-benchmark
Closes #xxxx
> [Java] fix janino deps for fury-benchmark

- README.md
Build and contribute are actually two concepts. Build refers to compiling code, and how to contribute actually refers to the specifications and processes when submitting a PR. From the documentation, this is mainly about compiling source code, so I changed it to how to build.
Closes #xxxx
- [] tests added / passed (if needed)
- [] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them
> [Improve][Doc] Improve README

- README.md
Bump release version to 0.2.1
Closes #xxxx
> [Doc] Bump release version to 0.2.1

- README.md
The project also seems to have plans to support Rust
Closes #xxxx
- [] tests added / passed (if needed)
- [] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them
> [Impove][Doc] Improve README

- README.md
Update go install doc
Closes #xxxx
> [Doc] Update go install doc

- docs/guide/DEVELOPMENT.md
add java environment requirement
If C++, Python, and Go have version requirements, I can also add to this PR
Closes #xxxx
> [Improve][Doc] add environment requirement

- docs/guide/java_object_graph_guide.md
This pull request fixes some typos from "docs/guide/java_object_graph_guide.md"
referecne -> reference 
duplciate -> duplicate 
Closes #xxxx
> chore(docs): fixed typos

- README.md
- docs/guide/DEVELOPMENT.md
- docs/guide/java_object_graph_guide.md
- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/io/fury/serializer/Serializer.java
Optimize class regisration doc
Closes #xxxx
> [Doc] Optimize class registration doc

- README.md
- docs/guide/DEVELOPMENT.md
- docs/guide/scala_guide.md
> [Doc] refine scala doc

- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/codegen/CodegenContext.java
- java/fury-core/src/main/java/io/fury/codegen/Expression.java
- java/fury-core/src/main/java/io/fury/serializer/CodegenSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/JavaSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/ObjectStreamSerializer.java
- java/fury-core/src/main/java/io/fury/type/TypeUtils.java
- java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java
- java/fury-core/src/test/java/io/fury/serializer/CodegenSerializerTest.java
This  pr supported  local static class jit and fixed scala3 enum jit serialization NPE bug in #1033 
Closes #1033
> [Java] Support local static class jit

- java/fury-core/src/test/java/io/fury/builder/JITContextTest.java
This PR set timeout to JITContextTest to 60s
Closes #xxxx
> [Java] set timeout to JITContextTest

- .github/CODEOWNERS
add auto code reviewers
Closes #xxxx
> [Doc] add auto code reviewers

- README.md
> Update scala link title README.md

- README.md
- docs/README.md
- docs/guide/scala_guide.md
- scala/README.md
add scala readme and refine document
Closes #xxxx
> [Doc] add scala readme and refine document

- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/main/java/io/fury/util/ExceptionUtils.java
- java/fury-core/src/test/java/io/fury/FuryTest.java
This PR  populates StackOverflowError with enable ref tracking message, so that users can know what they need to do.
Closes #1032
> [Java] populate StackOverflowError with enable ref tracking message

- .github/workflows/ci.yml
- .gitignore
- scala/build.sbt
- scala/project/build.properties
- scala/src/test/scala/io/fury/serializer/CollectionSerializerTest.scala
Setup scala project and add collection tests
Closes #1055
> [Scala] Setup scala project

- scala/src/test/scala/io/fury/serializer/TupleTest.scala
> [Scala] add scala tuple serialization tests 

- README.md
- ci/deploy.sh
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- integration_tests/perftests/pom.xml
- java/fury-benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- python/pyfury/__init__.py
- scala/build.sbt
bump version to 0.4.0-SNAPSHOT
Closes #xxxx
> bump version to 0.4.0-SNAPSHOT

- README.md
add scala sbt install doc
Closes #xxxx
> [Doc] add scala sbt install doc

- docs/guide/scala_guide.md
> [Doc] Update scala_guide.md

- docs/guide/scala_guide.md
Add scala 2/3 support doc
Closes #xxxx
> [Doc] Add scala 2/3 support doc

- java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/serializer/ChildContainerSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/CollectionSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/GuavaSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/ImmutableCollectionSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/MapSerializers.java
- java/fury-core/src/main/java/io/fury/type/TypeUtils.java
- java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java
- java/fury-core/src/test/java/io/fury/serializer/CollectionSerializersTest.java
- scala/src/test/scala/io/fury/serializer/CollectionSerializerTest.scala
Refactor collection serialization framework to support writeReplace JIT
Closes #1061
> [Java]  Refactor collection serialization framework to support writeReplace JIT

- scala/build.sbt
> remove unused part of build.sbt

- README.md
add apache license on README
Closes #xxxx
> [Doc] add apache license section to readme

- java/fury-core/src/main/java/io/fury/config/Config.java
- java/fury-core/src/main/java/io/fury/config/FuryBuilder.java
- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
- add switch to disable class check warnings
- disable class check warnings by default when class registration is disabled 
Closes #1083
> [Java] add option to disable class check warnings

- rust/Cargo.toml
- rust/fury-derive/Cargo.toml
- rust/fury/Cargo.toml
- rust/tests/Cargo.toml
Add rust-version to prevent developments being able to compile
Closes #1090
> chore: add rust-version

- docs/guide/xlang_object_graph_guide.md
Add JavaScript sample,  which missing for a long time
Closes #1094
> [DOC] add javascript sample

- bazel/fury.bzl
- python/setup.py
As clarified in https://github.com/alipay/fury/issues/1089#issuecomment-1812515055 by @chaokunyang , the C++ standard is expected to be set to 17.
It closes #1089.
> Make sure the c++ standard is set to 17

- rust/fury-derive/src/lib.rs
- rust/tests/tests/test_complex_struct.rs
Merge FuryMeta、Deserialize and Serialize
Closes #1097
> [Rust] merge derive and make it sample

- java/fury-core/src/main/java/io/fury/Fury.java
throw error if nested fury serialize happen in serialization 
Closes #1102
> [Java] throw error if nested fury serialize happen in serialization 

- src/fury/util/util.h
Remove useless FromXXXEndian
#1096
> [C++] remove useless FromXXXEndian

- rust/fury-derive/src/lib.rs
- rust/fury/src/lib.rs
- rust/fury/src/serializer.rs
- rust/fury/src/types.rs
There are some magic numbers which would confuse developers, replace them with more readable constants.
Closes #1106
> [Rust ] Remove the magic numbers

- rust/fury/src/serializer.rs
Add some doc. Rust code has no comments, which is bad
#1108
> [Rust] chore: add rust doc

- javascript/README.md
Fill in the javascript readme, which is missing for a long time
> [JavaScript] Fill in readme

- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/io/fury/serializer/collection/MapSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/shim/ShimDispatcher.java
Add shim dispatcher to resolve compatibility problems for common used classes, e.g. JSONObject.
> [java] support shim dispatcher to resolve compatibility problems for common used classes

- README.md
- docs/guide/java_object_graph_guide.md
- docs/guide/scala_guide.md
bump release version to 0.3.1
Closes #xxxx
> [Doc] bump release version to 0.3.1

- .github/workflows/release.yaml
fix python release error in #1064 
Closes #xxxx
> [Python] fix python release

- java/fury-core/src/main/java/io/fury/serializer/collection/SynchronizedSerializers.java
- java/fury-core/src/main/java/io/fury/serializer/collection/UnmodifiableSerializers.java
- java/fury-core/src/main/java/io/fury/util/ReflectionUtils.java
- java/fury-core/src/main/resources/META-INF/native-image/org.furyio/fury-core/native-image.properties
make unsafe offset compatible with graalvm
Closes #1116
> [Java] make unsafe offset compatible with graalvm

- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- scala/src/test/scala/io/fury/serializer/ScalaTest.scala
Fix scala package object jit
Closes #1128
> [Scala] Fix scala package object JIT error

- .github/workflows/ci.yml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/pom.xml
- scala/build.sbt
Refine maven pom config
Closes #xxxx
> [Java] Refine maven pom config

- rust/tests/tests/test_complex_struct.rs
> chore/rust: fix typo

- ci/run_ci.sh
> ci/improve: add mesaage about rust ci

- java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/codegen/CodeGenerator.java
- java/fury-core/src/main/java/io/fury/codegen/CodegenContext.java
- java/fury-core/src/main/java/io/fury/codegen/Expression.java
- java/fury-core/src/main/java/io/fury/codegen/FieldInfo.java
- java/fury-core/src/test/java/io/fury/codegen/CodegenContextTest.java
- java/fury-format/src/main/java/io/fury/format/encoder/ArrayEncoderBuilder.java
- java/fury-format/src/main/java/io/fury/format/encoder/MapEncoderBuilder.java
support add static fields
Closes #1146
> [Java] support add static fields in fury codegen

- java/fury-core/src/main/java/io/fury/Fury.java
- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
support create serializer when register class
Closes #1153
> [Java] support create serializer when register class

- java/fury-core/src/main/java/io/fury/serializer/scala/SingletonObjectSerializer.java
add graalvm support for scala singleton: fix unsafe offset for singleton serializer
#1115
> [Scala] add graalvm support for scala singleton

- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/io/fury/serializer/scala/SingletonCollectionSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/scala/SingletonMapSerializer.java
- scala/src/test/scala/io/fury/serializer/CollectionSerializerTest.scala
fix scala singleton map/collection serialization in struct
Closes #1157
> [Scala] Fix scala singleton map/collection serialization in struct

- java/fury-testsuite/src/test/java/io/fury/test/ReadResolveCircularTest.java
add read resolve circular test suite
#1152
> [Java] add read resolve circular test suite

- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- scala/src/test/scala/io/fury/serializer/ScalaTest.scala
Fix package object serialization in scala App
Closes #1165
> [Scala] Fix package object serialization in scala App

- README.md
- docs/README.md
- docs/guide/DEVELOPMENT.md
- docs/guide/graalvm_guide.md
add graalvm usage doc
Closes #1167 
Closes #678
> [Java] add graalvm usage doc

- integration_tests/graalvm_tests/README.md
- integration_tests/graalvm_tests/pom.xml
- integration_tests/graalvm_tests/src/main/java/io/fury/graalvm/Benchmark.java
- integration_tests/graalvm_tests/src/main/java/io/fury/graalvm/Foo.java
- integration_tests/graalvm_tests/src/main/java/io/fury/graalvm/Main.java
- integration_tests/graalvm_tests/src/main/java/io/fury/graalvm/Struct.java
- integration_tests/graalvm_tests/src/main/resources/META-INF/native-image/org.furyio/graalvm_tests/native-image.properties
- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
- add graalvm benchmark
- support create multipel fury for graalvm native image
Closes #1177
> [Java] Add graalvm benchmark

- java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/io/fury/codegen/CodeGenerator.java
- java/fury-core/src/main/java/io/fury/codegen/CodegenContext.java
- scala/src/test/scala/io/fury/serializer/ScalaTest.scala
fix package object inaccessible from source code
Closes #1175
> [Scala] fix package object inaccessible from source code

- README.md
- docs/guide/java_object_graph_guide.md
- docs/guide/scala_guide.md
- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- integration_tests/perftests/pom.xml
- java/fury-benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- python/pyfury/__init__.py
- python/setup.py
- scala/build.sbt
bump release version to 0.4.0
Closes #1183
> [Doc] bump release version to 0.4.0

- src/fury/encoder/row_encoder.h
- src/fury/encoder/row_encoder_test.cc
Here we use visitor pattern to solve the ownership issue for children of writers.
> [C++] Fix ownership problem for children writers by visitor

- rust/fury-derive/src/fury_row.rs
- rust/fury/src/row/bit_util.rs
- rust/fury/src/row/mod.rs
- rust/fury/src/row/reader.rs
- rust/fury/src/row/row.rs
- rust/fury/src/row/writer.rs
- rust/tests/tests/test_row.rs
Support  int8, int16, int32, int64, binary, string, list, date32, and date64.
Close #1201
> [Rust] Row support more types

- README.md
- docs/guide/xlang_object_graph_guide.md
- python/pyfury/_fury.py
- python/pyfury/_serialization.pyx
- python/pyfury/format/encoder.pxi
- python/pyfury/tests/test_cross_language.py
- python/pyfury/tests/test_struct.py
- python/pyfury/type.py
Refine py register class method by merge class_tag and class_id together
Closes #1217 
Closes #1219
> [Python] Refine py register class method

- java/fury-core/src/main/java/io/fury/resolver/ClassResolver.java
Clear extRegistry.getClassCtx if generate serializer class failed
Closes #1220
> [Java] Clear extRegistry.getClassCtx if generate serializer class failed

- src/fury/encoder/row_encode_trait.h
- src/fury/encoder/row_encode_trait_test.cc
We support `std::optional<T>` field types and array element types for `RowEncoder`, e.g.
```c++
struct A {
std::optional<B> x;
...
};
```
> [C++] Support optional fields/elements in RowEncoder

- java/fury-core/src/main/java/io/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/io/fury/serializer/ArraySerializers.java
- java/fury-core/src/main/java/io/fury/serializer/collection/AbstractCollectionSerializer.java
- java/fury-core/src/main/java/io/fury/serializer/collection/ArrayAsList.java
- java/fury-core/src/main/java/io/fury/serializer/collection/CollectionFlags.java
- java/fury-core/src/main/java/io/fury/serializer/collection/FuryArrayAsListSerializer.java
Align string array to collection protocol v2
Closes #1227
> [Java] Align string array to collection protocol v2

- CONTRIBUTING.md
> [Improve] add rust doc

- src/fury/util/status.cc
- src/fury/util/status.h
We can use std::unique_ptr to make Status more easy to implement.
> [C++] Improve Status by using unique_ptr

- ci/format.sh
- ci/run_ci.sh
- javascript/.eslintrc.cjs
- javascript/package.json
- javascript/packages/fury/index.ts
- javascript/packages/fury/lib/classResolver.ts
- javascript/packages/fury/lib/codeGen.ts
- javascript/packages/fury/lib/description.ts
- javascript/packages/fury/lib/fury.ts
- javascript/packages/fury/lib/internalSerializer/any.ts
- javascript/packages/fury/lib/internalSerializer/array.ts
- javascript/packages/fury/lib/internalSerializer/binary.ts
- javascript/packages/fury/lib/internalSerializer/bool.ts
- javascript/packages/fury/lib/internalSerializer/datetime.ts
- javascript/packages/fury/lib/internalSerializer/map.ts
- javascript/packages/fury/lib/internalSerializer/number.ts
- javascript/packages/fury/lib/internalSerializer/set.ts
- javascript/packages/fury/lib/internalSerializer/string.ts
- javascript/packages/fury/lib/internalSerializer/tuple.ts
- javascript/packages/fury/lib/platformBuffer.ts
- javascript/packages/fury/lib/reader.ts
- javascript/packages/fury/lib/referenceResolver.ts
- javascript/packages/fury/lib/type.ts
- javascript/packages/fury/lib/util.ts
- javascript/packages/fury/lib/writer.ts
- javascript/packages/hps/index.ts
> [JavaScript] Add lint tools

- README.md
- docs/guide/java_object_graph_guide.md
- docs/guide/scala_guide.md
bump release version to 0.4.1: https://github.com/alipay/fury/releases/tag/v0.4.1
Closes #xxxx
> [Doc] bump release version to 0.4.1

- README.md
> Rename to Apache Fury in README

- README.md
- docs/guide/java_object_graph_guide.md
- docs/guide/scala_guide.md
Disable class registration is dangerouse, we should enable class registration by default even in doc.
Closes #xxxx
> [Java][Doc] enable requireClassRegistration in example by default

- .asf.yaml
> Add collaborators to workaround unfinished apache ID procedure

- .asf.yaml
cc @chaokunyang @wangweipeng2 waiting for your approval to check the permission.
> chore: reflect PPMC members set up

- README.md
Update twitter id in README.md to ApacheFury
> Update twitter id in README.md to ApacheFury

- NOTICE
- licenses/LICENSE-kryo.txt
- licenses/LICENSE-murmurHash3.js.txt
- licenses/LICENSE-node.txt
> Update NOTICE to mention all the licenses for source files where code is borrowed from different project.

- .github/workflows/ci.yml
- ci/run_ci.sh
- src/fury/meta/type_traits_test.cc
macOS C++ build is added to CI workflow in this PR.
> [CI] Add macos C++ build to ci.yml

- README.md
> Refine words and remove other org links in README

- README.md
> Refine English writing about benchmark in README

- .gitignore
```
On branch main
Untracked files:
(use "git add <file>..." to include in what will be committed)
MODULE.bazel
MODULE.bazel.lock
nothing added to commit but untracked files present (use "git add" to track)
```
Update `.gitignore` to ignore two intermediate files.
> chore(git): update .gitignore

- java/fury-core/src/main/java/org/apache/fury/collection/Collections.java
refine collection builder util to avoid array creation cost and generic array creation warnings
> feat(java): refine collection builder util

- java/fury-core/src/main/java/org/apache/fury/collection/Collections.java
refine collection builder util (#1334), fix collection init size typo
> feat(java): refine collection builder util (#1334), fix collection init size typo

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/CollectionSerializersTest.java
- scala/src/test/scala/org/apache/fury/serializer/CollectionSerializerTest.scala
Fix nested collection cast for scala, we missed nested scala collection/map check before
Closes #1325
> fix(java): fix nested collection cast for scala/java

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/CodecUtils.java
- java/fury-core/src/main/java/org/apache/fury/pool/FuryPooledObjectFactory.java
- java/fury-core/src/main/java/org/apache/fury/util/LoaderBinding.java
fix ClassLoader npe in `loadOrGenCodecClass` mentioned in #1340
> fix(java): fix ClassLoader npe in loadOrGenCodecClass

- CONTRIBUTING.md
- docs/guide/DEVELOPMENT.md
1. Add build and test and environment requirements documentation for JavaScript.
2. Remove the Title Icon in a and keep it consistent with other Title styles (or add all Icon, here I chose to remove the Icon).
> docs(JavaScript): Add build and test documentation for JavaScript

- .github/workflows/ci.yml
Add` 'licenses/**', 'NOTICE', 'DISCLAIMER'` to the files ignored by CI. When these files are modified, CI will not be triggered.
> ci(ci): Add files ignored by CI

- docs/guide/java_object_graph_guide.md
> fix(java): replace implements by extends

- java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java
- java/fury-core/src/main/java/org/apache/fury/codegen/ExpressionOptimizer.java
- java/fury-core/src/test/java/org/apache/fury/builder/ObjectCodecBuilderTest.java
- java/fury-core/src/test/java/org/apache/fury/codegen/javalangnameconflict/MethodSpiltObject.java
fix type conflict in method split in #1370 
Closes #1370 
Related issue: #1366
> fix(java): fix type conflict in method split

- integration_tests/graalvm_tests/pom.xml
- integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/Main.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fury/graalvm/ProxyExample.java
- integration_tests/graalvm_tests/src/main/resources/META-INF/native-image/org.apache.fury/graalvm_tests/native-image.properties
- integration_tests/graalvm_tests/src/main/resources/META-INF/native-image/proxy-config.json
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/JdkProxySerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java
- java/fury-core/src/main/java/org/apache/fury/util/ReflectionUtils.java
support jdk proxy serialization for graalvm, see more in #1364 
Closes #1378
> feat(java): support jdk proxy serialization for graalvm

- java/fury-core/src/main/java/org/apache/fury/serializer/scala/SingletonCollectionSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/scala/SingletonMapSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/scala/SingletonObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/util/unsafe/_Lookup.java
fix get static field by unsafe
Closes #1344
> fix(java): fix get static field by unsafe

- java/fury-core/src/main/java/org/apache/fury/BaseFury.java
- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/ThreadSafeFury.java
Extract the BaseFury interface based on Fury and ThreadSafeFury, and extract the common methods in Fury and ThreadSafeFury into BaseFury.
> chore(java): Extract BaseFury interface

- java/fury-core/src/main/java/org/apache/fury/pool/ClassLoaderFuryPooled.java
> chore(java): Simplified code

- java/fury-core/src/main/java/org/apache/fury/pool/ClassLoaderFuryPooled.java
- java/fury-core/src/test/java/org/apache/fury/pool/ClassLoaderFuryPooledTest.java
Add test for `ClassLoaderFuryPooled`.
> test(java): Add test for ClassLoaderFuryPooled

- integration_tests/latest_jdk_tests/src/test/java/org/apache/fury/integration_tests/ImmutableCollectionSerializersTest.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/GuavaCollectionSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/ImmutableCollectionSerializers.java
- java/fury-core/src/test/java/org/apache/fury/FuryTestBase.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/GuavaCollectionSerializersTest.java
fix immutable collection ref tracking in #1401
> fix(java): fix immutable collection ref tracking

- java/fury-core/src/main/java/org/apache/fury/builder/CodecUtils.java
- java/fury-core/src/main/java/org/apache/fury/codegen/CodeGenerator.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/util/DelayedRef.java
- java/fury-core/src/test/java/org/apache/fury/codegen/CodeGeneratorTest.java
> feat(java): avoid recompilation when gc happens for memory pressure

- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/pom.xml
- javascript/packages/fury/README.md
- javascript/packages/fury/package.json
- javascript/packages/hps/README.md
- javascript/packages/hps/package.json
- python/setup.py
- set license to Apache 2
- add disclaimer: according to https://incubator.apache.org/guides/distribution.html, the release of incubating project should carry with a disclaimer.
Releated issue: #1389
> fix: fix license issue for release

- ci/deploy.sh
- ci/release.py
- ci/run_ci.py
This PR add a `release.py` python script for bump version. In future, we will add other release related function here.
Related issue: #1389
> feat: bump version using python

- java/fury-core/src/main/resources/META-INF/DISCLAIMER
- java/fury-core/src/main/resources/META-INF/NOTICE
- java/fury-core/src/main/resources/META-INF/licenses/LICENSE-janino.txt
- java/fury-core/src/main/resources/META-INF/licenses/LICENSE-kryo.txt
- java/fury-format/src/main/resources/META-INF/DISCLAIMER
- java/fury-format/src/main/resources/META-INF/NOTICE
This PR adds DISCLAIMER and NOTICE for built jars to comply with ASF release policy
> fix(license): add DISCLAIMER and NOTICE for built jars

- java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java
- java/fury-core/src/test/java/org/apache/fury/serializer/SerializersTest.java
The bigdecimal serialization doesn't pass precison, this PR fixed it
> fix(java): fix bigdecimal serializer

- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
> chore(java): Reuse unsafePutPositiveVarInt in unsafeWritePositiveVarInt

- java/fury-core/src/main/java/org/apache/fury/codegen/CodeGenerator.java
> fix(java): fix illegal classname caused by negative hash

- .github/workflows/ci.yml
- java/fury-core/src/main/java/org/apache/fury/util/unsafe/_JDKAccess.java
- java/fury-core/src/main/java/org/apache/fury/util/unsafe/_Lookup.java
- java/fury-core/src/test/java/org/apache/fury/TestUtils.java
This PR add openj9 ci, since we have openj9 users, see #1433 . Class GC in linux distribution are not supported in this PR.
> feat(java): add openj9 ci

- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
refactor readVarUint32 algorithm
Closes #1461
> feat(java): refactor readVarUint32 algorithm

- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
This PR refine writeVarUint64 code for better readbility
> fix(java): refine writeVarUint64 readbility

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
This PR optimizes readVarInt/readInt performance by reduce code size of readVarInt for better jvm jit
> feat(java): reduce readInt/readVarInt code size for for jvm jit inline

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
- java/fury-core/src/test/java/org/apache/fury/memory/MemoryBufferTest.java
- optimize read char jvm jit inline by separate little/big endian methods
- optimize read short jvm jit inline by separate little/big endian methods
- generate unsafe get short code online
- generate unsafe get char code online
> feat(java): optimize read char/short jvm jit inline

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/CodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
- java/fury-core/src/test/java/org/apache/fury/FuryTestBase.java
- java/fury-core/src/test/java/org/apache/fury/memory/MemoryBufferTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/PrimitiveSerializersTest.java
- optimize read float jvm jit inline by separate little/big endian methods
- optimize read double jvm jit inline by separate little/big endian methods
- generate unsafe get float code online
- generate unsafe get double code online
> feat(java): optimize read float/double for jvm jit inline

- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
> chore(java): add comments for loop unrolling.

- java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java
- java/fury-core/src/test/java/org/apache/fury/serializer/SerializersTest.java
> fix(java): fix big integer serialization

- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
Reduce unsafePutPositiveVarInt bytecode size from 192 to 151.
https://github.com/apache/incubator-fury/issues/1466
before
with this pr
> perf(java): Reduce unsafePutPositiveVarInt bytecode size.

- java/benchmark/src/main/java/org/apache/fury/benchmark/CompressStringSuite.java
- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/io/FuryInputStream.java
- java/fury-core/src/main/java/org/apache/fury/memory/BitUtils.java
- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
- java/fury-core/src/main/java/org/apache/fury/resolver/EnumStringResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/BufferSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/PrimitiveSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java
- java/fury-core/src/test/java/org/apache/fury/memory/BitUtilsTest.java
- java/fury-core/src/test/java/org/apache/fury/memory/MemoryBufferTest.java
- java/fury-format/src/main/java/org/apache/fury/format/row/Getters.java
- java/fury-format/src/main/java/org/apache/fury/format/row/Setters.java
- java/fury-format/src/main/java/org/apache/fury/format/row/ValueVisitor.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryArray.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryMap.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryRow.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/BinaryUtils.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/UnsafeTrait.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/writer/BinaryArrayWriter.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/writer/BinaryRowWriter.java
- java/fury-format/src/main/java/org/apache/fury/format/row/binary/writer/BinaryWriter.java
- java/fury-format/src/main/java/org/apache/fury/format/type/DataTypes.java
- java/fury-format/src/main/java/org/apache/fury/format/vectorized/ArrowWriter.java
- java/fury-format/src/test/java/org/apache/fury/format/row/binary/BinaryArrayTest.java
- java/fury-format/src/test/java/org/apache/fury/format/row/binary/BinaryMapTest.java
- java/fury-format/src/test/java/org/apache/fury/format/row/binary/BinaryRowTest.java
rename remaing get/put int/float
#1480
> chore(java): rename remaing get/put int/float

- java/pom.xml
> fix(java): make slf4j optional

- java/fury-core/src/main/java/org/apache/fury/Fury.java
> chore(java): reduce fury caller stack

- java/fury-core/src/main/java/org/apache/fury/logging/LogLevel.java
- java/fury-core/src/main/java/org/apache/fury/logging/LoggerFactory.java
Improve javadoc for logging module.
https://github.com/apache/incubator-fury/issues/1497
> chore(java): Improve javadoc for logging module.

- java/fury-core/src/main/java/org/apache/fury/logging/LoggerFactory.java
THis PR fix fix NilLogger creation introduced in #1503
> fix(java): fix create NilLogger

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java
- java/fury-core/src/main/java/org/apache/fury/util/Platform.java
> perf(java): optimize fury creation speed

- docs/specification/xlang_serialization_spec.md
This pr add doc for why map use chunk by chunk spec
#1413
> feat(spec): add doc for why map use chunk by chunk spec

- .github/ISSUE_TEMPLATE/feature_request.md
> chore: The placeholder is displayed in the form of "<!--...-->"

- java/fury-core/src/test/java/org/apache/fury/collection/MultiKeyWeakMapTest.java
This PR skip weakmap test for openj9 to fix CI failure
> fix(java): skip weakmap test for openj9

- javascript/packages/fury/lib/fury.ts
- javascript/packages/fury/lib/type.ts
- javascript/test/fury.test.ts
1. Add magic number described in protocol
The magic number introduces a binary protocol compatibility change.  But Xlang protocol has not been released yet.
> feat(javaScript): Implement magic number feature

- java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/FuryArrayAsListSerializer.java
This PR removed confused comment and remove generics.
#1560
> fix(license): remove confused comment and remove generics

- .github/workflows/ci.yml
fix macos javascript ci failure
https://github.com/actions/setup-python/issues/850
> fix(javascript): fix macos javascript ci failure

- docs/guide/java_serialization_guide.md
Update java_serialization_guide.md
> chore(doc): fixed a typo

- docs/guide/java_serialization_guide.md
- java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java
enable deserializeUnexistedClass by default
https://github.com/apache/incubator-fury/issues/1564
#1569
> feat(java): enable deserializeUnexistedClass by default

- java/fury-core/src/main/java/org/apache/fury/builder/MetaSharedCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/serializer/ObjectStreamSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/StructSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/SynchronizedSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/UnmodifiableSerializers.java
- java/fury-core/src/main/java/org/apache/fury/util/ExceptionUtils.java
- java/fury-core/src/main/java/org/apache/fury/util/Utils.java
- java/fury-core/src/main/java/org/apache/fury/util/unsafe/_JDKAccess.java
move exception ignore method into Exception util
> chore(java): move ignore method into Exception util

- java/fury-core/src/main/java/org/apache/fury/util/DelayedRef.java
This PR revives soft reference to try to make it has a longer lifetime
> feat(java): revive soft reference

- java/fury-core/src/test/java/org/apache/fury/meta/ClassDefTest.java
- java/fury-core/src/test/java/org/apache/fury/reflect/PlatformTest.java
- java/fury-core/src/test/java/org/apache/fury/reflect/ReflectionUtilsTest.java
- java/fury-core/src/test/java/org/apache/fury/reflect/UnsafeFieldAccessorTest.java
move tests to meta/reflect pkg
#1583 
#1578
> chore(java): move tests to meta/reflect pkg

- java/fury-core/src/main/java/org/apache/fury/serializer/collection/GuavaCollectionSerializers.java
- java/fury-core/src/main/java/org/apache/fury/util/unsafe/_JDKAccess.java
compatible low version guava
- #1593
> fix(java): compatible low version guava(#1593)

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/CompatibleCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/meta/ClassDef.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/MetaSharedSerializer.java
Fix ci failuure introduced in #1556 :
> fix(java): fix getClassDef thead safety

- README.md
- docs/guide/scala_guide.md
- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- python/pyfury/__init__.py
- rust/Cargo.toml
- scala/build.sbt
> chore: bump dev version to 0.6.0

- README.md
> fix(java): remove maven groupId change

- java/fury-testsuite/pom.xml
- java/pom.xml
Currently fury-core still carries slf4j dependency:
This PR make slf4j provided:
```
[INFO] --- maven-dependency-plugin:3.4.0:tree (default-cli) @ graalvm_tests ---
[INFO] org.apache.fury:graalvm_tests:jar:0.6.0-SNAPSHOT
[INFO] \- org.apache.fury:fury-core:jar:0.6.0-SNAPSHOT:compile
[INFO]    \- com.google.guava:guava:jar:32.1.2-jre:compile
[INFO]       +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]       +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO]       +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]       +- org.checkerframework:checker-qual:jar:3.33.0:compile
[INFO]       +- com.google.errorprone:error_prone_annotations:jar:2.18.0:compile
[INFO]       \- com.google.j2objc:j2objc-annotations:jar:2.8:compile …
```
> fix(java): make slf4j provided

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java
- java/fury-core/src/main/java/org/apache/fury/collection/LazyMap.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/ChildContainerSerializers.java
Remove Guava's Collection usages
#1113
Lazy map become slightly more lazy =)
> refactor(java): Remove Guava's Collection usages

- java/pom.xml
> chore(java): remove gpg pinentry-mode

- java/fury-core/src/main/java/org/apache/fury/reflect/TypeRef.java
- java/fury-core/src/main/java/org/apache/fury/reflect/Types.java
- java/fury-core/src/test/java/org/apache/fury/reflect/TypeRefTest.java
fix wildcard capturer capture NullPointerException
Closes #1633
> fix(java): fix wildcard capturer capture NullPointerException

- README.md
> chore(doc): fix example

- rust/fury-derive/Cargo.toml
- rust/fury/Cargo.toml
- rust/fury/src/deserializer.rs
- rust/fury/src/row/row.rs
- rust/fury/src/serializer.rs
- rust/tests/Cargo.toml
- rust/tests/tests/test_complex_struct.rs
- Resolve deprecate warnings from `chrono` dep
- Remove patch version in Cargo.toml
N/A
No
> chore(rust): resolve deprecate warnings

- README.md
- docs/guide/java_serialization_guide.md
according to comments,  should set `requireClassRegistration` to false
> chore(doc): fix doc example code

- ci/run_ci.py
- rust/rust-toolchain.toml
- rust/rustfmt.toml
Setup rustfmt and toolchain for rust
None
None
> chore(rust): Setup rustfmt and toolchain for rust

- .github/workflows/ci.yml
- ci/run_ci.py
- rust/fury/src/buffer.rs
- rust/fury/src/deserializer.rs
- rust/fury/src/row/bit_util.rs
- rust/fury/src/row/mod.rs
- rust/fury/src/serializer.rs
- rust/fury/src/types.rs
Make rust clippy happy.
I fixed all clippy warning and change the CI settings to reject new warnings.
- close https://github.com/apache/incubator-fury/issues/1676
None
> chore(rust): Make rust clippy happy

- .github/workflows/release-java-snapshot.yaml
> fix(java): fix snapshot jar upload

- .idea/vcs.xml
> chore(java): Update github URL in IntelliJ vcs.xml

- README.md
fix badge: twitter -> x
preview:
> docs: fix badge x

- README.md
- docs/guide/row_format_guide.md
fix doc error.`BinaryArray#getLong` not exist
> chore(doc): fix compiler error

- CONTRIBUTING.md
In fact, in Python's code style, here's the hint
```bash
pip install black==22.1.0 flake8==3.9.1 flake8-quotes flake8-bugbear
```
But there is no version of click
black actually depends on click, by default, our click is the latest, so there is a problem of version inconsistency, and then the developer may not know what version is needed, and may upgrade black. Unfortunately, the ci/cd monitoring results are not the same for different versions of black
I think it's the right thing to do to avoid ambiguity
```bash
pip install black==22.1.0 flake8==3.9.1 flake8-quotes flake8-bugbear click==8.0.2
```
https://github.com/apache/fury/blob/main/CONTRIBUTING.md
> fix(doc): codestyle version in python

- python/README.md
Improve documentation
In the java/rust/JavaScript readme, there is a fairly complete development documentation.
but in python it is empty. 
I thought it could be filled in and completed.
> chore(doc): the more complete readme is in python

- java/benchmark/src/test/java/org/apache/fury/benchmark/state/JsonTest.java
- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
> fix(java): fix nested map serialization codegen

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-testsuite/pom.xml
- java/fury-testsuite/src/test/java/org/apache/fury/test/FastJsonTest.java
> fix(java): fix fastjson object serialization

- scala/build.sbt
- scala/project/build.properties
* sbt 1.10.0
* scalatest 3.2.19
* scala 2.13.14
* add Apache Snapshot Repo resolver so you don't need to build the Java jars, the build can get them from the snapshot repo
> build: update scala build

- CONTRIBUTING.md
- cpp/fury/util/BUILD
- cpp/fury/util/string_util.cc
- cpp/fury/util/string_util.h
- cpp/fury/util/string_util_test.cc
ref: https://arxiv.org/pdf/1902.08318.pdf
ref: https://github.com/simdutf/simdutf
I learned about the related simd technology, as well as this paper and project implementation.
Using SIMD technique for string detection.
First, I need to implement the logic and complete the latin character detection
``` c++
// Baseline implementation
bool isLatin_Baseline(const std::string& str) {
for (char c : str) {
if (static_cast<unsigned char>(c) >= 128) {
return false;
}
}
return true;
}
```
Then, I tried to use SSE2 to speed it up, which is obviously a little bit faster, the logic is to read multiple characters at once and then do the bit arithmetic
Obviously, there was a speed boost, but I didn't think it was enough, so I tried it again with AVX2 …
> feat(C++): String detection is performed using SIMD techniques

- rust/fury/src/lib.rs
- rust/fury/src/util.rs
- rust/tests/tests/test_util.rs
Implement an util function converting utf16 encoded string to utf8 string in Rust.
#1547
> feat(Rust): Implement utf16 to utf8 conversion algorithm

- integration_tests/latest_jdk_tests/src/test/java/org/apache/fury/integration_tests/RecordSerializersTest.java
- java/fury-core/src/main/java/org/apache/fury/serializer/AbstractObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/MetaSharedSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/util/record/RecordUtils.java
This PR supports jdk17+ record copy
#1739 
#1701 
Closes #1740
> feat(java): support jdk17+ record copy

- DISCLAIMER
> chore: Update case in DISCLAIMER

- java/fury-core/src/main/resources/META-INF/LICENSE
fix janino commons classes issue
Closes #1745
> fix(java): fix janino commons classes issue

- README.md
- docs/guide/scala_guide.md
- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- rust/Cargo.toml
- scala/build.sbt
> chore: bump dev version to 0.7.0

- README.md
> fix(scala): fix scala release version

- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/config/Config.java
- java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java
- java/fury-core/src/test/java/org/apache/fury/FuryCopyTest.java
rename copyTrackingRef to copyRef
#1679 
#1747
> chore(java): rename copyTrackingRef to copyRef

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/test/java/org/apache/fury/serializer/EnumSerializerTest.java
fix enum abstract field serialization
Closes #1764
> fix(java): fix enum abstract field serialization

- java/benchmark/src/main/java/org/apache/fury/benchmark/CopyBenchmark.java
- java/benchmark/src/main/java/org/apache/fury/benchmark/data/Data.java
- java/benchmark/src/main/java/org/apache/fury/benchmark/state/KryoState.java
- java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java
optimize object array copy perf
Closes #1749
```
Benchmark                             (bufferType)  (references)   Mode  Cnt        Score         Error  Units
CopyBenchmark.fury_copy_object_array         array         false  thrpt    3  3738130.731 ± 2558439.249  ops/s
CopyBenchmark.kryo_copy_object_array         array         false  thrpt    3  1840856.001 ± 3577628.201  ops/s
Benchmark                             (bufferType)  (references)   Mode  Cnt        Score         Error  Units
CopyBenchmark.fury_copy_object_array         array         false  thrpt    3  8025674.789 ± 7659990.718  ops/s
CopyBenchmark.kryo_copy_object_array         array         false  thrpt    3  1167037.754 ± 1372076.679  ops/s
```
> perf(java): optimize object array copy perf

- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/serializer/AbstractObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/SynchronizedSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/UnmodifiableSerializers.java
- java/fury-core/src/test/java/org/apache/fury/FuryCopyTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/SynchronizedSerializersTest.java
support deep ref copy
Closes #1747
https://github.com/apache/fury/issues/1679
> feat(java): support deep ref copy

- rust/fury/src/serializer.rs
fix rust ci failed
https://github.com/apache/fury/issues/1781
> ci: fix rust ci failed

- README.md
- docs/guide/scala_guide.md
- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- rust/Cargo.toml
- scala/build.sbt
> chore: bump release version to 0.7.0

- .github/ISSUE_TEMPLATE/config.yml
- For https://github.com/apache/fury/pull/1807#issuecomment-2294884982
> chore(infra): remove redundant bug reporting options

- java/fury-core/src/main/java/org/apache/fury/codegen/CodeGenerator.java
- java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java
- java/fury-core/src/main/java/org/apache/fury/codegen/Expression.java
- java/fury-core/src/main/java/org/apache/fury/reflect/ReflectionUtils.java
- java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java
- scala/src/test/scala/org/apache/fury/serializer/SingleObjectSerializerTest.scala
> fix(scala): fix nested type serialization in scala object type

- java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java
- java/fury-core/src/test/java/org/apache/fury/codegen/CodegenContextTest.java
> fix(java): fix reserved keyword conflict

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/collection/MapEntry.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java
> fix(java): fix nested map field value serialization by private map serializer

- rust/fury-core/src/types.rs
- rust/fury-derive/src/object/derive_enum.rs
- rust/fury-derive/src/object/misc.rs
- rust/fury-derive/src/object/mod.rs
- rust/fury-derive/src/object/serializer.rs
- rust/tests/tests/test_complex_struct.rs
Support enum serialization for Rust.
Close #1393
> feat(rust): support enum serialization

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/test/java/org/apache/fury/serializer/SerializerFactoryTest.java
fix serializer factory getSerializerClass
> fix(java): fix serializer factory getSerializerClass

- README.md
- docs/guide/scala_guide.md
> chore(doc): bump release version to 0.7.1

- README.md
Fix 'how to upgrade fury' link in README.md
> chore(doc): fix 'how to upgrade fury' link in README

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
> perf(java): optimize read classdef perf

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassInfo.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/test/java/org/apache/fury/serializer/JdkProxySerializerTest.java
fix jdk proxy serialization when proxy writePlace method
Closes #1854
> fix(java): fix jdk proxy serialization when proxy writePlace method

- scala/project/build.properties
- scala/project/plugins.sbt
see https://github.com/mdedetrich/sbt-apache-sonatype/issues/39
> feat(scala): upgrade sbt and sbt-apache-sonatype

- scala/build.sbt
> build(deps): upgrade scala (2.13.15/3.3.4)

- rust/rust-toolchain.toml
> feat(rust):  add rust-analyzer to toolchain

- README.md
- ci/release.py
- docs/guide/scala_guide.md
- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- python/pyfury/__init__.py
- rust/Cargo.toml
> chore(doc): bump release version to 0.8.0

- README.md
- scala/build.sbt
> fix: fix bump snapshot version to 0.9.0

- .github/workflows/ci.yml
- ci/run_ci.sh
- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/test/java/org/apache/fury/builder/JITContextTest.java
- fix async compilation switch for non-public nested class
- fix install sbt for scala
- fix install python
Closes #1879
> fix(java): fix async compilation switch for non-public nested class

- java/fury-core/src/main/java/org/apache/fury/ThreadLocalFury.java
fix add fury thread safety issue
#1840
> fix(java): fix add fury thread safety issue

- java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java
- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/Serializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/StringSerializer.java
- java/fury-core/src/main/java/org/apache/fury/util/StringEncodingUtils.java
- java/fury-core/src/main/java/org/apache/fury/util/StringUtils.java
- java/fury-core/src/test/java/org/apache/fury/builder/JITContextTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/StringSerializerTest.java
- java/fury-core/src/test/java/org/apache/fury/util/StringEncodingUtilsTest.java
> feat(java): Refactor String serialization and deserialization

- java/fury-core/src/main/java/org/apache/fury/AbstractThreadSafeFury.java
- java/fury-core/src/main/java/org/apache/fury/ThreadLocalFury.java
- java/fury-core/src/main/java/org/apache/fury/pool/ThreadPoolFury.java
- kotlin/pom.xml
- kotlin/src/main/java/org/apache/fury/serializer/kotlin/KotlinSerializers.java
- scala/src/main/java/org/apache/fury/serializer/scala/ScalaSerializers.java
support thread safe register callback for scala kotlin
Closes #1894
> feat(java): support thread safe register callback for scala kotlin

- scala/src/main/java/org/apache/fury/serializer/scala/ScalaSerializers.java
- scala/src/main/scala/org/apache/fury/serializer/scala/RangeSerializer.scala
- scala/src/test/scala/org/apache/fury/serializer/scala/RangeTest.scala
> feat(scala): add scala range serializer

- ci/deploy.sh
> chore(scala): add scala build script

- kotlin/pom.xml
add parent pom for fury kotlin
> chore(kotlin): add parent pom for fury kotlin

- scala/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties
> fix(scala): fix scala native-image.properties

- integration_tests/cpython_benchmark/README.md
- integration_tests/cpython_benchmark/fury_benchmark.py
- python/pyfury/_fury.py
Enhance the Python benchmark script to support more parameter options
> perf(python): Enhance the Python benchmark script

- rust/fury-core/src/row/row.rs
- rust/fury-core/src/row/writer.rs
Fix the lint warnings in issue #1961 which was caused by the upgrade of clippy.
#1961
> chore(Rust): fix lint problems

- python/pyfury/_serialization.pyx
In Python, to implement a linear memory structure that stores key-value pairs, we can traverse them in the order of insertion like accessing an array. However, Cython does not provide a direct access interface, and these interfaces are internal in CPython, requiring compatibility work to use them correctly. Nevertheless, we can still use the`PyDict_Next` interface to replace the `items` method. Essentially, `items` use `PyDict_Next` to append to a list. Doing so can reduce the copying overhead.
For large dict
```
[dict_item] 541 us +- 39 us -> [dict_next]  535 us +- 35 us: 1.00x faster
[dict_item] 119.8 MiB +- 1344.0 KiB -> [dict_next] 118.8 MiB +- 1338.4 KiB: 1.01x faster
```
> perf(python): Directly access the key-value pairs of a dict

- .github/workflows/ci.yml
- .github/workflows/release.yaml
- python/pyfury/_fury.py
- python/pyfury/_serialization.pyx
- python/setup.py
This pr drop py3.7 support
Closes #1982
> chore(python): drop py3.7 support

- cpp/fury/util/platform.h
- cpp/fury/util/string_util.cc
- cpp/fury/util/string_util.h
- cpp/fury/util/string_util_test.cc
1、Inline `string_util.cc` function to `string_util.h`
2、Clearer judgment of conditions:`if defined(USE_IMMINTRIN_SIMD)`
3、Remove redundant code
> chore(c++): Function inlining and code tuning

- NOTICE
- java/fury-core/src/main/resources/META-INF/NOTICE
- java/fury-format/src/main/resources/META-INF/NOTICE
> docs: update copyright date in NOTICE

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java
fix duplicate entry write at max chunk size bound
#2025
#2027
> fix(java): fix duplicate entry write at max chunk size bound

- .github/workflows/ci.yml
- ci/deploy.sh
- ci/run_ci.sh
- python/setup.py
add macos pyfury ci:
- macos13: x86
- macos14: arm64
> feat(python): add macos pyfury ci

- java/benchmark/pom.xml
some dependency in benchmark pom is duplicate, remove them
> fix(java): Remove duplicate maven dependency

- .github/workflows/release.yaml
- ci/deploy.sh
- python/setup.py
- Add automatic release pyfury on macos windows
- Fix windows wheel build missing add pyd files
#798 
#1885
> feat(python): automatic release pyfury on macos and windows

- docs/guide/java_serialization_guide.md
update java serialization schema compatibility doc
> docs(java): update java serialization schema compatibility doc

- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-extensions/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- kotlin/pom.xml
- python/pyfury/__init__.py
- rust/Cargo.toml
- scala/build.sbt
bump release version to 0.10.0
> chore: bump release version to 0.10.0

- docs/guide/java_serialization_guide.md
- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/meta/ClassDefEncoder.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassInfo.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/resolver/TypeNameBytes.java
- java/fury-core/src/main/java/org/apache/fury/resolver/XtypeResolver.java
- java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties
- java/fury-core/src/test/java/org/apache/fury/resolver/ClassInfoTest.java
- java/fury-core/src/test/java/org/apache/fury/resolver/ClassResolverTest.java
support register type by name in java
Closes https://github.com/apache/fury/discussions/1969
> feat(java): support register type by name in java

- BUILD
- CONTRIBUTING.md
- bazel/fury_deps_setup.bzl
> build(bazel): Extracts compile_commands.json

- java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java
- java/fury-core/src/test/java/org/apache/fury/StreamTest.java
fix read null chunk out of bound
Closes #2062
> fix(java): fix read null chunk out of bound

- java/fury-core/src/main/java/org/apache/fury/builder/ObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/io/FuryInputStream.java
- java/fury-core/src/test/java/org/apache/fury/StreamTest.java
fix read primitives error on fill buffer bound
Closes #2060
> fix(java): fix read primitives error on fill buffer bound

- java/fury-core/src/main/java/org/apache/fury/memory/MemoryBuffer.java
- java/fury-core/src/main/java/org/apache/fury/meta/MetaStringEncoder.java
In this update, the bit manipulation logic within the MetaStringEncoder::encodeGeneric method has been optimized for better performance. The original implementation processed the bits one at a time in each loop iteration, updating only a single bit per cycle. The new approach improves efficiency by processing multiple bits (up to one byte) per loop iteration, reducing the number of iterations required and minimizing the overhead of bit-level operations.
| Test # | encodeGeneric (ms) | new encodeGeneric (ms) |
|--------|--------------------|---------------------|
| 1      | 102                | 27                  |
| 2      | 85                 | 29                  |
| 3      | 86                 | 29                  |
| 4      | 81                 | 26                  |
| 5      | 94 …
> perf(java): Optimize Computational Efficiency of MetaStringEncoder::encodeGeneric

- README.md
> Update snapshot version

- java/fury-core/src/main/java/org/apache/fury/serializer/ImmutableSerializer.java
- java/fury-core/src/main/java/org/apache/fury/util/LoaderBinding.java
> fix(java): Modify some mistake

- java/fury-core/src/main/resources/fury/disallowed.txt
Add extra entry to disallowed file.
> feat(java): extra entry in disallowed.txt

- java/fury-core/src/main/java/org/apache/fury/resolver/DisallowedList.java
- java/fury-core/src/main/resources/fury/disallowed.txt
use sha256 to check disallowed.txt tamper
Closes #2100
> feat(java): use sha256 to check disallowed.txt tamper

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/NoneSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractCollectionSerializer.java
- java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/CollectionSerializersTest.java
> fix(java): fix serialization npe of collection with all null elems

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
> fix(java): fix not null value flag

- java/fury-core/src/main/java/org/apache/fury/meta/ClassDef.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedCompatibleTest.java
> fix(java): use registered id to sort fields

- java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java
- java/fury-core/src/test/java/org/apache/fury/type/TypeUtilsTest.java
support nested bean in array/collection/map for row format
Closes #2106
> feat(java): support nested bean in array/collection/map for row format

- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/meta/ClassDef.java
- java/fury-core/src/main/java/org/apache/fury/meta/ClassDefDecoder.java
- java/fury-core/src/main/java/org/apache/fury/meta/ClassDefEncoder.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/type/Descriptor.java
- java/fury-core/src/main/java/org/apache/fury/type/TypeUtils.java
- java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedCompatibleTest.java
> feat(java): support inconsistent registration by name/id

- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-extensions/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- kotlin/pom.xml
- python/pyfury/__init__.py
- rust/Cargo.toml
- scala/build.sbt
> chore: bump version to 0.10.1

- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/builder/CompatibleCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/resolver/TypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/resolver/XtypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/CompatibleSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractCollectionSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/GuavaCollectionSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/SerializationBinding.java
- java/fury-core/src/main/java/org/apache/fury/type/GenericType.java
- java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties
- python/pyfury/_serialization.pyx
- scala/src/main/scala/org/apache/fury/serializer/scala/RangeSerializer.scala
This PR supports xlang map chunk serialization between java/python
Closes #2125 
Closes #2126
> feat: xlang map chunk serialization between java/python

- .github/workflows/ci.yml
- ci/run_ci.sh
- java/fury-core/src/main/java/org/apache/fury/resolver/DisallowedList.java
- java/fury-core/src/test/java/org/apache/fury/resolver/DisallowedListTest.java
- add windows ci for java21
- Fix sha256 check error on windows:
Closes #2100
> fix(java): fix disallowedlist filechekc on windows

- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/config/FuryBuilder.java
- java/fury-core/src/main/java/org/apache/fury/resolver/XtypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/StructSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractCollectionSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/GuavaCollectionSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/SerializationBinding.java
- java/fury-core/src/test/java/org/apache/fury/CrossLanguageTest.java
- python/pyfury/_fury.py
- python/pyfury/_registry.py
- python/pyfury/_serialization.pyx
- python/pyfury/_serializer.py
- python/pyfury/serializer.py
- python/pyfury/tests/test_cross_language.py
- python/pyfury/type.py
This PR implements homogeneous xlang  collection serialization between java/python. Changes include:
- Xlang homogeneous  collection serialization in cython/python
- Xlang chunk map serialization in pure python for debug
- Use  homogeneous  collection serialization in java
- homogeneous  collection serialization between java and python
Closes #2131 
Closes #2132
> feat: xlang homogeneous collection serialization between java/python

- .github/workflows/ci.yml
- ci/release.py
> feat(chore): bump version support kotlin

- java/fury-core/src/main/java/org/apache/fury/Fury.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/resolver/TypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/resolver/XtypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/MetaSharedSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/NonexistentClassSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/ObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/SerializationBinding.java
- java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties
> refactor(java): refactor object serializer for unifying xlang/java serialization in java

- java/fury-core/src/main/java/org/apache/fury/resolver/DisallowedList.java
It appears that [PR #2128](https://github.com/apache/fury/pull/2128) did not truly resolve this issue, as it only modified the test case code without addressing the actual runtime logic. This PR re-fixes the problem.
> fix(java): fix DisallowedList calculate hash in Windows

- java/fury-core/src/main/java/org/apache/fury/type/DescriptorGrouper.java
> chore(java): Update the content that needs to be corrected when reading the code.

- java/fury-core/src/main/resources/META-INF/NOTICE
- java/pom.xml
- kotlin/pom.xml
> fix: update copyright year to 2025

- java/fury-core/src/main/resources/META-INF/NOTICE
- java/pom.xml
- kotlin/pom.xml
> chore: update copyright year to 2025

- README.md
- docs/guide/scala_guide.md
- kotlin/pom.xml
> chore: bump release version to 0.10.1

- java/fury-core/src/main/java/org/apache/fury/logging/FuryLogger.java
- java/fury-core/src/test/java/org/apache/fury/logging/Slf4jLoggerTest.java
> fix(java): fix fury logger log exception

- .github/workflows/ci.yml
- java/fury-core/src/main/java/org/apache/fury/logging/FuryLogger.java
- java/fury-core/src/test/java/org/apache/fury/logging/Slf4jLoggerTest.java
> fix(java): Fix logger error

- .github/workflows/ci.yml
- java/fury-core/src/main/java/org/apache/fury/logging/FuryLogger.java
- java/fury-core/src/main/java/org/apache/fury/resolver/DisallowedList.java
- java/fury-core/src/main/resources/META-INF/NOTICE
- java/fury-core/src/test/java/org/apache/fury/logging/Slf4jLoggerTest.java
- java/pom.xml
- kotlin/pom.xml
> chore: cherypick commits for 0.10.2

- java/fury-core/src/main/java/org/apache/fury/serializer/collection/AbstractMapSerializer.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java
> fix(java): fix nested chunk map serialization error when generics exists

- java/fury-core/src/main/java/org/apache/fury/resolver/XtypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/AbstractObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/CollectionSerializers.java
- java/fury-core/src/main/java/org/apache/fury/serializer/collection/MapSerializers.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/XlangCollectionSerializerTest.java
fix xlang container field deserialization type error
Closes #2105
> fix(java): fix xlang container field deserialization type error

- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/resolver/TypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/resolver/XtypeResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/AbstractObjectSerializer.java
- java/fury-core/src/main/java/org/apache/fury/serializer/SerializationUtils.java
- java/fury-core/src/test/java/org/apache/fury/CrossLanguageTest.java
- python/pyfury/_serialization.pyx
- python/pyfury/_serializer.py
- python/pyfury/_struct.py
- python/pyfury/tests/test_cross_language.py
- python/pyfury/type.py
support more final types in xlang serialization:
- enum
- timestamp/date
- primitive array
Closes #2163
> feat(java): support enum/time/array final types in xlang serialization

- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-extensions/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- kotlin/pom.xml
- python/pyfury/__init__.py
- rust/Cargo.toml
- scala/build.sbt
> chore: bump version 0.10.2

- ci/release.py
Cherry-pick https://github.com/apache/fury/pull/2134 into the releases-0.10 branch to save the step of manually modifying the Kotlin version.
> feat(chore): bump version support kotlin (#2134)

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/codegen/Expression.java
- java/fury-core/src/main/java/org/apache/fury/codegen/ExpressionUtils.java
- java/fury-core/src/test/java/org/apache/fury/codegen/ExpressionTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java
fix nested map chunk serialization codegen
Closes #2170
> fix(java): fix nested map chunk serialization codegen

- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedArraySerializers.kt
- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedSerializer.kt
> fix(kotlin): fix kotlin compile error

- java/fury-core/src/main/java/org/apache/fury/builder/BaseObjectCodecBuilder.java
- java/fury-core/src/main/java/org/apache/fury/codegen/Expression.java
- java/fury-core/src/main/java/org/apache/fury/codegen/ExpressionUtils.java
- java/fury-core/src/test/java/org/apache/fury/codegen/ExpressionTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java
- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedArraySerializers.kt
- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedSerializer.kt
> fix(kotlin): Fix compilation and logical errors for version 0.11

- .github/workflows/ci.yml
- ci/run_ci.sh
Add fury kotlin github CI 8
relate #2174
> feat(kotlin): add kotlin ci 

- .github/workflows/ci.yml
Add multiple versions of kotlin CI
The compatibility of multiple versions has been verified
JDK11
JDK17
JDK21
Closes #2174
> perf(kotlin): Add multiple versions of kotlin CI

- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedArraySerializers.kt
- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedSerializer.kt
cherrypick https://github.com/apache/fury/pull/2173 into releases-0.10
> fix(kotlin): fix kotlin compile error (#2173)

- .github/workflows/ci.yml
- ci/run_ci.sh
- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedArraySerializers.kt
- kotlin/src/main/kotlin/org/apache/fury/serializer/kotlin/UnsignedSerializer.kt
cp https://github.com/apache/fury/pull/2176
> feat(kotlin): add kotlin ci  (#2176)

- ci/run_ci.sh
- python/pyproject.toml
- python/setup.py
> fix(python): fix pyfury build using pyproject.toml

- README.md
- docs/guide/scala_guide.md
> chore: bump release version to 0.10.2

- java/benchmark/pom.xml
- java/benchmark/src/main/java/org/apache/fury/benchmark/state/ProtoBuffersState.java
- java/benchmark/src/test/java/org/apache/fury/benchmark/state/ProtobufSerializerTest.java
- java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java
- java/fury-core/src/main/java/org/apache/fury/serializer/shim/ProtobufDispatcher.java
- java/fury-core/src/main/resources/META-INF/native-image/org.apache.fury/fury-core/native-image.properties
- java/fury-extensions/pom.xml
- java/fury-extensions/src/main/java/org/apache/fury/serializer/ByteStringSerializer.java
- java/fury-extensions/src/main/java/org/apache/fury/serializer/ProtobufSerializer.java
add protobuf serializer for message and byte string
#1945
> feat(java): add protobuf serializer for message and byte string

- java/fury-core/src/main/java/org/apache/fury/meta/ClassDefEncoder.java
- java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedCompatibleTest.java
> fix(java): fix field super class missing in compatible mode

- docs/specification/java_serialization_spec.md
- docs/specification/xlang_serialization_spec.md
update type meta encoding
#2197
> feat(spec): update type meta encoding

- java/fury-core/src/test/java/org/apache/fury/FuryTestBase.java
- java/fury-core/src/test/java/org/apache/fury/serializer/CodegenCompatibleSerializerTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/CodegenSerializerTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedCompatibleTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/MetaSharedObjectSerializerTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/NonexistentClassSerializersTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/ProtocolInteroperabilityTest.java
- java/fury-core/src/test/java/org/apache/fury/serializer/collection/MapSerializersTest.java
> chore(java): reduce java test log

- .asf.yaml
> chore(.asf.yaml): enable rebase-and-merge button

- .github/workflows/release.yaml
> fix(ci): fix releases-0.10.3 ci

- java/pom.xml
Update Janino compiler to latest version with various bugfixes
> chore(java): janino 3.1.12

- .github/workflows/ci.yml
> chore(javascript): remove nodejs 12 support

- java/fury-extensions/pom.xml
mark fury-test-core as test dep in fury extensions
Closes #2228
> fix(java): mark fury-test-core as test dep in fury extensions

- .github/workflows/ci.yml
- java/fury-extensions/pom.xml
> chore: cherry-pick commits for 0.10.3

- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fury-core/pom.xml
- java/fury-extensions/pom.xml
- java/fury-format/pom.xml
- java/fury-test-core/pom.xml
- java/fury-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fury/package.json
- javascript/packages/hps/package.json
- kotlin/pom.xml
- python/pyfury/__init__.py
- rust/Cargo.toml
- scala/build.sbt
> chore: Bump version to 0.10.3

- go/README.md
- go/fury/buffer.go
Delete the redundant comments and add the document.
> chore: Delete the redundant comments and add the document

- README.md
- docs/guide/scala_guide.md
chore: bump release version to 0.10.3
> chore: bump release version to 0.10.3

- go/fury/buffer.go
- go/fury/meta/meta_string.go
- go/fury/type.go
1、Optimize the type registration system，Use type instead of String to reduce copying，Reduce useless code
2、Add the buffer tool. For subsequent use, continue to optimize metastringbytes
> perf(go): Optimize the type registration system && Reduce useless code 

- README.md
> chore: keep fury for maven artifact

- java/fory-core/src/main/java/org/apache/fory/Fory.java
- java/fory-core/src/main/java/org/apache/fory/builder/MetaSharedCodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/builder/ObjectCodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/config/ForyBuilder.java
- java/fory-core/src/main/java/org/apache/fory/meta/ClassDef.java
- java/fory-core/src/main/java/org/apache/fory/serializer/MetaSharedSerializer.java
- java/fory-core/src/main/java/org/apache/fory/serializer/NonexistentClassSerializers.java
- java/fory-core/src/main/java/org/apache/fory/serializer/ObjectSerializer.java
- java/fory-core/src/main/java/org/apache/fory/serializer/Serializer.java
- java/fory-core/src/test/java/org/apache/fory/xlang/MetaSharedXlangTest.java
This PR supports meta shared serialization for xlang in java.
Multi-dimensional array field is not supported in this PR. We track it in #2197
#2197
> feat(java): support meta shared serialization for xlang in java

- java/fory-test-core/src/main/java/org/apache/fory/test/TestUtils.java
existing code works if python is installed but not pyfory, but on Mac the default name for Python is `python3` and there is no `python` at all by default
> chore(java): fix xlang test skip in the case where there is no Python at all

- python/pyfory/__init__.py
- python/pyfory/_fory.py
- python/pyfory/_registry.py
- python/pyfory/_serialization.pyx
- python/pyfory/_serializer.py
- python/pyfory/_struct.py
- python/pyfory/error.py
- python/pyfory/format/infer.py
- python/pyfory/serializer.py
- python/pyfory/tests/test_cross_language.py
- python/pyfory/tests/test_serializer.py
- python/pyfory/tests/test_struct.py
replace "_class" prefix with "_type" in metashare
#2289
> feat(python): replace "_class" prefix with "_type" in metashare

- README.md
> chore: ppdate fory rename in README.md

- README.md
Some of the Fury refs will need to stay for a while.
> chore: Some Fory changes in README.md

- integration_tests/cpython_benchmark/fory_benchmark.py
- python/pyproject.toml
> fix(python): update python benchmark script

- bazel/fory_deps_setup.bzl
- integration_tests/cpython_benchmark/fory_benchmark.py
- java/fory-core/src/main/java/org/apache/fory/meta/ClassDef.java
- java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
- java/fory-core/src/main/java/org/apache/fory/resolver/XtypeResolver.java
- java/fory-core/src/main/java/org/apache/fory/type/CustomTypeRegistry.java
- java/fory-core/src/main/java/org/apache/fory/type/TypeUtils.java
- java/fory-core/src/test/java/org/apache/fory/resolver/ClassResolverTest.java
- java/fory-core/src/test/java/org/apache/fory/xlang/MetaSharedXlangTest.java
- java/fory-format/src/main/java/org/apache/fory/format/encoder/ArrayDataForEach.java
- java/fory-format/src/main/java/org/apache/fory/format/encoder/ArrayEncoderBuilder.java
- java/fory-format/src/main/java/org/apache/fory/format/encoder/BaseBinaryEncoderBuilder.java
- java/fory-format/src/main/java/org/apache/fory/format/encoder/CustomCodec.java
- java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java
- java/fory-format/src/main/java/org/apache/fory/format/type/CustomTypeEncoderRegistry.java
- java/fory-format/src/main/java/org/apache/fory/format/type/CustomTypeHandler.java
- java/fory-format/src/main/java/org/apache/fory/format/type/TypeInference.java
- java/fory-format/src/test/java/org/apache/fory/format/encoder/CustomCodecTest.java
- python/pyproject.toml
> chore: cp more commits to 0.11.0

- README.md
> chore: Update README.md for fory rename

- README.md
> chore: update slack invite link to fory

- .github/workflows/ci.yml
> fix(python): fix py3.13 ci on windows

- README.md
- docs/guide/scala_guide.md
- integration_tests/graalvm_tests/pom.xml
- integration_tests/jdk_compatibility_tests/pom.xml
- integration_tests/jpms_tests/pom.xml
- integration_tests/latest_jdk_tests/pom.xml
- java/benchmark/pom.xml
- java/fory-core/pom.xml
- java/fory-extensions/pom.xml
- java/fory-format/pom.xml
- java/fory-test-core/pom.xml
- java/fory-testsuite/pom.xml
- java/pom.xml
- javascript/packages/fory/package.json
- javascript/packages/hps/package.json
- kotlin/pom.xml
- python/pyfory/__init__.py
- rust/Cargo.toml
- scala/build.sbt
> chore: bump release version to 0.11.0

- java/fory-core/src/main/java/org/apache/fory/reflect/ReflectionUtils.java
- java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
- java/fory-core/src/test/java/org/apache/fory/resolver/ClassResolverTest.java
fix register serializer for abstract class
#2345 #2311
> fix(java): fix register serializer for abstract class

- docs/guide/DEVELOPMENT.md
- docs/guide/java_serialization_guide.md
This PR add documents for customized map collection serializers
> docs: add document for customized map collection serializers

- java/fory-core/src/main/java/org/apache/fory/builder/BaseObjectCodecBuilder.java
- java/fory-core/src/test/java/org/apache/fory/serializer/collection/MapSerializersTest.java
> fix(java): fix map nested array type serialization codegen

- docs/guide/java_serialization_guide.md
- docs/specification/xlang_serialization_spec.md
> docs: fix document markdown lint error

- docs/guide/java_serialization_guide.md
> docs: Update java_serialization_guide.md - fury --> fory

- java/fory-core/src/main/java/org/apache/fory/codegen/CodeGenerator.java
- java/fory-core/src/main/java/org/apache/fory/collection/Collections.java
- java/fory-core/src/main/java/org/apache/fory/reflect/ReflectionUtils.java
- java/fory-core/src/main/java/org/apache/fory/type/Descriptor.java
- java/fory-core/src/main/java/org/apache/fory/util/LoaderBinding.java
- java/fory-core/src/main/java/org/apache/fory/util/function/Functions.java
- java/fory-core/src/main/resources/META-INF/native-image/org.apache.fory/fory-core/native-image.properties
fix weak map thread safety
Closes #2367
> fix: fix WeakHashMap thread safety

- README.md
> docs: update jdk 24 support in README.md

- README.md
- ci/generate_release_note.py
- docs/guide/scala_guide.md
> chore: bump version 0.11.1

- java/fory-core/pom.xml
fix automatic module conflict with maven shaded dependencies
Closes #2371
> fix(java): fix automatic module conflict with maven shaded dependencies

- scala/project/build.properties
- scala/project/plugins.sbt
Keep sbt and plugins up to date
> chore(Scala): upgrade sbt and plugins

- scala/src/test/scala-3/org/apache/fory/serializer/scala/ScalaEnumTest.scala
basic unit test for a Scala 3 enum
> chore(Scala): add test for Scala 3 enum

- README.md
- docs/guide/scala_guide.md
> chore: bump release version to 0.11.2

- docs/guide/java_serialization_guide.md
- docs/guide/row_format_guide.md
> chore(docs): Fix the names of some documents

- CONTRIBUTING.md
The command 'ruff format' is in the python directory, does not need to add 'python' parameter.
> docs: fix ruff command

- bazel/arrow/pyarrow_configure.bzl
- ci/format.sh
- docs/guide/java_serialization_guide.md
- docs/specification/java_serialization_spec.md
- docs/specification/xlang_serialization_spec.md
- go/fory/fory.go
> chore: fix typos

- dart/packages/fory-test/lib/util/test_process_util.dart
- dart/packages/fory/lib/src/codegen/analyze/impl/annotation/key_annotation_analyzer.dart
- dart/packages/fory/lib/src/memory/byte_reader_impl.dart
> chore: translate comments

- java/fory-core/src/main/java/org/apache/fory/serializer/collection/AbstractMapSerializer.java
- java/fory-core/src/test/java/org/apache/fory/serializer/CodegenSerializerTest.java
> fix(java): crash when map only contains null value

- .github/workflows/ci.yml
- .github/workflows/release-java-snapshot.yaml
- ci/run_ci.py
- ci/tasks/java.py
- java/fory-format/pom.xml
use java11 for fory-format module
#2422
> feat(java): use java11 for fory-format module

- ci/run_ci.py
- ci/tasks/java.py
- java/pom.xml
> fix(java): fix install jdks

- python/pyfory/_fory.py
- python/pyfory/_serialization.pyx
> feat(python): add register api for python

- java/fory-core/src/main/java/org/apache/fory/builder/BaseObjectCodecBuilder.java
- java/fory-core/src/test/java/org/apache/fory/serializer/collection/ChildContainerSerializersTest.java
> fix(java): fix map/list element type same with collection type jit error

- java/fory-core/src/main/java/org/apache/fory/type/TypeUtils.java
- java/fory-format/src/main/java/org/apache/fory/format/encoder/RowEncoderBuilder.java
- java/fory-format/src/test/java/org/apache/fory/format/encoder/RowEncoderTest.java
> fix(java): fix row encoder for private struct

- .github/workflows/ci.yml
- .github/workflows/release.yaml
- ci/deploy.sh
> fix(python): fix pyfory pypi release

- .github/workflows/release.yaml
- ci/deploy.sh
> fix(python): fix pyfory pypi release (#2473)

- python/pyfory/__init__.py
> chore(python): disable pyfory.format import warning

- .github/workflows/release.yaml
- ci/deploy.sh
- python/pyproject.toml
> fix(python): fix py release on macos 13

- .github/workflows/release.yaml
- ci/deploy.sh
- python/pyproject.toml
> fix(python): fix py releases macos13

- python/pyfory/_fory.py
- python/pyfory/_serialization.pyx
> feat(python): set default languge to python for pyfory

- docs/specification/java_serialization_spec.md
- docs/specification/xlang_serialization_spec.md
correct meta_size_mask in doc.
> docs: fix meta_size_mask

- dart/packages/fory/lib/src/codec/impl/meta_string_decoder_impl.dart
- dart/packages/fory/lib/src/codec/impl/meta_string_encoder_impl.dart
- dart/packages/fory/lib/src/codec/meta_string_decoder.dart
- dart/packages/fory/lib/src/codec/meta_string_encoder.dart
- dart/packages/fory/lib/src/codec/meta_string_encoding.dart
- dart/packages/fory/lib/src/meta/meta_string.dart
- dart/packages/fory/lib/src/meta/meta_string_byte.dart
- dart/packages/fory/lib/src/resolver/impl/tag_str_encode_resolver_impl.dart
fix MetaStrEncoding to MetaStringEncoding, similar to MetaStringBytes
dart/packages/fory/lib/src/meta/meta_string_byte.dart
```
final class MetaStringBytes{
// static late final MetaStringBytes empty;
// static const int defDynamicWriteStrId = -1;
static const int _headerMask = 0xff;
// bytes maybe a view of a larger buffer, do not modify it
final Uint8List _bytes;
final int _hashCode;
```
> chore: fix MetaStrEncoding

- .github/workflows/release-python.yaml
> fix(ci): print workflow head branch

- .github/workflows/build-native-release.yml
> fix(python): add macos 13 release

- .github/workflows/sync.yml
> fix(ci): use lowercase for betahuhn/repo-file-sync-action

- .github/workflows/sync.yml
> fix(ci): use commit hash for repo-file-sync-action

- README.md
- docs/guide/xlang_serialization_guide.md
- javascript/README.md
- javascript/benchmark/index.js
- javascript/benchmark/map.js
- javascript/benchmark/platform-buffer.js
- javascript/package-lock.json
- javascript/packages/fory/package.json
- javascript/packages/hps/package.json
- javascript/test/hps.test.ts
> chore(javascript): rename foryjs to apache-fory and remove install docs

- javascript/README.md
> fix(javascript): remove installation instructions for Apache Fory

- javascript/README.md
Updated installation instructions to reflect that Apache Fory is not available on npm and should be installed from source code.
> fix(javascript): fix install isstructions

- README.md
- docs/guide/scala_guide.md
> chore: bump release version to 0.12.1

- java/fory-core/src/main/java/org/apache/fory/builder/BaseObjectCodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/builder/CodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/builder/MetaSharedCodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/builder/ObjectCodecBuilder.java
- java/fory-core/src/test/java/org/apache/fory/serializer/CodegenSerializerTest.java
> fix(java): fix codegen name conflict

- CONTRIBUTING.md
update `contributing.md` with Rust lint command
> docs: update contributing.md with Rust lint command

- java/fory-core/src/main/java/org/apache/fory/builder/BaseObjectCodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/builder/CodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/builder/MetaSharedCodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/builder/ObjectCodecBuilder.java
- java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
- java/fory-core/src/test/java/org/apache/fory/serializer/CodegenSerializerTest.java
> fix(java): fix codegen name conflict (#2565)

- java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
> fix(java): fix classinfo npe on graalvm

- java/fory-core/src/main/java/org/apache/fory/serializer/ObjectSerializer.java
> fix(java): skip hash compute for abstract field type

- java/fory-core/src/main/java/org/apache/fory/Fory.java
- java/fory-core/src/main/java/org/apache/fory/exception/CopyException.java
- java/fory-core/src/main/java/org/apache/fory/exception/DeserializationException.java
- java/fory-core/src/main/java/org/apache/fory/exception/SerializationException.java
- java/fory-core/src/main/java/org/apache/fory/util/ExceptionUtils.java
- java/fory-core/src/test/java/org/apache/fory/ForyTest.java
- java/fory-core/src/test/java/org/apache/fory/ForyTestBase.java
- java/fory-core/src/test/java/org/apache/fory/resolver/MetaContextTest.java
- java/fory-core/src/test/java/org/apache/fory/serializer/LambdaSerializerTest.java
- java/fory-core/src/test/java/org/apache/fory/serializer/NonexistentClassSerializersTest.java
- java/fory-core/src/test/java/org/apache/fory/serializer/collection/CollectionSerializersTest.java
- java/fory-core/src/test/java/org/apache/fory/serializer/collection/MapSerializersTest.java
> refactor(java): refactor fory java exception hierarchical structure

- rust/README.md
- rust/fory-core/src/lib.rs
- rust/fory-derive/src/lib.rs
- rust/fory/src/lib.rs
> docs(rust): add rust document

- java/fory-core/src/main/java/org/apache/fory/meta/TypeDefEncoder.java
- java/fory-core/src/main/java/org/apache/fory/serializer/ObjectSerializer.java
- java/fory-core/src/main/java/org/apache/fory/type/Types.java
- java/fory-core/src/test/java/org/apache/fory/CrossLanguageTest.java
> fix(java): fix xlang mode meta shared for java

- python/setup.py
> chore: Revert "fix(python): Fix the build dependency failure that occurred in pyfory"

- python/pyfory/meta/typedef.py
> fix(python): Delete the redundant code in typedef

- go/fory/codegen/guard.go
- go/fory/fory.go
- go/fory/map.go
- go/fory/type.go
- go/fory/type_def.go
> chore(go): replace all typ to type_

- java/fory-core/src/main/java/org/apache/fory/meta/TypeDefEncoder.java
- java/fory-core/src/main/java/org/apache/fory/resolver/XtypeResolver.java
- java/fory-core/src/test/java/org/apache/fory/CrossLanguageTest.java
- python/pyfory/tests/test_cross_language.py
fix register by id for xlang metashare mode in java
> fix(java): fix register by id for xlang metashare mode in java 

- go/fory/codegen/generator.go
- go/fory/fory.go
- go/fory/type.go
The current `globalTypeResolver` design has several issues:
- Maintains complex dual state management (global + per-instance)
- Every Fory instance creation requires copying entire global state
Replaced the complex global state management with a lightweight factory function registry
```go
// Heavy global state with full serializer instances
var globalTypeResolver *typeResolver
// Every instance copies all global state
func NewFory() {
for type_, serializer := range globalTypeResolver.typeToSerializers {
fory.typeResolver.typeToSerializers[type_] = serializer  // Full copy
}
}
```
```go
// Lightweight global registry storing only factory functions
var generatedSerializerFactories = struct {
factories map[reflect.Type]func() Serializer
}
// Instance-level registration on demand
func …
```
> refactor(go): Replace globalTypeResolver with factory-based serializer registration

- python/pyfory/_fory.py
- python/pyfory/_serialization.pyx
> feat(python): support limit pyfory depth

- python/pyfory/_fory.py
- python/pyfory/_serialization.pyx
- python/pyfory/_serializer.py
> fix(python): fix pyfory depth limit

- java/fory-core/src/main/java/org/apache/fory/AbstractThreadSafeFory.java
- java/fory-core/src/main/java/org/apache/fory/Fory.java
- java/fory-core/src/main/java/org/apache/fory/ThreadSafeFory.java
- java/fory-core/src/main/java/org/apache/fory/config/ForyBuilder.java
- java/fory-core/src/main/java/org/apache/fory/logging/LoggerFactory.java
- java/fory-core/src/main/java/org/apache/fory/meta/ClassSpec.java
- java/fory-core/src/main/java/org/apache/fory/meta/TypeDefDecoder.java
- java/fory-core/src/main/java/org/apache/fory/meta/TypeDefEncoder.java
- java/fory-core/src/main/java/org/apache/fory/pool/ThreadPoolFory.java
- java/fory-core/src/main/java/org/apache/fory/resolver/AllowListChecker.java
- java/fory-core/src/main/java/org/apache/fory/resolver/ClassInfo.java
- java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
- java/fory-core/src/main/java/org/apache/fory/resolver/TypeChecker.java
- java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java
- java/fory-core/src/main/java/org/apache/fory/resolver/XtypeResolver.java
- java/fory-core/src/main/resources/META-INF/native-image/org.apache.fory/fory-core/native-image.properties
- java/fory-core/src/test/java/org/apache/fory/CrossLanguageTest.java
- java/fory-core/src/test/java/org/apache/fory/ForyCopyTest.java
- java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java
- java/fory-core/src/test/java/org/apache/fory/resolver/AllowListCheckerTest.java
This pr refactored type resolver, which also fixed #2637
Closes #2637
> refactor(java): refactor type resolver

- AGENTS.md
- java/fory-core/src/main/java/org/apache/fory/meta/ClassDef.java
- java/fory-core/src/test/java/org/apache/fory/ForyTestBase.java
- java/fory-core/src/test/java/org/apache/fory/serializer/MetaSharedCompatibleTest.java
> fix(java): fix field converter for xlang

- java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java
- java/fory-core/src/main/java/org/apache/fory/resolver/XtypeResolver.java
- java/fory-core/src/main/java/org/apache/fory/serializer/NonexistentClassSerializers.java
- java/fory-core/src/test/java/org/apache/fory/CrossLanguageTest.java
> feat(java): support deserialize not registered/exsited class/fields for xlang compatible mode

- docs/guide/graalvm_guide.md
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/ArrayExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/Benchmark.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/CompatibleExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/CompatibleThreadSafeExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/Example.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/ObjectStreamExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/ProxyExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/ScopedCompatibleExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/ThreadSafeExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/record/CompatibleRecordExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/record/RecordExample.java
- integration_tests/graalvm_tests/src/main/java/org/apache/fory/graalvm/record/RecordExample2.java
- java/fory-core/src/main/java/org/apache/fory/AbstractThreadSafeFory.java
- java/fory-core/src/main/java/org/apache/fory/BaseFory.java
- java/fory-core/src/main/java/org/apache/fory/Fory.java
- java/fory-core/src/main/java/org/apache/fory/meta/ClassDef.java
- java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
- java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java
- java/fory-core/src/main/java/org/apache/fory/resolver/XtypeResolver.java
- java/fory-core/src/main/java/org/apache/fory/serializer/ObjectStreamSerializer.java
- java/fory-core/src/test/java/org/apache/fory/serializer/RegisterTest.java
1. fix meta share deserialization for register
2. Add register by class name
Fixes #2666
Closes #2605
> fix(java): fix meta share deserialization for register

- rust/fory-core/src/serializer/box_.rs
- rust/fory-core/src/serializer/mod.rs
- rust/tests/tests/test_box.rs
> feat(rust): support box serde for rust

- java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java
- java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java
> fix(java): fix graalvm not use generated serializer

- python/README.md
> docs: fix python readme lint

- ci/tasks/rust.py
- java/fory-core/src/main/java/org/apache/fory/meta/ClassDef.java
- java/fory-core/src/test/java/org/apache/fory/RustXlangTest.java
- java/fory-core/src/test/java/org/apache/fory/xlang/RegisterTest.java
> fix(java): fix xlang typedef encode
